import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createContext,runInContext} from 'node:vm';
import {webcrypto} from 'node:crypto';
function app(){const ctx=createContext({URL,Intl,Date,Map,Set,Number,String,JSON,Array,structuredClone,crypto:webcrypto,localStorage:{getItem:()=>null},window:{addEventListener(){}},document:{addEventListener(){}}});for(const file of ['translations','icons','core','stories','planner','demo','transfer','storefront','product-workflow'])runInContext(readFileSync(new URL('../src/'+file+'.js',import.meta.url),'utf8'),ctx);runInContext("state=demoData();let productFilters={query:'',status:'all',evidence:'all',view:'cards'};",ctx);return code=>runInContext(code,ctx)}
test('schema-v2 legacy records validate and category rendering never changes them',()=>{const run=app(),before=run('JSON.stringify(state)');assert.equal(run('validateImport({app:"Affiliate Intelligence Studio",mode:"real",data:state}).products.length'),3);assert.equal(run('catalogueCategories()[0].id'),'uncategorized');run('storefrontCollection()');assert.equal(run('JSON.stringify(state)'),before)});
test('custom categories, brands and tags survive JSON round trip and are searchable',()=>{const run=app();run("state.products[0].category='Home & garden';state.products[0].brand='Mek';state.products[0].tags='desk, home';state=validateImport(JSON.parse(JSON.stringify({app:'Affiliate Intelligence Studio',mode:'real',data:state})));productFilters.query='Mek'");assert.equal(run('filteredProducts().length'),1);run("productFilters.query='desk'");assert.equal(run('filteredProducts().length'),1);run("productFilters.query='';productFilters.category='custom:Home & garden'");assert.equal(run('filteredProducts().length'),1);assert.equal(run("catalogueCategories().find(c=>c.id==='custom:Home & garden').count"),1)});
test('untrusted metadata is escaped and invalid types/oversized values are rejected',()=>{const run=app();run("state.products[0].category='<img src=x onerror=alert(1)>'");const html=run('storefrontCollection()');assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));run('state.products[0].category={wrong:true}');assert.throws(()=>run('validateImport({app:"Affiliate Intelligence Studio",mode:"real",data:state})'));run("state.products[0].category='a'.repeat(121)");assert.throws(()=>run('validateImport({app:"Affiliate Intelligence Studio",mode:"real",data:state})'))});
test('UI language changes labels but never product category or authored content',()=>{const run=app();run("state.products[0].category='ของใช้ในบ้าน'");const before=run('JSON.stringify(state)');run("lang='en'");assert.equal(run('productCategoryName(state.products[0])'),'ของใช้ในบ้าน');assert.equal(run('productCategoryName(state.products[1])'),'Uncategorized');assert.equal(run('JSON.stringify(state)'),before);assert.equal(run('JSON.stringify(Object.keys(TRANSLATIONS.th).sort())'),run('JSON.stringify(Object.keys(TRANSLATIONS.en).sort())'))});

test('content status prioritizes published then ready and keeps product evidence status separate',()=>{const run=app();run("state.posts=[];state.stories=[]");assert.equal(run('productContentStatus(state.products[0])'),'draft');run("state.stories=[{productId:state.products[0].id,ready:true}]");assert.equal(run('productContentStatus(state.products[0])'),'ready');run("state.posts=[{productId:state.products[0].id}]");assert.equal(run('productContentStatus(state.products[0])'),'published')});
test('chart uses latest same-age snapshots, preserves nulls and groups Bangkok publication days',()=>{const run=app();run(`state.posts=[{id:'a',publishedAt:'2026-10-01T18:00:00Z',metrics:[{window:'72h',observedAt:'2026-10-04T17:00:00Z',clicks:10,confirmed:4,attribution:'post'},{window:'72h',observedAt:'2026-10-04T18:00:00Z',clicks:20,confirmed:8,attribution:'post'}]},{id:'b',publishedAt:'2026-10-02T03:00:00Z',metrics:[{window:'72h',observedAt:'2026-10-05T03:00:00Z',clicks:5,confirmed:100,attribution:'unknown'}]},{id:'c',publishedAt:'2026-10-03T03:00:00Z',metrics:[{window:'72h',observedAt:'2026-10-06T03:00:00Z',clicks:null,confirmed:null,attribution:'post'}]}]`);assert.equal(run("JSON.stringify(commerceSeries(latestRows('72h','all')))"),'[["2026-10-02",25]]');assert.equal(run("total(attributed(latestRows('72h','all')),'confirmed')"),8);assert.equal(run("commerceSeries(latestRows('7d','all')).length"),0);assert.equal(run("total(latestRows('7d','all'),'clicks')"),null)});
