import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createContext,runInContext} from 'node:vm';
import {webcrypto} from 'node:crypto';
function app(){const ctx=createContext({URL,Intl,Date,Map,Set,Number,String,JSON,Array,structuredClone,crypto:webcrypto,localStorage:{getItem:()=>null},window:{addEventListener(){}},document:{addEventListener(){}}});for(const file of ['translations','icons','core','stories','planner','demo','transfer','storefront','product-workflow'])runInContext(readFileSync(new URL('../src/'+file+'.js',import.meta.url),'utf8'),ctx);runInContext("state=demoData();let productFilters={query:'',status:'all',evidence:'all',view:'cards'};",ctx);return code=>runInContext(code,ctx)}
test('schema-v2 legacy records validate and category rendering never changes them',()=>{const run=app(),before=run('JSON.stringify(state)');assert.equal(run('validateImport({app:"Affiliate Intelligence Studio",mode:"real",data:state}).products.length'),3);assert.equal(run('catalogueCategories()[0].id'),'uncategorized');run('storefrontCollection()');assert.equal(run('JSON.stringify(state)'),before)});
test('custom categories, brands and tags survive JSON round trip and are searchable',()=>{const run=app();run("state.products[0].category='Home & garden';state.products[0].brand='Mek';state.products[0].tags='desk, home';state=validateImport(JSON.parse(JSON.stringify({app:'Affiliate Intelligence Studio',mode:'real',data:state})));productFilters.query='Mek'");assert.equal(run('filteredProducts().length'),1);run("productFilters.query='desk'");assert.equal(run('filteredProducts().length'),1);run("productFilters.query='';productFilters.category='custom:Home & garden'");assert.equal(run('filteredProducts().length'),1);assert.equal(run("catalogueCategories().find(c=>c.id==='custom:Home & garden').count"),1)});
test('untrusted metadata is escaped and invalid types/oversized values are rejected',()=>{const run=app();run("state.products[0].category='<img src=x onerror=alert(1)>'");const html=run('storefrontCollection()');assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));run('state.products[0].category={wrong:true}');assert.throws(()=>run('validateImport({app:"Affiliate Intelligence Studio",mode:"real",data:state})'));run("state.products[0].category='a'.repeat(121)");assert.throws(()=>run('validateImport({app:"Affiliate Intelligence Studio",mode:"real",data:state})'))});
test('UI language changes labels but never product category or authored content',()=>{const run=app();run("state.products[0].category='ของใช้ในบ้าน'");const before=run('JSON.stringify(state)');run("lang='en'");assert.equal(run('productCategoryName(state.products[0])'),'ของใช้ในบ้าน');assert.equal(run('productCategoryName(state.products[1])'),'Uncategorized');assert.equal(run('JSON.stringify(state)'),before);assert.equal(run('JSON.stringify(Object.keys(TRANSLATIONS.th).sort())'),run('JSON.stringify(Object.keys(TRANSLATIONS.en).sort())'))});
