const {chromium,webkit}=require('playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..');const users={a:{id:'00000000-0000-4000-8000-000000000001',email:'a@example.test'},b:{id:'00000000-0000-4000-8000-000000000002',email:'b@example.test'}};
function session(user){const exp=Math.floor(Date.now()/1000)+3600;const part=x=>Buffer.from(JSON.stringify(x)).toString('base64url');return {access_token:part({alg:'HS256',typ:'JWT'})+'.'+part({sub:user.id,exp,aud:'authenticated'})+'.test-signature',refresh_token:'fixture-refresh',token_type:'bearer',expires_in:3600,expires_at:exp,user:{...user,aud:'authenticated',role:'authenticated',created_at:new Date().toISOString(),email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email'},user_metadata:{}}};}
(async()=>{const server=http.createServer((req,res)=>{res.setHeader('content-type','text/html;charset=utf-8');res.end(fs.readFileSync(path.join(root,'index.html')))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const engine=process.env.BROWSER==='webkit'?webkit:chromium;const browser=await engine.launch({headless:true,...(engine===chromium?{executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']}: {})});let passed=0,failed=0;
async function test(name,fn){const c=await browser.newContext(),p=await c.newPage(),cloud=new Map(),errors=[];p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));await c.route('https://gfqkexnqbjtuwsyqacsw.supabase.co/**',async route=>{const req=route.request(),url=new URL(req.url()),body=req.postDataJSON();const bearer=req.headers().authorization||'';let uid;try{uid=JSON.parse(Buffer.from(bearer.split('.')[1],'base64url').toString()).sub}catch{}const user=Object.values(users).find(u=>u.id===uid);const reply=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
if(url.pathname==='/auth/v1/token')return reply(session(body.email===users.a.email?users.a:users.b));if(url.pathname==='/auth/v1/user')return reply(user?session(user).user:{message:'Unauthorized'},user?200:401);if(url.pathname==='/auth/v1/logout')return route.fulfill({status:204});if(!user)return reply({message:'Unauthorized'},401);
if(url.pathname.endsWith('/rpc/sp_affiliate_save_workspace')){const old=cloud.get(uid);if((old?.revision||0)!==body.p_expected_revision)return reply({code:'P0001',message:'CLOUD_CONFLICT'},400);const row={revision:(old?.revision||0)+1,payload:body.p_payload,updated_at:new Date().toISOString()};cloud.set(uid,row);return reply({revision:row.revision,updated_at:row.updated_at})}
if(url.pathname.endsWith('/sp_affiliate_workspaces'))return reply(cloud.has(uid)?[cloud.get(uid)]:[]);
if(url.pathname.endsWith('/sp-affiliate-api'))return reply(body.action==='status'?{shopee:'not_configured',ai:'not_configured'}:{error:'SHOPEE_NOT_CONFIGURED'},body.action==='status'?200:503);return reply({error:'Unexpected mock path'},500)});
try{await p.goto('http://127.0.0.1:'+server.address().port);await p.waitForSelector('#nav button');await fn(p,cloud);assert.deepEqual(errors,[]);console.log('PASS',name);passed++}catch(e){failed++;console.error('FAIL',name,e.message);fs.mkdirSync(root+'/test-results',{recursive:true});await p.screenshot({path:root+'/test-results/cloud-failure.png'}).catch(()=>{})}finally{await c.close()}}
async function login(p,key){await p.evaluate(()=>navigateTo('settings'));await p.locator('#cloud-email').fill(users[key].email);await p.locator('#cloud-password').fill('Fixture-password-123');await p.locator('#cloud-login-form button[type=submit]').click();await p.waitForFunction(id=>cloudUser?.id===id&& !cloudChanging,users[key].id)}
await test('credentials excluded from drafts and backups',async p=>{await p.evaluate(()=>navigateTo('settings'));await p.locator('#cloud-email').fill(users.a.email);await p.locator('#cloud-password').fill('Never-store-this-password');const backup=await p.evaluate(()=>JSON.stringify(backupPayload()));assert.ok(!backup.includes('Never-store'));assert.ok(!backup.includes(users.a.email));await p.reload();await p.waitForSelector('#cloud-password');assert.equal(await p.locator('#cloud-password').inputValue(),'')});
await test('login separates guest and account data then logout restores guest',async p=>{await p.evaluate(async()=>{state=demoData();await persist();render()});await login(p,'a');assert.equal(await p.evaluate(()=>state.products.length),0);await p.locator('[data-action="cloud-copy-guest"]').click();await p.locator('[data-action="cloud-confirm-guest"]').click();await p.waitForFunction(()=>state.products.length===3);await p.locator('[data-action="cloud-signout"]').click();await p.waitForFunction(()=>!cloudUser&&!cloudChanging);assert.equal(await p.evaluate(()=>state.products.length),3);await login(p,'b');assert.equal(await p.evaluate(()=>state.products.length),0)});
await test('cloud conflict preserves local data and download retains backup',async(p,cloud)=>{await login(p,'a');await p.evaluate(async()=>{state=demoData();await persist();render()});await p.locator('[data-action="cloud-upload"]').click();await p.waitForFunction(()=>cloudMeta.revision===1&&!cloudBusy);const remote=cloud.get(users.a.id);remote.revision=2;remote.payload.data.profile.audience='Changed remotely';await p.evaluate(()=>state.profile.audience='Local offline edit');await p.locator('[data-action="cloud-upload"]').click();await p.waitForFunction(()=>cloudConflict===true&&!cloudBusy);assert.equal(await p.evaluate(()=>state.profile.audience),'Local offline edit');assert.equal(cloud.get(users.a.id).payload.data.profile.audience,'Changed remotely');await p.locator('[data-action="cloud-download"]').click();await p.locator('[data-action="cloud-confirm-download"]').click();await p.waitForFunction(()=>state.profile.audience==='Changed remotely'&&!cloudChanging);assert.equal(await p.evaluate(async()=>(await readRecord('cloud-backup:'+workspaceKey())).data.profile.audience),'Local offline edit');await p.reload();await p.waitForFunction(()=>cloudUser?.id&&cloudMeta.revision===2);assert.equal(await p.evaluate(()=>state.profile.audience),'Changed remotely')});
await test('service status stays disconnected without credentials',async p=>{await login(p,'a');await p.locator('[data-action="online-status"]').click();await p.waitForFunction(()=>onlineStatus.shopee==='not_configured');assert.equal(await p.evaluate(()=>onlineStatus.ai),'not_configured');assert.ok((await p.locator('#online-services').innerText()).includes('ยังไม่เชื่อมต่อ'))});
await test('AI evidence IDs map back to saved product evidence',async p=>{await login(p,'a');await p.evaluate(async()=>{state=demoData();await persist();const product=state.products[0];const base=makeStory(product,state.profile,0,30,'th','TikTok');base.shots[2].evidence='E1';pendingOnline={kind:'story',context:cloudContext(),owner:cloudUser.id,request:{product,brief:state.profile,duration:30,language:'th',platform:'TikTok'},data:{result:base,model:'fixture',verifiedAt:new Date().toISOString()}};await handleOnlineAction('online-apply-story')});assert.equal(await p.evaluate(()=>storyDraft.shots[2].evidence),await p.evaluate(()=>storyDraft.productId.slice(0,6)+'-E1'));assert.equal(await p.evaluate(()=>storyDraft.ready),false)});
await test('mode change during authentication never uploads demo data',async(p,cloud)=>{await login(p,'a');await p.evaluate(()=>{cloudClient.auth.getUser=()=>new Promise(resolve=>window.releaseCloudAuth=()=>resolve({data:{user:cloudUser}}));window.uploadDone=cloudUpload().catch(()=>{});});await p.locator('#demo').click();await p.waitForFunction(()=>mode==='demo');await p.evaluate(async()=>{releaseCloudAuth();await uploadDone});assert.equal(cloud.size,0)});
await test('late cloud preview cannot expose a previous account',async(p,cloud)=>{await login(p,'a');await p.evaluate(async()=>{state=demoData();state.profile.audience='PRIVATE ACCOUNT A';await persist();await cloudUpload();const row={revision:1,payload:backupPayload()};cloudClient.from=()=>({select:()=>({eq:()=>({maybeSingle:()=>new Promise(resolve=>window.releasePreview=()=>resolve({data:row}))})})});window.previewDone=previewCloud().catch(()=>{});});await p.waitForFunction(()=>typeof window.releasePreview==='function');await p.evaluate(async user=>{await switchCloudUser(user);releasePreview();await previewDone},users.b);assert.equal(await p.evaluate(()=>pendingCloud),null);assert.equal(await p.locator('#dialog').evaluate(el=>el.open),false)});
await browser.close();server.close();console.log(`${passed} passed; ${failed} failed (${process.env.BROWSER||'chromium'})`);process.exitCode=failed?1:0})().catch(e=>{console.error(e);process.exit(1)});
