import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002';
const payload={app:'Affiliate Intelligence Studio',mode:'real',data:{schemaVersion:2,products:[],stories:[],plans:[],posts:[],experiments:[]}};
test('real PostgreSQL RLS, optimistic revisions and private quotas',async()=>{const db=new PGlite();try{await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);insert into auth.users values('${a}'),('${b}');create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);await db.exec(await readFile(new URL('../db/schema.sql',import.meta.url),'utf8'));
 await db.exec(`set role anon`);await assert.rejects(db.query('select * from public.sp_affiliate_workspaces'));
 await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${a}',false)`);const save=(rev)=>db.query('select public.sp_affiliate_save_workspace($1,$2::jsonb) as result',[rev,JSON.stringify(payload)]);assert.equal((await save(0)).rows[0].result.revision,1);await assert.rejects(save(0),/CLOUD_CONFLICT/);assert.equal((await save(1)).rows[0].result.revision,2);await assert.rejects(save(1),/CLOUD_CONFLICT/);
 await db.exec(`select set_config('request.jwt.claim.sub','${b}',false)`);assert.equal((await db.query('select * from public.sp_affiliate_workspaces')).rows.length,0);await assert.rejects(db.query('insert into public.sp_affiliate_workspaces(owner_id,payload) values($1,$2)',[a,payload]),/row-level security/);await assert.rejects(db.query('select public.sp_affiliate_consume_limit($1,$2)',[b,'ai']),/permission denied/);
 await db.exec('reset role;set role service_role');for(let i=0;i<10;i++)assert.equal((await db.query('select public.sp_affiliate_consume_limit($1,$2) as allowed',[a,'ai'])).rows[0].allowed,true);assert.equal((await db.query('select public.sp_affiliate_consume_limit($1,$2) as allowed',[a,'ai'])).rows[0].allowed,false);assert.equal((await db.query("select requests from public.sp_affiliate_usage where bucket='global' and kind='ai'")).rows[0].requests,10);for(let i=0;i<100;i++)assert.equal((await db.query('select public.sp_affiliate_consume_limit($1,$2) as allowed',[a,'ai'])).rows[0].allowed,false);assert.equal((await db.query('select public.sp_affiliate_consume_limit($1,$2) as allowed',[b,'ai'])).rows[0].allowed,true);
}finally{await db.close()}});
