const {chromium,webkit}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const http=require('node:http');
const root=path.resolve(__dirname,'..');
(async()=>{const server=http.createServer((req,res)=>{res.setHeader('content-type','text/html;charset=utf-8');res.end(fs.readFileSync(path.join(root,req.url.includes('legacy')?'tests/legacy-v2.html':'index.html')))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const engine=process.env.BROWSER==='webkit'?webkit:chromium;const browser=await engine.launch({headless:true,...(engine===chromium?{...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']}: {})});let passed=0,failed=0;
async function test(name,fn){if(process.env.TEST_FILTER&&!name.includes(process.env.TEST_FILTER))return;const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage();p.setDefaultTimeout(5000);const errors=[];p.on('pageerror',e=>errors.push(e.message));try{await p.goto(url+'/?legacy');await p.waitForSelector('#nav button');const legacyData=await p.evaluate(async()=>{state=demoData();mode='real';await persist();return state});await p.goto(url);await p.waitForSelector('#nav button');await fn(p,legacyData);assert.deepEqual(errors,[]);console.log('PASS',name);passed++}catch(e){console.error('FAIL',name,e.stack);failed++;fs.mkdirSync(path.join(root,'test-results'),{recursive:true});await p.screenshot({path:path.join(root,'test-results',name.replace(/\W/g,'-')+'.png'),fullPage:true}).catch(()=>{})}finally{await context.close()}}
await test('v2 database and JSON remain compatible',async (p,legacyData)=>{assert.deepEqual(await p.evaluate(()=>state),legacyData);assert.equal(await p.evaluate(()=>state.products.length),3);assert.equal(await p.evaluate(()=>state.schemaVersion),2);assert.equal(await p.evaluate(()=>validateImport({app:'Affiliate Intelligence Studio',mode:'real',data:state}).stories.length),1)});
await test('product draft and step survive refresh and UI language',async p=>{await p.locator('[data-action="new-product"]').first().click();await p.locator('#title').fill('Draft survives reload');await p.locator('#affiliate').fill('https://s.shopee.co.th/example');await p.locator('#variant').fill('Black');await p.locator('[data-action="product-step"][data-step="1"]').click();await p.waitForFunction(()=>document.querySelector('#save-status').dataset.state==='saved');await p.reload();await p.waitForSelector('#title',{state:'attached'});assert.equal(await p.locator('#title').inputValue(),'Draft survives reload');assert.equal(await p.evaluate(()=>productStep),1);await p.locator('#lang').click();assert.equal(await p.locator('#title').inputValue(),'Draft survives reload');});
await test('search filters and browser Back work',async p=>{await p.locator('#nav [data-page="products"]').click();await p.locator('#productSearch').fill('USB');await p.waitForTimeout(300);assert.equal(await p.locator('.product-title').count(),1);await p.locator('#productSearch').fill('does not exist');await p.waitForTimeout(300);assert.equal(await p.locator('.product-title').count(),0);assert.ok(await p.locator('#no-products').isVisible());await p.locator('[data-page="planner"]').first().click();await p.goBack();await p.waitForFunction(()=>page==='products');assert.equal(await p.locator('#productSearch').inputValue(),'does not exist')});
await test('story autosave undo redo and revision restore',async p=>{await p.locator('[data-page="studio"]').first().click();await p.locator('[data-action="open-story"]').first().click();await p.locator('[data-action="studio-tab"][data-tab="script"]').click();const before=await p.locator('#storyHookA').inputValue();await p.locator('#storyHookA').fill('New hook from creator');await p.waitForFunction(()=>document.querySelector('#save-status').dataset.state==='saved');await p.locator('[data-action="undo-story"]').click();assert.equal(await p.locator('#storyHookA').inputValue(),before);await p.locator('[data-action="redo-story"]').click();assert.equal(await p.locator('#storyHookA').inputValue(),'New hook from creator');await p.reload();await p.waitForSelector('#storyHookA');assert.equal(await p.locator('#storyHookA').inputValue(),'New hook from creator');await p.locator('[data-action="save-story"]').first().click();await p.waitForFunction(()=>state.stories[0].revisions.length===2);await p.locator('[data-action="studio-tab"][data-tab="history"]').click();await p.locator('[data-action="restore-revision"]').last().click();await p.locator('[data-action="confirm-restore-revision"]').click();await p.locator('[data-action="studio-tab"][data-tab="script"]').click();assert.equal(await p.locator('#storyHookA').inputValue(),before);assert.equal(await p.evaluate(()=>storyDraft.ready),false)});
await test('scene cards and teleprompter preserve text',async p=>{await p.locator('[data-page="studio"]').first().click();await p.locator('[data-action="open-story"]').first().click();await p.locator('[data-action="studio-tab"][data-tab="scenes"]').click();assert.equal(await p.locator('.scene-card').count(),5);await p.locator('#voice1').fill('Scene text for rehearsal');await p.locator('[data-action="teleprompter"]').click();assert.ok((await p.locator('#prompt-text').innerText()).includes('Scene text for rehearsal'));await p.locator('[data-action="prompt-toggle"]').click();await p.waitForFunction(()=>document.querySelector('#prompt-clock').textContent!=='00:00');assert.notEqual(await p.locator('#prompt-clock').innerText(),'00:00');await p.locator('[data-action="close-modal"]').click()});
await test('mobile layouts and translation do not overflow',async p=>{for(const width of [393,768,1440]){await p.setViewportSize({width,height:900});for(const route of ['today','analyze','products','studio','planner','results','lab','settings']){await p.evaluate(r=>navigateTo(r),route);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route+' @ '+width)}}});

await test('existing product drafts survive refresh and stay with their product',async p=>{
 const ids=await p.evaluate(()=>state.products.map(p=>p.id));
 await p.evaluate(id=>navigateTo('analyze',id),ids[1]);await p.locator('#title').fill('Product B pending edit');
 await p.reload();await p.waitForSelector('#title');assert.equal(await p.locator('#title').inputValue(),'Product B pending edit');
 await p.evaluate(()=>navigateTo('studio',state.stories[0].id));await p.evaluate(()=>navigateTo('analyze'));
 assert.equal(await p.evaluate(()=>selected),ids[1]);assert.equal(await p.locator('#title').inputValue(),'Product B pending edit');
 await p.evaluate(id=>navigateTo('analyze',id),ids[2]);await p.locator('#title').fill('Product C pending edit');
 await p.evaluate(id=>navigateTo('analyze',id),ids[1]);assert.equal(await p.locator('#title').inputValue(),'Product B pending edit');
 await p.evaluate(id=>navigateTo('analyze',id),ids[2]);assert.equal(await p.locator('#title').inputValue(),'Product C pending edit');
});
await test('real and demo drafts remain isolated',async p=>{
 await p.locator('[data-action="new-product"]').first().click();await p.locator('#title').fill('Real draft');await p.locator('#demo').click();
 await p.waitForFunction(()=>mode==='demo'&&state.products.length===3);await p.locator('[data-action="new-product"]').first().click();await p.locator('#title').fill('Demo draft');
 await p.locator('#demo').click();await p.waitForFunction(()=>mode==='real'&&page==='analyze');assert.equal(await p.locator('#title').inputValue(),'Real draft');
 await p.reload();await p.waitForSelector('#title');assert.equal(await p.locator('#title').inputValue(),'Real draft');
});
await test('business save failure is not hidden by successful autosave',async p=>{
 await p.evaluate(async()=>{const original=writeRecord;writeRecord=(key,value)=>key==='real'?Promise.reject(Error('injected quota failure')):original(key,value);state.profile.audience='unsaved business data';await persist().catch(()=>{});await flushSession()});
 assert.equal(await p.locator('#save-status').getAttribute('data-state'),'error');assert.equal(await p.evaluate(()=>saveFailure),true);
 assert.equal(await p.evaluate(()=>backupPayload().data.profile.audience),'unsaved business data');
});
await test('JSON import supports old records and recovered new drafts',async p=>{
 const ids=await p.evaluate(()=>state.products.map(p=>p.id));await p.evaluate(id=>navigateTo('analyze',id),ids[1]);await p.locator('#title').fill('Backup product B');await p.evaluate(id=>navigateTo('analyze',id),ids[2]);await p.locator('#title').fill('Backup product C');
 await p.evaluate(()=>navigateTo('studio',state.stories[0].id));await p.locator('#storyHookA').fill('Roundtrip hook');await p.locator('[data-action="save-story"]').first().click();
 await p.waitForFunction(()=>state.stories[0].revisions.length===2);await p.locator('#storyHookA').fill('Unsaved story in backup');
 const payload=await p.evaluate(()=>backupPayload());
 await p.evaluate(()=>navigateTo('settings'));await p.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});
 await p.locator('[data-action="import-replace"]').click();await p.locator('[data-action="confirm-import"]').click();await p.waitForFunction(()=>storyDraft?.hookA==='Unsaved story in backup');
 await p.reload();await p.waitForFunction(()=>storyDraft?.hookA==='Unsaved story in backup');assert.equal(await p.evaluate(()=>state.stories[0].hookA),'Roundtrip hook');await p.evaluate(id=>navigateTo('analyze',id),ids[1]);assert.equal(await p.locator('#title').inputValue(),'Backup product B');await p.evaluate(id=>navigateTo('analyze',id),ids[2]);assert.equal(await p.locator('#title').inputValue(),'Backup product C');
 await p.evaluate(()=>navigateTo('settings'));delete payload.editingSession;for(const story of payload.data.stories)for(const r of story.revisions)delete r.snapshot;
 await p.locator('#import-file').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});await p.locator('[data-action="import-merge"]').click();await p.waitForFunction(()=>pendingImport===null);assert.equal(await p.evaluate(()=>state.products.length),3);
});
await test('wizard validation focuses the required hidden step',async p=>{
 await p.locator('[data-action="new-product"]').first().click();await p.locator('[data-action="product-step"][data-step="3"]').click();await p.locator('#product-submit').click();
 assert.equal(await p.evaluate(()=>productStep),0);assert.equal(await p.locator('#affiliate').getAttribute('aria-invalid'),'true');
});

await test('backup merge keeps product draft ownership',async p=>{
 const ids=await p.evaluate(()=>state.products.map(p=>p.id));await p.evaluate(id=>navigateTo('analyze',id),ids[1]);await p.locator('#title').fill('Imported draft B');const payload=await p.evaluate(()=>backupPayload());
 await p.evaluate(async()=>{resetSession();page='today';render();await flushSession()});await p.evaluate(id=>navigateTo('analyze',id),ids[2]);await p.locator('#title').fill('Current draft C');
 await p.evaluate(()=>navigateTo('settings'));await p.locator('#import-file').setInputFiles({name:'merge.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});await p.locator('[data-action="import-merge"]').click();await p.waitForFunction(()=>pendingImport===null);
 await p.evaluate(()=>navigateTo('analyze'));assert.equal(await p.evaluate(()=>selected),ids[2]);assert.equal(await p.locator('#title').inputValue(),'Current draft C');await p.evaluate(id=>navigateTo('analyze',id),ids[1]);assert.equal(await p.locator('#title').inputValue(),'Imported draft B');
});
await test('merge recovers new product into an empty editor',async p=>{
 await p.locator('[data-action="new-product"]').first().click();await p.locator('#title').fill('Imported new draft');const payload=await p.evaluate(()=>backupPayload());await p.evaluate(async()=>{resetSession();page='settings';render();await flushSession()});
 await p.locator('#import-file').setInputFiles({name:'new-draft.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});await p.locator('[data-action="import-merge"]').click();await p.waitForFunction(()=>pendingImport===null);await p.evaluate(()=>navigateTo('analyze'));assert.equal(await p.locator('#title').inputValue(),'Imported new draft');await p.reload();await p.waitForSelector('#title');assert.equal(await p.locator('#title').inputValue(),'Imported new draft');
});
await test('structured revisions restore scenes and remain unready',async p=>{
 await p.evaluate(()=>navigateTo('studio',state.stories[0].id));await p.locator('#storyHookA').fill('Version checkpoint');await p.locator('[data-action="save-story"]').first().click();await p.waitForFunction(()=>state.stories[0].revisions.length===2);
 await p.locator('#storyHookA').fill('Later hook');await p.locator('[data-action="studio-tab"][data-tab="history"]').click();await p.locator('[data-action="restore-revision"]').first().click();await p.locator('[data-action="confirm-restore-revision"]').click();
 assert.equal(await p.evaluate(()=>storyDraft.hookA),'Version checkpoint');assert.equal(await p.evaluate(()=>storyDraft.shots[0].voice),'Version checkpoint');assert.equal(await p.evaluate(()=>storyDraft.ready),false);assert.equal(await p.evaluate(()=>storyDraft.revisions.length),3);
});
await test('standalone file works offline and recovers a draft',async p=>{
 await p.goto(require('node:url').pathToFileURL(path.join(root,'index.html')).href);await p.waitForSelector('#nav button');await p.evaluate(()=>navigateTo('analyze'));await p.locator('#title').fill('File mode draft');await p.waitForFunction(()=>document.querySelector('#save-status').dataset.state==='saved');await p.reload();await p.waitForSelector('#title');assert.equal(await p.locator('#title').inputValue(),'File mode draft');
});
await browser.close();server.close();console.log(`${passed} passed; ${failed} failed`);process.exitCode=failed?1:0})().catch(e=>{console.error(e);process.exit(1)});
