import {build} from 'esbuild';
import {readFile, writeFile} from 'node:fs/promises';
const files=['cloud-config','translations','icons','core','dashboard','products','stories','planner','results','lab','settings','transfer','demo','workspace','product-workflow','studio-tools','cloud','integrations','storefront','controller'];
const css=(await Promise.all(['styles','premium','commerce','lighting'].map(n=>readFile(new URL('../src/'+n+'.css',import.meta.url),'utf8')))).join('\n');
const sdk=await build({entryPoints:[new URL('../src/auth-sdk.js',import.meta.url).pathname],bundle:true,write:false,minify:true,format:'iife',platform:'browser',target:['es2020'],legalComments:'inline'});
const js=sdk.outputFiles[0].text+'\n'+(await Promise.all(files.map(n=>readFile(new URL('../src/'+n+'.js',import.meta.url),'utf8')))).join('\n');
const shell=await readFile(new URL('../src/shell.html',import.meta.url),'utf8');
const assets=Object.fromEntries(await Promise.all(['hero','empty'].map(async name=>[name,'data:image/webp;base64,'+(await readFile(new URL('../assets/emerald-'+name+'.webp',import.meta.url))).toString('base64')])));
const source=js.replaceAll('/*__HERO_ASSET__*/',assets.hero).replaceAll('/*__EMPTY_ASSET__*/',assets.empty);
const out=shell.replace('/*__STYLES__*/',()=>css).replace('/*__SCRIPTS__*/',()=>source);
await writeFile(new URL('../index.html',import.meta.url),out);
console.log('Built index.html ('+Buffer.byteLength(out)+' bytes)');
