// Cloud identity never replaces the original guest v2 IndexedDB keys.
let cloudClient=null,cloudUser=null,cloudChanging=false,cloudBusy=false,cloudMeta={revision:0,auto:false},cloudMessage='',cloudTimer,cloudSwitchQueue=Promise.resolve(),cloudConflict=null,cloudEpoch=0;
function workspaceKey(workspace=mode){return cloudUser?'account:'+cloudUser.id+':'+workspace:workspace;}
function cloudLabel(){return cloudUser?T('บัญชี','Account')+': '+cloudUser.email:T('บัญชีและซิงก์','Account & sync');}
function cloudError(error){const code=error?.message||String(error);if(code.includes('CLOUD_CONFLICT'))return T('ข้อมูลบนคลาวด์เปลี่ยนจากอีกเครื่อง ร่างในเครื่องยังอยู่ กรุณาดูข้อมูลคลาวด์ก่อนเลือกอีกครั้ง','Cloud changed on another device. Local drafts are safe. Review the cloud copy before continuing.');if(code.includes('Failed to fetch')||!navigator.onLine)return T('ออฟไลน์หรือเชื่อมต่อไม่ได้ ข้อมูลยังบันทึกในเครื่อง','Offline or connection unavailable. Your work remains on this device.');return T('ทำรายการไม่สำเร็จ: ','Request failed: ')+code;}
function cloudNote(message){cloudMessage=message;const box=$('#cloud-message');if(box)box.textContent=message;}
let cloudReady=false,cloudAuthEvent=null,cloudRecoveryRequested=false;
async function processCloudAuth(){if(!cloudReady||!cloudAuthEvent)return;const {session}=cloudAuthEvent;cloudAuthEvent=null;if(session?.user?.id!==cloudUser?.id)await switchCloudUser(session?.user||null);if(cloudRecoveryRequested){cloudRecoveryRequested=false;openRecoveryForm()}}
async function initCloud(){if(!CLOUD_CONFIG.url||!CLOUD_CONFIG.publishableKey||!globalThis.SPAffiliateAuth)return;cloudClient=SPAffiliateAuth.createClient(CLOUD_CONFIG.url,CLOUD_CONFIG.publishableKey,{auth:{storageKey:'sp-affiliate-auth-v1',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'},global:{fetch:(url,options={})=>fetch(url,{...options,signal:options.signal||AbortSignal.timeout(12000)})}});cloudClient.auth.onAuthStateChange((event,session)=>{cloudAuthEvent={event,session};if(event==='PASSWORD_RECOVERY')cloudRecoveryRequested=true;setTimeout(()=>processCloudAuth().catch(e=>cloudNote(cloudError(e))),0)});try{const result=await Promise.race([cloudClient.auth.getSession(),new Promise(r=>setTimeout(()=>r(null),1800))]);cloudUser=result?.data?.session?.user||null}catch{}}
async function loadCloudMeta(){cloudMeta=await readRecord('cloud-meta:'+workspaceKey('real'))||{revision:0,auto:false};}
function setCloudChanging(value){if(value){cloudEpoch++;pendingCloud=null;pendingOnline=null;$('#dialog').close()}cloudChanging=value;$('#main').inert=value;$('#nav').inert=value;$('#demo').disabled=value;}
function switchCloudUser(user){const run=cloudSwitchQueue.catch(()=>{}).then(async()=>{if(user?.id===cloudUser?.id)return;clearTimeout(cloudTimer);setCloudChanging(true);try{await flushSession();await persist();cloudUser=user;mode='real';cloudConflict=null;cloudMessage='';resetSession();await load();await loadSession();await loadCloudMeta();page='settings';onlineStatus={shopee:'unknown',ai:'unknown'};pendingOnline=null;pendingCloud=null;render();syncRoute(true)}finally{setCloudChanging(false)}});cloudSwitchQueue=run;return run;}
function cloudAccountHTML(){return `<section class="card mb cloud-panel"><div class="section-title"><div><div class="eyebrow">CLOUD WORKSPACE</div><h2>${T('บัญชีและซิงก์ข้ามเครื่อง','Account & cross-device sync')}</h2></div>${badge(cloudUser?T('บัญชีของคุณ','Your account'):T('ข้อมูลในเครื่อง','Local workspace'),cloudUser?'cyan':'violet')}</div><p class="sub">${T('ข้อมูลเดิมในเครื่องยังอยู่แยกต่างหาก บัญชีแต่ละคนมีพื้นที่ของตัวเอง โหมดตัวอย่างไม่ส่งขึ้นคลาวด์','Your original local records stay separate. Each account has its own workspace. Demo data is never uploaded.')}</p>${!cloudClient?`<p class="notice">${T('ยังไม่ได้กำหนดค่าบริการบัญชี','Account service is not configured.')}</p>`:cloudUser?`<p><strong>${esc(cloudUser.email||'')}</strong></p><div class="actions">${btn(T('ส่งข้อมูลเครื่องนี้ขึ้นคลาวด์','Upload this workspace'),'cloud-upload','cyan')}${btn(T('ดูและรับข้อมูลจากคลาวด์','Review cloud copy'),'cloud-download','ghost')}${btn(T('คัดลอกข้อมูลเดิมในเครื่องเข้าบัญชี','Copy original local records'),'cloud-copy-guest','ghost')}${btn(T('ออกจากระบบ','Sign out'),'cloud-signout','ghost')}</div><label class="check mt"><input id="cloud-auto" type="checkbox" ${cloudMeta.auto?'checked':''} ${cloudMeta.revision?'':'disabled'}>${T('ส่งขึ้นคลาวด์อัตโนมัติหลังบันทึก (เปิดได้หลังซิงก์ครั้งแรก)','Automatically upload after saving (available after first sync)')}</label><p class="sub">${T('เวอร์ชันที่เครื่องนี้รู้จัก','Known cloud revision')}: ${cloudMeta.revision||0} · ${T('ข้อมูลที่แก้พร้อมกันจะหยุดให้เลือก ไม่เขียนทับอัตโนมัติ','Concurrent edits stop for review instead of overwriting.')}</p>`:`<form id="cloud-login-form" data-private><div class="formgrid">${field('cloud-email',T('อีเมล','Email'),'','email','required autocomplete="email"')}${field('cloud-password',T('รหัสผ่าน','Password'),'','password','required autocomplete="current-password"')}</div><div class="actions"><button type="submit" class="primary">${T('เข้าสู่ระบบ','Sign in')}</button>${btn(T('สมัครบัญชี','Create account'),'cloud-signup','cyan')}${btn(T('ลืมรหัสผ่าน','Forgot password'),'cloud-reset','ghost')}</div><p class="sub">${T('บัญชีใหม่ต้องยืนยันอีเมล รหัสผ่านไม่ถูกเก็บในร่างหรือไฟล์สำรอง','New accounts require email verification. Passwords are excluded from drafts and backups.')}</p></form>`}<p id="cloud-message" class="notice info mt" role="status">${esc(cloudMessage||T('ร่างบันทึกในเครื่องเสมอ ซิงก์ครั้งแรกเมื่อคุณเลือก','Drafts always save locally. First sync happens when you choose.'))}</p></section>`;}
function scheduleCloudUpload(){clearTimeout(cloudTimer);if(cloudUser&&cloudMeta.auto&&mode==='real'&&!cloudChanging&&!cloudBusy&&!cloudConflict)cloudTimer=setTimeout(()=>cloudUpload().catch(e=>cloudNote(cloudError(e))),2000);}
function cloudContext(){return {owner:cloudUser?.id,scope:workspaceKey(),epoch:cloudEpoch};}
function assertCloudContext(context){if(!context||cloudChanging||mode!=='real'||context.owner!==cloudUser?.id||context.scope!==workspaceKey()||context.epoch!==cloudEpoch)throw Error(T('บัญชีหรือพื้นที่ทำงานเปลี่ยนแล้ว กรุณาทำรายการใหม่','Account or workspace changed. Try again.'));}
async function requireCloud(){if(!cloudClient||!cloudUser||mode!=='real')throw Error(T('เข้าสู่ระบบและใช้โหมดข้อมูลจริงก่อน','Sign in and switch to your real workspace first.'));const context=cloudContext();const {data,error}=await cloudClient.auth.getUser();assertCloudContext(context);if(error||data.user?.id!==context.owner)throw Error(T('เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง','Session expired. Sign in again.'));return context.owner;}
async function cloudUpload(){if(cloudBusy||cloudChanging)return;cloudBusy=true;const scope=workspaceKey(),context=cloudContext();let uploadedVersion=sessionVersion;try{const owner=await requireCloud();await flushSession();assertCloudContext(context);const payload=backupPayload();validateImport(payload);validateRecovery(payload.editingSession,payload.data);const snapshot=structuredClone(payload);uploadedVersion=sessionVersion;cloudNote(T('กำลังส่งขึ้นคลาวด์…','Uploading…'));const {data,error}=await cloudClient.rpc('sp_affiliate_save_workspace',{p_expected_revision:cloudMeta.revision||0,p_payload:snapshot});assertCloudContext(context);if(error){if(error.message?.includes('CLOUD_CONFLICT'))cloudConflict=true;throw error}if(scope!==workspaceKey()||cloudUser?.id!==owner)return;cloudMeta={...cloudMeta,revision:data.revision};await writeRecord('cloud-meta:'+scope,cloudMeta);cloudNote(T('ซิงก์สำเร็จ เวอร์ชัน ','Synced revision ')+data.revision);if($('#cloud-auto'))$('#cloud-auto').disabled=false;}finally{cloudBusy=false;if(scope===workspaceKey()&&uploadedVersion!==sessionVersion)scheduleCloudUpload();}}
async function fetchCloud(){const context=cloudContext();const owner=await requireCloud();const {data,error}=await cloudClient.from('sp_affiliate_workspaces').select('revision,payload,updated_at').eq('owner_id',owner).maybeSingle();assertCloudContext(context);if(error)throw error;if(!data)throw Error(T('ยังไม่มีข้อมูลบนคลาวด์ ใช้ส่งขึ้นคลาวด์ครั้งแรก','No cloud copy yet. Upload this workspace first.'));const valid=validateImport(data.payload),recovery=validateRecovery(data.payload.editingSession,valid);return {...data,payload:{...data.payload,data:valid,editingSession:recovery},owner,context};}
let pendingCloud=null;
async function previewCloud(){const result=await fetchCloud();assertCloudContext(result.context);pendingCloud=result;modal(T('ตรวจข้อมูลคลาวด์ก่อนรับลงเครื่อง','Review cloud data before downloading'),`<p>${T('เวอร์ชัน','Revision')} ${pendingCloud.revision} · ${pendingCloud.payload.data.products.length} ${T('สินค้า','products')} · ${pendingCloud.payload.data.stories.length} ${T('บท','stories')}</p><p>${T('การรับลงเครื่องจะแทนที่พื้นที่บัญชีนี้ และเก็บสำเนาปัจจุบันในเครื่องให้กู้กลับได้ ข้อมูลผู้ใช้ทั่วไปเดิมไม่ถูกเปลี่ยน','Downloading replaces this account workspace and retains a local recovery copy. Original guest records are unchanged.')}</p><div class="actions">${btn(T('ดาวน์โหลด JSON คลาวด์','Download cloud JSON'),'cloud-export-remote','ghost')}</div>`,btn(T('สำรองแล้วรับข้อมูลคลาวด์','Back up & download'),'cloud-confirm-download','primary'));}
async function writeCloudBatch(entries){const frozen=structuredClone(entries);const job=saveQueue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{const tx=db.transaction('workspaces','readwrite');for(const [key,value]of frozen)tx.objectStore('workspaces').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Transaction aborted'))}));saveQueue=job;await job;}
function applyCloudCopy(copy){const run=cloudSwitchQueue.catch(()=>{}).then(()=>applyCloudCopyNow(copy));cloudSwitchQueue=run;return run;}
async function applyCloudCopyNow(copy){assertCloudContext(copy.context);if(copy.owner!==cloudUser?.id||mode!=='real')throw Error('Account changed');setCloudChanging(true);clearTimeout(cloudTimer);try{await flushSession();const scope=workspaceKey(),previous=backupPayload();const session=copy.payload.editingSession||{version:1,drafts:{},sessionStories:{},page:'settings'};const meta={revision:copy.revision,auto:false};await writeCloudBatch([[scope,copy.payload.data],['session:'+scope,session],['cloud-backup:'+scope,previous],['cloud-meta:'+scope,meta]]);try{localStorage.removeItem(journalKey())}catch{}await load();await loadSession();cloudMeta=meta;cloudConflict=null;page='settings';render();syncRoute(true);cloudNote(T('รับข้อมูลแล้ว สำเนาก่อนรับเก็บไว้ในเครื่อง','Downloaded. The previous copy is retained on this device.'));}finally{setCloudChanging(false)}}
function openRecoveryForm(){modal(T('ตั้งรหัสผ่านใหม่','Set a new password'),`<form id="cloud-recovery-form" data-private>${field('cloud-new-password',T('รหัสผ่านใหม่อย่างน้อย 10 ตัว','New password, at least 10 characters'),'','password','required minlength="10" autocomplete="new-password"')}<button type="submit" class="primary mt">${T('บันทึกรหัสผ่าน','Save password')}</button></form>`);}
function authRedirect(){return location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'?location.origin+location.pathname:undefined;}
async function handleCloudAction(action){if(!cloudClient)throw Error('Cloud is not configured');if(action==='cloud-signup'){const email=$('#cloud-email').value,password=$('#cloud-password').value;if(!$('#cloud-login-form').reportValidity())return;if(password.length<10)throw Error(T('รหัสผ่านใหม่ต้องมีอย่างน้อย 10 ตัว','New passwords need at least 10 characters.'));const {error}=await cloudClient.auth.signUp({email,password,options:{emailRedirectTo:authRedirect()}});if(error)throw error;$('#cloud-password').value='';cloudNote(T('ตรวจอีเมลเพื่อยืนยันบัญชี หากไม่ได้รับ ให้ตรวจการตั้งค่าอีเมลของบริการ','Check your email to verify your account. If no email arrives, check the service email configuration.'));}if(action==='cloud-reset'){const email=$('#cloud-email').value;if(!$('#cloud-email').reportValidity())return;const {error}=await cloudClient.auth.resetPasswordForEmail(email,{redirectTo:authRedirect()});if(error)throw error;cloudNote(T('หากมีบัญชีที่ใช้อีเมลนี้ ระบบจะส่งลิงก์ตั้งรหัสผ่านใหม่','If this email has an account, a password-reset link will be sent.'));}if(action==='cloud-signout'){await flushSession();await persist();const {error}=await cloudClient.auth.signOut({scope:'local'});if(error)throw error;await switchCloudUser(null);}if(action==='cloud-upload')await cloudUpload();if(action==='cloud-download')await previewCloud();if(action==='cloud-export-remote'&&pendingCloud){assertCloudContext(pendingCloud.context);download('Affiliate-cloud.json',JSON.stringify(pendingCloud.payload,null,2),'application/json');}if(action==='cloud-confirm-download'&&pendingCloud){await applyCloudCopy(pendingCloud);pendingCloud=null;$('#dialog').close();}if(action==='cloud-copy-guest'){await requireCloud();modal(T('คัดลอกข้อมูลเดิมเข้าพื้นที่บัญชี','Copy original records into this account'),`<p>${T('จะรวมข้อมูลสินค้า บท และผลจากพื้นที่ผู้ใช้ทั่วไปในเครื่องนี้ โดยไม่ลบต้นฉบับ ID ซ้ำจะเก็บข้อมูลบัญชีปัจจุบัน','Merge products, stories and results from this device’s guest workspace. Original records are retained; duplicate IDs keep the current account version.')}</p>`,btn(T('คัดลอกข้อมูล','Copy records'),'cloud-confirm-guest','primary'));}if(action==='cloud-confirm-guest')await copyGuestToAccount();if(action==='cloud-export-recovery'){const context=cloudContext();const saved=await readRecord('cloud-backup:'+workspaceKey());assertCloudContext(context);if(!saved)throw Error(T('ยังไม่มีสำเนาก่อนซิงก์','No pre-sync recovery copy yet.'));download('Affiliate-before-sync.json',JSON.stringify(saved,null,2),'application/json');}}
async function handleCloudSubmit(form){if(!form.reportValidity())return;const button=form.querySelector('button');button.disabled=true;try{if(form.id==='cloud-login-form'){const {data,error}=await cloudClient.auth.signInWithPassword({email:$('#cloud-email').value,password:$('#cloud-password').value});if(error)throw error;await switchCloudUser(data.user);}else{const {error}=await cloudClient.auth.updateUser({password:$('#cloud-new-password').value});if(error)throw error;$('#dialog').close();toast(T('เปลี่ยนรหัสผ่านแล้ว','Password updated.'));}}finally{button.disabled=false}}
window.addEventListener('online',()=>scheduleCloudUpload());

function switchWorkspaceMode(){const run=cloudSwitchQueue.catch(()=>{}).then(async()=>{setCloudChanging(true);clearTimeout(cloudTimer);try{await flushSession();await persist();mode=mode==='real'?'demo':'real';try{localStorage.setItem('aff-mode',mode)}catch{}await load();if(mode==='demo'&&!state.products.length){state=demoData();await persist()}page='today';await loadSession();await loadCloudMeta();render();syncRoute(true)}finally{setCloudChanging(false)}});cloudSwitchQueue=run;return run;}

function copyGuestToAccount(){const context=cloudContext();const run=cloudSwitchQueue.catch(()=>{}).then(async()=>{await requireCloud();assertCloudContext(context);setCloudChanging(true);try{await flushSession();const guest=await readRecord('real');if(guest){const next=structuredClone(state);for(const key of ['products','stories','plans','posts','experiments','hooks']){const ids=new Set((next[key]||[]).map(x=>x.id));next[key]=[...(next[key]||[]),...(guest[key]||[]).filter(x=>!ids.has(x.id))]}validateImport({app:'Affiliate Intelligence Studio',mode:'real',data:next});await writeCloudBatch([['cloud-backup:'+workspaceKey(),backupPayload()],[workspaceKey(),next]]);state=next;render();queueSession();}}finally{setCloudChanging(false)}});cloudSwitchQueue=run;return run;}
