// Cloud identity never replaces the original guest v2 IndexedDB keys.
let cloudClient=null,cloudUser=null,cloudChanging=false,cloudBusy=false,cloudMeta={revision:0,auto:false},cloudMessage='',cloudTimer,cloudSwitchQueue=Promise.resolve(),cloudConflict=null,cloudEpoch=0;
function workspaceKey(workspace=mode){return cloudUser?'account:'+cloudUser.id+':'+workspace:workspace;}
function cloudLabel(){return cloudUser?uiText('account')+': '+cloudUser.email:uiText('account_sync');}
function cloudError(error){const code=error?.message||String(error);if(code.includes('CLOUD_CONFLICT'))return uiText('cloud_changed_on_another_device_local_drafts_are_safe_r');if(code.includes('Failed to fetch')||!navigator.onLine)return uiText('offline_or_connection_unavailable_your_work_remains_on_');return uiText('request_failed')+code;}
function cloudNote(message){cloudMessage=message;const box=$('#cloud-message');if(box)box.textContent=message;}
let cloudReady=false,cloudAuthEvent=null,cloudRecoveryRequested=false;
async function processCloudAuth(){if(!cloudReady||!cloudAuthEvent)return;const {session}=cloudAuthEvent;cloudAuthEvent=null;if(session?.user?.id!==cloudUser?.id)await switchCloudUser(session?.user||null);if(cloudRecoveryRequested){cloudRecoveryRequested=false;openRecoveryForm()}}
async function initCloud(){if(!CLOUD_CONFIG.url||!CLOUD_CONFIG.publishableKey||!globalThis.SPAffiliateAuth)return;cloudClient=SPAffiliateAuth.createClient(CLOUD_CONFIG.url,CLOUD_CONFIG.publishableKey,{auth:{storageKey:'sp-affiliate-auth-v1',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'},global:{fetch:(url,options={})=>fetch(url,{...options,signal:options.signal||AbortSignal.timeout(12000)})}});cloudClient.auth.onAuthStateChange((event,session)=>{cloudAuthEvent={event,session};if(event==='PASSWORD_RECOVERY')cloudRecoveryRequested=true;setTimeout(()=>processCloudAuth().catch(e=>cloudNote(cloudError(e))),0)});try{const result=await Promise.race([cloudClient.auth.getSession(),new Promise(r=>setTimeout(()=>r(null),1800))]);cloudUser=result?.data?.session?.user||null}catch{}}
async function loadCloudMeta(){cloudMeta=await readRecord('cloud-meta:'+workspaceKey('real'))||{revision:0,auto:false};}
function setCloudChanging(value){if(value){cloudEpoch++;pendingCloud=null;pendingOnline=null;$('#dialog').close()}cloudChanging=value;$('#main').inert=value;$('#nav').inert=value;$('#demo').disabled=value;}
function switchCloudUser(user){const run=cloudSwitchQueue.catch(()=>{}).then(async()=>{if(user?.id===cloudUser?.id)return;clearTimeout(cloudTimer);setCloudChanging(true);try{await flushSession();await persist();cloudUser=user;mode='real';cloudConflict=null;cloudMessage='';resetSession();await load();await loadSession();await loadCloudMeta();page='settings';onlineStatus={shopee:'unknown',ai:'unknown'};pendingOnline=null;pendingCloud=null;render();syncRoute(true)}finally{setCloudChanging(false)}});cloudSwitchQueue=run;return run;}
function cloudAccountHTML(){return `<section class="card mb cloud-panel"><div class="section-title"><div><div class="eyebrow">${uiText('cloud_workspace')}</div><h2>${uiText('account_cross_device_sync')}</h2></div>${badge(cloudUser?uiText('your_account'):uiText('local_workspace'),cloudUser?'cyan':'violet')}</div><p class="sub">${uiText('your_original_local_records_stay_separate_each_account_')}</p>${!cloudClient?`<p class="notice">${uiText('account_service_is_not_configured')}</p>`:cloudUser?`<p><strong>${esc(cloudUser.email||'')}</strong></p><div class="actions">${btn(uiText('upload_this_workspace'),'cloud-upload','cyan')}${btn(uiText('review_cloud_copy'),'cloud-download','ghost')}${btn(uiText('copy_original_local_records'),'cloud-copy-guest','ghost')}${btn(uiText('sign_out'),'cloud-signout','ghost')}</div><label class="check mt"><input id="cloud-auto" type="checkbox" ${cloudMeta.auto?'checked':''} ${cloudMeta.revision?'':'disabled'}>${uiText('automatically_upload_after_saving_available_after_first')}</label><p class="sub">${uiText('known_cloud_revision')}: ${cloudMeta.revision||0} · ${uiText('concurrent_edits_stop_for_review_instead_of_overwriting')}</p>`:`<form id="cloud-login-form" data-private><div class="formgrid">${field('cloud-email',uiText('email'),'','email','required autocomplete="email"')}${field('cloud-password',uiText('password'),'','password','required autocomplete="current-password"')}</div><div class="actions"><button type="submit" class="primary">${uiText('sign_in')}</button>${btn(uiText('create_account'),'cloud-signup','cyan')}${btn(uiText('forgot_password'),'cloud-reset','ghost')}</div><p class="sub">${uiText('new_accounts_require_email_verification_passwords_are_e')}</p></form>`}<p id="cloud-message" class="notice info mt" role="status">${esc(cloudMessage||uiText('drafts_always_save_locally_first_sync_happens_when_you_'))}</p></section>`;}
function scheduleCloudUpload(){clearTimeout(cloudTimer);if(cloudUser&&cloudMeta.auto&&mode==='real'&&!cloudChanging&&!cloudBusy&&!cloudConflict)cloudTimer=setTimeout(()=>cloudUpload().catch(e=>cloudNote(cloudError(e))),2000);}
function cloudContext(){return {owner:cloudUser?.id,scope:workspaceKey(),epoch:cloudEpoch};}
function assertCloudContext(context){if(!context||cloudChanging||mode!=='real'||context.owner!==cloudUser?.id||context.scope!==workspaceKey()||context.epoch!==cloudEpoch)throw Error(uiText('account_or_workspace_changed_try_again'));}
async function requireCloud(){if(!cloudClient||!cloudUser||mode!=='real')throw Error(uiText('sign_in_and_switch_to_your_real_workspace_first'));const context=cloudContext();const {data,error}=await cloudClient.auth.getUser();assertCloudContext(context);if(error||data.user?.id!==context.owner)throw Error(uiText('session_expired_sign_in_again'));return context.owner;}
async function cloudUpload(){if(cloudBusy||cloudChanging)return;cloudBusy=true;const scope=workspaceKey(),context=cloudContext();let uploadedVersion=sessionVersion;try{const owner=await requireCloud();await flushSession();assertCloudContext(context);const payload=backupPayload();validateImport(payload);validateRecovery(payload.editingSession,payload.data);const snapshot=structuredClone(payload);uploadedVersion=sessionVersion;cloudNote(uiText('uploading'));const {data,error}=await cloudClient.rpc('sp_affiliate_save_workspace',{p_expected_revision:cloudMeta.revision||0,p_payload:snapshot});assertCloudContext(context);if(error){if(error.message?.includes('CLOUD_CONFLICT'))cloudConflict=true;throw error}if(scope!==workspaceKey()||cloudUser?.id!==owner)return;cloudMeta={...cloudMeta,revision:data.revision};await writeRecord('cloud-meta:'+scope,cloudMeta);cloudNote(uiText('synced_revision')+data.revision);if($('#cloud-auto'))$('#cloud-auto').disabled=false;}finally{cloudBusy=false;if(scope===workspaceKey()&&uploadedVersion!==sessionVersion)scheduleCloudUpload();}}
async function fetchCloud(){const context=cloudContext();const owner=await requireCloud();const {data,error}=await cloudClient.from('sp_affiliate_workspaces').select('revision,payload,updated_at').eq('owner_id',owner).maybeSingle();assertCloudContext(context);if(error)throw error;if(!data)throw Error(uiText('no_cloud_copy_yet_upload_this_workspace_first'));const valid=validateImport(data.payload),recovery=validateRecovery(data.payload.editingSession,valid);return {...data,payload:{...data.payload,data:valid,editingSession:recovery},owner,context};}
let pendingCloud=null;
async function previewCloud(){const result=await fetchCloud();assertCloudContext(result.context);pendingCloud=result;modal(uiText('review_cloud_data_before_downloading'),`<p>${uiText('revision')} ${pendingCloud.revision} · ${pendingCloud.payload.data.products.length} ${uiText('products')} · ${pendingCloud.payload.data.stories.length} ${uiText('stories')}</p><p>${uiText('downloading_replaces_this_account_workspace_and_retains')}</p><div class="actions">${btn(uiText('download_cloud_json'),'cloud-export-remote','ghost')}</div>`,btn(uiText('back_up_download'),'cloud-confirm-download','primary'));}
async function writeCloudBatch(entries){const frozen=structuredClone(entries);const job=saveQueue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{const tx=db.transaction('workspaces','readwrite');for(const [key,value]of frozen)tx.objectStore('workspaces').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Transaction aborted'))}));saveQueue=job;await job;}
function applyCloudCopy(copy){const run=cloudSwitchQueue.catch(()=>{}).then(()=>applyCloudCopyNow(copy));cloudSwitchQueue=run;return run;}
async function applyCloudCopyNow(copy){assertCloudContext(copy.context);if(copy.owner!==cloudUser?.id||mode!=='real')throw Error('Account changed');setCloudChanging(true);clearTimeout(cloudTimer);try{await flushSession();const scope=workspaceKey(),previous=backupPayload();const session=copy.payload.editingSession||{version:1,drafts:{},sessionStories:{},page:'settings'};const meta={revision:copy.revision,auto:false};await writeCloudBatch([[scope,copy.payload.data],['session:'+scope,session],['cloud-backup:'+scope,previous],['cloud-meta:'+scope,meta]]);try{localStorage.removeItem(journalKey())}catch{}await load();await loadSession();cloudMeta=meta;cloudConflict=null;page='settings';render();syncRoute(true);cloudNote(uiText('downloaded_the_previous_copy_is_retained_on_this_device'));}finally{setCloudChanging(false)}}
function openRecoveryForm(){modal(uiText('set_a_new_password'),`<form id="cloud-recovery-form" data-private>${field('cloud-new-password',uiText('new_password_at_least_10_characters'),'','password','required minlength="10" autocomplete="new-password"')}<button type="submit" class="primary mt">${uiText('save_password')}</button></form>`);}
function authRedirect(){return location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'?location.origin+location.pathname:undefined;}
async function handleCloudAction(action){if(!cloudClient)throw Error('Cloud is not configured');if(action==='cloud-signup'){const email=$('#cloud-email').value,password=$('#cloud-password').value;if(!$('#cloud-login-form').reportValidity())return;if(password.length<10)throw Error(uiText('new_passwords_need_at_least_10_characters'));const {error}=await cloudClient.auth.signUp({email,password,options:{emailRedirectTo:authRedirect()}});if(error)throw error;$('#cloud-password').value='';cloudNote(uiText('check_your_email_to_verify_your_account_if_no_email_arr'));}if(action==='cloud-reset'){const email=$('#cloud-email').value;if(!$('#cloud-email').reportValidity())return;const {error}=await cloudClient.auth.resetPasswordForEmail(email,{redirectTo:authRedirect()});if(error)throw error;cloudNote(uiText('if_this_email_has_an_account_a_password_reset_link_will'));}if(action==='cloud-signout'){await flushSession();await persist();const {error}=await cloudClient.auth.signOut({scope:'local'});if(error)throw error;await switchCloudUser(null);}if(action==='cloud-upload')await cloudUpload();if(action==='cloud-download')await previewCloud();if(action==='cloud-export-remote'&&pendingCloud){assertCloudContext(pendingCloud.context);download('Affiliate-cloud.json',JSON.stringify(pendingCloud.payload,null,2),'application/json');}if(action==='cloud-confirm-download'&&pendingCloud){await applyCloudCopy(pendingCloud);pendingCloud=null;$('#dialog').close();}if(action==='cloud-copy-guest'){await requireCloud();modal(uiText('copy_original_records_into_this_account'),`<p>${uiText('merge_products_stories_and_results_from_this_device_s_g')}</p>`,btn(uiText('copy_records'),'cloud-confirm-guest','primary'));}if(action==='cloud-confirm-guest')await copyGuestToAccount();if(action==='cloud-export-recovery'){const context=cloudContext();const saved=await readRecord('cloud-backup:'+workspaceKey());assertCloudContext(context);if(!saved)throw Error(uiText('no_pre_sync_recovery_copy_yet'));download('Affiliate-before-sync.json',JSON.stringify(saved,null,2),'application/json');}}
async function handleCloudSubmit(form){if(!form.reportValidity())return;const button=form.querySelector('button');button.disabled=true;try{if(form.id==='cloud-login-form'){const {data,error}=await cloudClient.auth.signInWithPassword({email:$('#cloud-email').value,password:$('#cloud-password').value});if(error)throw error;await switchCloudUser(data.user);}else{const {error}=await cloudClient.auth.updateUser({password:$('#cloud-new-password').value});if(error)throw error;$('#dialog').close();toast(uiText('password_updated'));}}finally{button.disabled=false}}
window.addEventListener('online',()=>scheduleCloudUpload());

function switchWorkspaceMode(){const run=cloudSwitchQueue.catch(()=>{}).then(async()=>{setCloudChanging(true);clearTimeout(cloudTimer);try{await flushSession();await persist();mode=mode==='real'?'demo':'real';try{localStorage.setItem('aff-mode',mode)}catch{}await load();if(mode==='demo'&&!state.products.length){state=demoData();await persist()}page='today';await loadSession();await loadCloudMeta();render();syncRoute(true)}finally{setCloudChanging(false)}});cloudSwitchQueue=run;return run;}

function copyGuestToAccount(){const context=cloudContext();const run=cloudSwitchQueue.catch(()=>{}).then(async()=>{await requireCloud();assertCloudContext(context);setCloudChanging(true);try{await flushSession();const guest=await readRecord('real');if(guest){const next=structuredClone(state);for(const key of ['products','stories','plans','posts','experiments','hooks']){const ids=new Set((next[key]||[]).map(x=>x.id));next[key]=[...(next[key]||[]),...(guest[key]||[]).filter(x=>!ids.has(x.id))]}validateImport({app:'Affiliate Intelligence Studio',mode:'real',data:next});await writeCloudBatch([['cloud-backup:'+workspaceKey(),backupPayload()],[workspaceKey(),next]]);state=next;render();queueSession();}}finally{setCloudChanging(false)}});cloudSwitchQueue=run;return run;}
