function dirtyStory(){if(!storyDraft)return false;const saved=state.stories.find(s=>s.id===storyDraft.id);return !saved||storyText(saved)!==storyText(storyDraft)}
const busyActions=new Set();
async function handleAction(e){if(cloudChanging)return;const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a.startsWith('cloud-')||a.startsWith('online-')){if(cloudBusy)return;b.disabled=true;try{if(a.startsWith('cloud-'))await handleCloudAction(a);else await handleOnlineAction(a)}catch(error){cloudNote(cloudError(error));toast(cloudError(error))}finally{b.disabled=false}return;}const lock=['save-story','ready-story'].includes(a)?'story-save':['save-profile','generate-story','demo','import-merge','confirm-import'].includes(a)?a:null;if(lock&&busyActions.has(lock))return;if(lock){busyActions.add(lock);b.disabled=true}try{if(a==='nav'){await navigateTo(b.dataset.page)}
if(a==='product-step'||a==='step-next'||a==='step-back'){capture();productStep=a==='product-step'?Number(b.dataset.step):Math.max(0,Math.min(3,productStep+(a==='step-next'?1:-1)));applyProductStep();window.scrollTo(0,0)}
if(a==='product-layout'){capture();productFilters.view=b.dataset.view;render()}
if(a==='clear-product-filters'){productFilters={query:'',status:'all',evidence:'all',view:productFilters.view};clearDraft('products');render()}
if(a==='studio-tab'){syncStory();recordStoryHistory();capture();studioTab=b.dataset.tab;applyStudioTab();window.scrollTo(0,0)}
if(a==='undo-story')undoStory(-1);
if(a==='redo-story')undoStory(1);
if(a==='restore-revision')revisionPreview(b.dataset.id);
if(a==='confirm-restore-revision')confirmRevisionRestore();
if(a==='teleprompter')openTeleprompter();
if(a==='prompt-toggle')togglePrompter();
if(a==='prompt-reset'){promptElapsed=0;promptLast=0;$('#prompt-scroll').scrollTop=0;$('#prompt-clock').textContent='00:00'}
if(a==='copy-part'){syncStory();const part=b.dataset.part,value=part==='cta'?storyDraft.shots.at(-1).voice:part==='scene'?storyDraft.shots[Number(b.dataset.scene)].voice:part==='caption'?storyDraft.caption+'\n'+storyDraft.disclosure:storyDraft[part];await copy(value||'')}
if(a==='save-hook'){syncStory();state.hooks=state.hooks||[];if(state.hooks.some(h=>h.text===storyDraft.hookA))throw Error(T('มี Hook นี้ในคลังแล้ว','This hook is already saved.'));state.hooks.push({id:uid(),text:storyDraft.hookA,name:storyDraft.name,productId:storyDraft.productId,audience:storyDraft.brief.audience,createdAt:now()});await persist();capture();render();toast(T('เก็บ Hook แล้ว','Hook saved.'))}
if(a==='use-hook'){if(!storyDraft)throw Error(T('เปิดหรือสร้างบทก่อนใช้ Hook','Open or generate a story before applying a hook.'));syncStory();recordStoryHistory();const h=(state.hooks||[]).find(h=>h.id===b.dataset.id)||state.stories.map(s=>({id:s.id,text:s.hookA})).find(h=>h.id===b.dataset.id);if(h){storyDraft.hookA=h.text;storyDraft.shots[0].voice=h.text;storyDraft.ready=false;storyDraft.reviewed=false;storyDraft.linkChecked=false;clearDraft('studio');studioTab='script';render();recordStoryHistory()}}
if(a==='more')modal(T('พื้นที่ทำงานเพิ่มเติม','More workspace tools'),navItems().filter(([k])=>['products','results','lab','settings'].includes(k)).map(([k,l])=>btn(l,'modal-nav','ghost',`data-page="${k}"`)).join(' '));
if(a==='modal-nav'){$('#dialog').close();await navigateTo(b.dataset.page)}
if(a==='lang'){syncStory();capture();lang=lang==='th'?'en':'th';try{localStorage.setItem('aff-lang',lang)}catch{}render()}
if(a==='new-product'){switchProductDraft(null);page='analyze';render();window.scrollTo(0,0)}
if(a==='edit-product'){await navigateTo('analyze',b.dataset.id)}
if(a==='copy-link')await copy(product(b.dataset.id).affiliate);
if(a==='product-story'){syncStory();if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);studioProductId=b.dataset.id;storyDraft=null;studioTab='brief';clearDraft('studio');page='studio';render();window.scrollTo(0,0)}
if(a==='compare'){const ps=$$('.compare-check:checked').map(el=>product(el.value));if(ps.length<2||ps.length>5)throw Error(T('เลือก 2–5 สินค้า','Select 2–5 products.'));$('#comparison').innerHTML=`<section class="card"><h2>${T('เปรียบเทียบข้อมูล','Evidence comparison')}</h2><p class="notice info">${T('ใช้ rubric เดียวกัน แต่ชุดมิติและรุ่นอาจต่างกัน ห้ามสรุปว่าราคาถูกที่สุดจากตารางนี้','Same rubric, but dimensions and variants may differ. This is not a cheapest-product ranking.')}</p><div class="tablewrap"><table><thead><tr><th>${T('มิติ','Dimension')}</th>${ps.map(p=>`<th>${esc(p.title)}<br><small>${esc(p.variant)}</small></th>`).join('')}</tr></thead><tbody><tr><td>${T('โอกาส / Coverage','Opportunity / coverage')}</td>${ps.map(p=>`<td>${formatScore(p)} / ${score(p).coverage}%</td>`).join('')}</tr><tr><td>${T('ราคา','Price')}</td>${ps.map(p=>`<td>${money(p.price)}</td>`).join('')}</tr>${dimensions().map(([n],i)=>`<tr><td>${n}</td>${ps.map(p=>`<td>${p.dims[i].rating??'—'}<p class="sub">${esc(p.dims[i].reason)}</p></td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;$('#comparison').scrollIntoView({behavior:'smooth'})}
if(a==='save-profile'){readProfile();await persist();toast(T('บันทึกบรีฟแล้ว','Brief saved.'))}
if(a==='generate-story'){if(storyDraft&&$('#storyName'))syncStory();const p=product($('#storyProduct').value),brief=readProfile();if(!brief.audience)throw Error(T('ระบุกลุ่มคนดูก่อนเลือกมุมเรื่อง','Enter an audience before choosing an angle.'));if(brief.minutes<10||brief.minutes>480)throw Error(T('เวลาถ่ายต้อง 10–480 นาที','Filming time must be 10–480 minutes.'));const angle=Number(b.dataset.angle);if(angle===1&&!brief.own)toast(T('ยังไม่มีสินค้า เปลี่ยนเป็นมุมวิธีเลือกให้','No product in hand: using a buying-guide angle.'));const next=makeStory(p,brief,angle,Number($('#duration').value),$('#storyLanguage').value,$('#platform').value);if(storyDraft&&(!state.stories.some(s=>s.id===storyDraft.id)||storyText(storyDraft)!==storyText(state.stories.find(s=>s.id===storyDraft.id)))){pendingStory=next;modal(T('มีร่างที่ยังไม่บันทึก','Unsaved story draft'),`<p>${T('บันทึกร่างปัจจุบันก่อนสร้างมุมใหม่ หรือยืนยันแทนที่ร่าง','Save the current draft first, or confirm replacing it.')}</p>`,btn(T('แทนที่ร่าง','Replace draft'),'replace-story','primary'));return}if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);storyDraft=next;studioTab='script';initStoryHistory();await persist();clearDraft('studio');render();$('#story-editor').scrollIntoView({behavior:'smooth'})}
if(a==='replace-story'){if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);storyDraft=pendingStory;studioTab='script';initStoryHistory();pendingStory=null;$('#dialog').close();clearDraft('studio');render();$('#story-editor').scrollIntoView()}
if(a==='open-story'||a==='resume-story'){await navigateTo('studio',b.dataset.id)}
if(a==='refresh-story-evidence'){syncStory();storyDraft.evidenceVersion=product(storyDraft.productId).snapshots.at(-1)?.id;storyDraft.ready=false;storyDraft.reviewed=false;storyDraft.linkChecked=false;clearDraft('studio');render();$('#story-editor').scrollIntoView();toast(T('ผูกหลักฐานล่าสุดแล้ว โปรดทวนบทและยืนยันใหม่','Latest evidence linked. Review the script and confirm again.'))}
if(a==='validate-story'){syncStory();const f=storyFlags(storyDraft);$('#quality-flags').innerHTML=f.length?f.map(x=>`<p class="notice">${esc(x)}</p>`).join(''):badge(T('ผ่านการตรวจเบื้องต้น กรุณาทวนด้วยตนเอง','Basic checks passed. Human review is still required.'),'green')}
if(a==='save-story')await saveStory(false);
if(a==='ready-story')await saveStory(true);
if(a==='copy-story'){syncStory();await copy(storyText(storyDraft))}
if(a==='view-revision'){const r=storyDraft.revisions.find(r=>r.id===b.dataset.id);modal(T('เวอร์ชันที่บันทึก','Saved revision'),`<pre>${esc(r.text)}</pre>`)}
if(a==='plan-view'){capture();planView=b.dataset.view;render()}
if(a==='complete-task'){const p=state.plans.find(x=>x.id===b.dataset.plan),t=p.tasks.find(x=>x.id===b.dataset.id),s=state.stories.find(x=>x.id===t.storyId);if(t.dependency&&p.tasks.find(x=>x.id===t.dependency)?.status!=='done')throw Error(T('ทำงานก่อนหน้าให้เสร็จก่อน','Complete the prerequisite first.'));if(['shoot','check','publish'].includes(t.type)&&(!s.ready||storyFlags(s).length))throw Error(T('บทต้องผ่านการตรวจและเป็น Ready ก่อนงานนี้','The story must pass review and be Ready before this task.'));if(t.type==='publish'){pendingTask={p,t};modal(T('ยืนยันโพสต์ด้วยตนเอง','Confirm manual publishing'),`<p>${T('คุณเผยแพร่โพสต์เองแล้วใช่ไหม? เว็บนี้ไม่ได้โพสต์แทนคุณ','Have you published this post yourself? This app does not publish it.')}</p>`,btn(T('โพสต์แล้ว','I published it'),'confirm-task','primary'));return}if(t.type==='measure'){const posts=state.posts.filter(x=>x.storyId===t.storyId).sort((a,b)=>a.publishedAt.localeCompare(b.publishedAt)),post=posts.at(-1);if(!post||Date.now()-Date.parse(post.publishedAt)<72*36e5||!post.metrics.some(m=>m.window==='72h'))throw Error(T('ลงทะเบียนโพสต์จริง รออายุครบ 72 ชั่วโมง และบันทึก snapshot ก่อนจบงานนี้','Register the actual post, wait 72 hours after publishing and save a 72h snapshot first.'));}t.status='done';await persist();capture();render()}
if(a==='confirm-task'){pendingTask.t.status='done';await persist();$('#dialog').close();capture();render();toast(T('บันทึกแล้ว เพิ่ม URL และยอดในหน้าผลโพสต์','Saved. Add the post URL and metrics in Results.'))}
if(a==='export')exportData();if(a==='export-csv')exportCSV();if(a==='close-modal'){stopPrompter();$('#dialog').close()}
if(a==='demo')await switchWorkspaceMode();
if(a==='import-merge'||a==='import-replace'){if(!pendingImport)throw Error('No import');if(a==='import-replace'){modal(T('สำรองแล้วแทนที่ข้อมูล?','Back up and replace data?'),`<p>${T('จะดาวน์โหลดสำรองข้อมูลปัจจุบันก่อน แล้วแทนที่ข้อมูลทั้งหมดในโหมดนี้ด้วยไฟล์ที่เลือก','A backup of the current workspace will download before the imported file replaces it.')}</p>`,btn(T('สำรองและแทนที่','Back up & replace'),'confirm-import','primary'));return}exportData();const next=structuredClone(state);for(const key of ['products','stories','plans','posts','experiments','hooks']){next[key]=next[key]||[];const ids=new Set(next[key].map(x=>x.id));next[key].push(...(pendingImport[key]||[]).filter(x=>!ids.has(x.id)))}validateImport({app:'Affiliate Intelligence Studio',mode,data:next});state=next;await persist();if(pendingRecovery){stashProductDraft();sessionStories={...pendingRecovery.sessionStories,...sessionStories};const current=productDrafts[selected||'_new'];productDrafts={...pendingRecovery.productDrafts,...Object.fromEntries(Object.entries(productDrafts).filter(([,d])=>hasProductDraft(d)))};if(!hasProductDraft(current)){const incoming=productDrafts[selected||'_new'];if(incoming){clearDraft('analyze');Object.assign(drafts,incoming.fields);draftImage=incoming.image;productStep=incoming.step}}drafts={...Object.fromEntries(Object.entries(pendingRecovery.drafts).filter(([k])=>!k.startsWith('analyze:')&&!k.startsWith('studio:'))),...drafts}}pendingImport=null;pendingRecovery=null;render();toast(T('นำเข้าแล้ว ID ซ้ำเก็บข้อมูลเดิม','Imported. Existing records with the same ID were preserved.'))}
if(a==='confirm-import'){exportData();state=pendingImport;await persist();const recovery=pendingRecovery;pendingImport=null;pendingRecovery=null;resetSession();if(recovery){await writeRecord('session:'+workspaceKey(),recovery);try{localStorage.removeItem(journalKey())}catch{}await loadSession()}$('#dialog').close();render();toast(T('แทนที่ข้อมูลแล้ว','Workspace replaced.'))}
if(!['nav','modal-nav','open-story','resume-story','edit-product'].includes(a))syncRoute();queueSession();}catch(err){toast(err.message||String(err))}finally{if(lock){busyActions.delete(lock);b.disabled=false}}}
let pendingStory=null,pendingTask=null;
document.addEventListener('click',handleAction);
document.addEventListener('input',e=>{if(rendering||cloudChanging)return;if(page==='studio'&&storyDraft&&e.target.closest('#story-editor')&&!['reviewed','linkChecked'].includes(e.target.id)&&!e.target.id.startsWith('shotdone')){storyDraft.reviewed=false;storyDraft.linkChecked=false;storyDraft.ready=false;if($('#reviewed'))$('#reviewed').checked=false;if($('#linkChecked'))$('#linkChecked').checked=false;if(e.target.id==='storyHookA'&&$('#voice0'))$('#voice0').value=e.target.value;if(e.target.id==='voice0'&&$('#storyHookA'))$('#storyHookA').value=e.target.value;clearTimeout(historyTimer);historyTimer=setTimeout(recordStoryHistory,300);}if(e.target.closest('#main')){clearFieldError(e.target);if(e.target.id==='productSearch'){productFilters.query=e.target.value;renderProductSearch()}queueSession()}if(e.target.id==='prompt-font'){promptFont=+e.target.value;$('#prompt-text').style.fontSize=promptFont+'px'}if(e.target.id==='prompt-speed')promptSpeed=+e.target.value;});
document.addEventListener('change',async e=>{if(rendering||cloudChanging)return;try{if(e.target.id==='cloud-auto'){cloudMeta.auto=e.target.checked;await writeRecord('cloud-meta:'+workspaceKey('real'),cloudMeta);scheduleCloudUpload();return;}if(e.target.id==='productStatus'||e.target.id==='productEvidence'){productFilters[e.target.id==='productStatus'?'status':'evidence']=e.target.value;capture();render()}if(e.target.id==='imageFile'&&e.target.files[0]){const f=e.target.files[0];if(f.size>5*1024*1024||!['image/png','image/jpeg','image/webp'].includes(f.type)){e.target.value='';throw Error(T('ใช้รูป JPG/PNG/WebP ไม่เกิน 5 MB','Use JPG/PNG/WebP up to 5 MB.'))}draftImage=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});applyProductStep()}if(e.target.closest('#main'))queueSession();if(e.target.id==='resultWindow'){filter.window=e.target.value;clearDraft('results');render()}if(e.target.id==='resultPlatform'){filter.platform=e.target.value;clearDraft('results');render()}if(e.target.id.startsWith('status-')){const p=product(e.target.id.slice(7));if(e.target.value==='ready'&&score(p).coverage<60){e.target.value=p.status;throw Error(T('หลักฐานต้องครบอย่างน้อย 60% ก่อนพร้อมทดลอง','At least 60% evidence coverage is required.'))}p.status=e.target.value;await persist()}if(e.target.id==='import-file'){const f=e.target.files[0];if(!f)return;if(f.size>20*1024*1024)throw Error(T('ไฟล์ใหญ่เกิน 20 MB','File exceeds 20 MB.'));const root=JSON.parse(await f.text());if(root.mode!==mode)throw Error(T('โหมดตัวอย่างกับข้อมูลจริงต้องนำเข้าแยกกัน เปลี่ยนโหมดให้ตรงกับไฟล์ก่อน','Demo and real backups are isolated. Switch to the matching workspace first.'));pendingImport=validateImport(root);pendingRecovery=validateRecovery(root.editingSession,pendingImport);$('#import-preview').innerHTML=`<div class="notice info mt">${T('ตรวจรูปแบบแล้ว','Validated')} · ${pendingImport.products.length} ${T('สินค้า','products')} · ${pendingImport.stories.length} ${T('บท','stories')} · ${pendingImport.posts.length} ${T('โพสต์','posts')}</div><div class="actions mt">${btn(T('รวมกับข้อมูลเดิม','Merge records'),'import-merge','cyan')}${btn(T('แทนที่ทั้งหมด','Replace workspace'),'import-replace','ghost')}</div>`}}catch(err){pendingImport=null;toast(err.message||String(err))}});
document.addEventListener('submit',async e=>{e.preventDefault();if(cloudChanging)return;if(e.target.id.startsWith('cloud-')){try{await handleCloudSubmit(e.target)}catch(error){cloudNote(cloudError(error));toast(cloudError(error))}return;}const form=e.target;if(!validateForm(form))return;if(form.dataset.saving)return;form.dataset.saving='true';const submits=[...form.querySelectorAll('[type=submit],button:not([type])')];submits.forEach(b=>b.disabled=true);const v=id=>$('#'+id).value;try{if(form.id==='product-form')await saveProduct(form);
if(form.id==='plan-form'){const chosen=$$('.plan-story:checked').map(el=>state.stories.find(s=>s.id===el.value)),weekdays=$$('.weekday:checked').map(el=>+el.value);if(!chosen.length||!weekdays.length)throw Error(T('เลือกอย่างน้อยหนึ่งบทและหนึ่งวัน','Select at least one story and weekday.'));const ongoing=new Set(state.plans.flatMap(p=>p.tasks.filter(t=>t.status!=='done').map(t=>t.storyId)));if(chosen.some(s=>ongoing.has(s.id)))throw Error(T('บทที่เลือกมีแผนที่ยังไม่เสร็จอยู่แล้ว','A selected story already has an unfinished plan.'));const cfg={start:v('planStart'),days:+v('planDays'),minutes:+v('dailyMinutes'),reserve:+v('reserve'),max:+v('maxPosts'),time:v('planTime'),arrival:v('arrival'),off:v('daysOff').split(',').map(x=>x.trim()).filter(Boolean),weekdays};if(cfg.time.split(':').map(Number).reduce((h,m)=>h*60+m)+cfg.minutes>1440)throw Error(T('ช่วงเวลาทำงานล้นวัน เลือกเวลาเริ่มให้เร็วขึ้นหรือลดนาทีต่อวัน','The work block crosses midnight. Start earlier or reduce daily minutes.'));if(cfg.off.some(d=>!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d))))throw Error(T('วันหยุดใช้รูปแบบ YYYY-MM-DD','Use YYYY-MM-DD for days off.'));const reserved={};state.plans.forEach(p=>p.tasks.forEach(t=>{reserved[t.date]=(reserved[t.date]||0)+t.effort}));const plan=schedule(chosen,cfg,reserved);if(!plan.tasks.length)throw Error(T('ไม่มีเวลาที่ว่างพอในช่วงแผนนี้','No usable capacity in this plan.'));state.plans.push(plan);await persist();clearDraft('planner');render();toast(T('สร้างแผนแล้ว งานเกินกำลังแยกไว้ด้านล่าง','Plan saved. Deferred work is listed below.'))}
if(form.id==='post-form'){const s=state.stories.find(s=>s.id===v('postStory'));if(!s)throw Error(T('เลือกบทก่อน','Choose a story.'));const url=safeUrl(v('postUrl'));if(!url)throw Error(T('URL โพสต์ไม่ถูกต้อง','Invalid post URL.'));if(state.posts.some(p=>p.url===url))throw Error(T('โพสต์ URL นี้มีแล้ว กรุณาเพิ่ม snapshot แทน','This post already exists. Add a snapshot instead.'));const dt=v('publishedAt')+':00+07:00';if(Date.parse(dt)>Date.now())throw Error(T('โพสต์ต้องเผยแพร่แล้ว ไม่ใช่เวลาอนาคต','Publication time cannot be in the future.'));state.posts.push({id:uid(),storyId:s.id,storyVersion:s.revisions.at(-1)?.id||null,productId:s.productId,productVariant:product(s.productId).variant,productTitle:product(s.productId).title,platform:s.platform,name:v('postName').trim(),url,publishedAt:dt,variant:v('postVariant'),metrics:[]});await persist();clearDraft('results');render();toast(T('บันทึกโพสต์แล้ว','Post saved.'))}
if(form.id==='metric-form'){const p=state.posts.find(p=>p.id===v('metricPost')),dt=v('metricDate')+':00+07:00',age=(Date.parse(dt)-Date.parse(p.publishedAt))/36e5,expected={'24h':24,'72h':72,'7d':168}[v('metricWindow')];if(Date.parse(dt)>Date.now())throw Error(T('เวลาสังเกตห้ามเป็นอนาคต','Observation time cannot be in the future.'));if(Math.abs(age-expected)>expected*.15)throw Error(T('อายุโพสต์ไม่ตรงช่วงที่เลือก (ยอมคลาดเคลื่อน 15%) เลือกวันเวลาที่ใกล้ช่วงวัด','Post age does not match the window (15% tolerance). Use a matching observation time.'));const m={id:uid(),window:v('metricWindow'),observedAt:dt,source:v('metricSource').trim(),attribution:v('attribution')};['views','clicks','orders','cancelled','sales','estimated','confirmed','cost','retention'].forEach(k=>m[k]=N(v('m-'+k)));if(['views','clicks','orders','confirmed'].every(k=>m[k]===null))throw Error(T('กรอกอย่างน้อยหนึ่งยอดหลัก','Enter at least one primary metric.'));if(m.cancelled!==null&&m.orders!==null&&m.cancelled>m.orders)throw Error(T('ยอดยกเลิกต้องไม่เกินยอดออเดอร์','Cancelled orders cannot exceed total orders.'));const same=p.metrics.find(x=>x.window===m.window&&x.observedAt===m.observedAt);if(same)throw Error(T('มี snapshot เวลานี้แล้ว ใช้เวลาสังเกตใหม่เพื่อแก้ไข','A snapshot exists at this time. Use a new observation timestamp.'));p.metrics.push(m);await persist();clearDraft('results');render();toast(T('บันทึก snapshot แล้ว ไม่มีการบวกยอดซ้ำ','Snapshot saved without double counting.'))}
if(form.id==='experiment-form'){if(v('expA')===v('expB'))throw Error(T('เลือกคนละโพสต์','Choose two different posts.'));state.experiments.push({id:uid(),name:v('expName'),a:v('expA'),b:v('expB'),variable:v('expVariable'),metric:v('expMetric'),window:v('expWindow'),pre:$('#expPre').checked,createdAt:now()});await persist();clearDraft('lab');render()}
if(form.id==='forecast-form'){const orders=+v('fViews')*(+v('fClick')/100)*(+v('fOrder')/100),payout=v('fMode')==='fixed'?+v('fValue'):+v('fValue')*(+v('fRate')/100),commission=orders*payout*(+v('fApproval')/100);$('#forecast-result').innerHTML=`<div class="notice info"><strong>${T('สถานการณ์สมมติ ไม่ใช่การพยากรณ์','Hypothetical scenario, not a prediction')}</strong><p>${T('ออเดอร์สมมติ','Assumed orders')}: ${num(orders)}<br>${T('คอมมิชชันสมมติหลังปรับสัดส่วนยืนยัน','Assumed commission after approval fraction')}: ${money(commission)}</p><small>${T('ที่มา','Source')}: ${esc(v('fSource'))}</small></div>`}
if(form.id==='settings-form'){['staleHours','minViews','minClicks','clickTarget','orderTarget','commissionTarget'].forEach(k=>state.settings[k]=+v(k));state.settings.reserve=+v('setReserve');state.settings.reduced=$('#reduced').checked;await persist();clearDraft('settings');render();toast(T('บันทึกการตั้งค่าแล้ว','Settings saved.'))}
syncRoute();queueSession();}catch(err){toast(err.message||String(err))}finally{delete form.dataset.saving;submits.forEach(b=>b.disabled=false)}});
window.addEventListener('beforeunload',e=>{if(saveFailure||sessionVersion>savedSessionVersion){e.preventDefault();e.returnValue=''}});
(async()=>{try{try{mode=localStorage.getItem('aff-mode')==='demo'?'demo':'real'}catch{}db=await openDB();await initCloud();await load();await loadSession();await loadCloudMeta()}catch(e){state=state||base();db=null}render();if(location.hash)await applyLocation();else syncRoute(true);cloudReady=true;await processCloudAuth();if(!db){saveFailure=true;saveIndicator('error');toast(T('พื้นที่บันทึกไม่พร้อม ส่งออกสำรองก่อนปิดหน้า','Storage unavailable. Export your work before closing.'))}})();

document.addEventListener('keydown',e=>{if(e.target.closest('.studio-tabs')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=$$('[data-action="studio-tab"][role="tab"]:not(:disabled)'),i=tabs.indexOf(e.target),next=(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].click();tabs[next].focus()}if(page==='studio'&&storyDraft&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!e.target.matches('input,textarea')){e.preventDefault();undoStory(e.shiftKey?1:-1)}});
$('#dialog').addEventListener('close',stopPrompter);
