function dirtyStory(){if(!storyDraft)return false;const saved=state.stories.find(s=>s.id===storyDraft.id);return !saved||storyText(saved)!==storyText(storyDraft)}
const busyActions=new Set();
async function handleAction(e){if(cloudChanging)return;const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a.startsWith('cloud-')||a.startsWith('online-')){if(cloudBusy)return;b.disabled=true;try{if(a.startsWith('cloud-'))await handleCloudAction(a);else await handleOnlineAction(a)}catch(error){cloudNote(cloudError(error));toast(cloudError(error))}finally{b.disabled=false}return;}const lock=['save-story','ready-story'].includes(a)?'story-save':['save-profile','generate-story','demo','import-merge','confirm-import'].includes(a)?a:null;if(lock&&busyActions.has(lock))return;if(lock){busyActions.add(lock);b.disabled=true}try{if(['workspace-menu','close-menu','store-search','explore-products','store-category','start-product-link','global-search','appearance'].includes(a)){await handleStoreAction(a,b);return}if($('#workspace-drawer').open&&['nav','demo','export'].includes(a))$('#workspace-drawer').close();if(a==='nav'){await navigateTo(b.dataset.page)}
if(a==='product-step'||a==='step-next'||a==='step-back'){capture();productStep=a==='product-step'?Number(b.dataset.step):Math.max(0,Math.min(3,productStep+(a==='step-next'?1:-1)));applyProductStep();window.scrollTo(0,0)}
if(a==='product-layout'){capture();productFilters.view=b.dataset.view;render()}
if(a==='clear-product-filters'){productFilters={query:'',status:'all',evidence:'all',view:productFilters.view};clearDraft('products');render()}
if(a==='studio-tab'){syncStory();recordStoryHistory();capture();studioTab=b.dataset.tab;applyStudioTab();window.scrollTo(0,0)}
if(a==='undo-story')undoStory(-1);
if(a==='redo-story')undoStory(1);
if(a==='restore-revision')revisionPreview(b.dataset.id);
if(a==='confirm-restore-revision')confirmRevisionRestore();
if(a==='teleprompter')openTeleprompter();
if(a==='prompt-toggle')togglePrompter();
if(a==='prompt-reset'){promptElapsed=0;promptLast=0;$('#prompt-scroll').scrollTop=0;$('#prompt-clock').textContent='00:00'}
if(a==='copy-part'){syncStory();const part=b.dataset.part,value=part==='cta'?storyDraft.shots.at(-1).voice:part==='scene'?storyDraft.shots[Number(b.dataset.scene)].voice:part==='caption'?storyDraft.caption+'\n'+storyDraft.disclosure:storyDraft[part];await copy(value||'')}
if(a==='save-hook'){syncStory();state.hooks=state.hooks||[];if(state.hooks.some(h=>h.text===storyDraft.hookA))throw Error(uiText('this_hook_is_already_saved'));state.hooks.push({id:uid(),text:storyDraft.hookA,name:storyDraft.name,productId:storyDraft.productId,audience:storyDraft.brief.audience,createdAt:now()});await persist();capture();render();toast(uiText('hook_saved'))}
if(a==='use-hook'){if(!storyDraft)throw Error(uiText('open_or_generate_a_story_before_applying_a_hook'));syncStory();recordStoryHistory();const h=(state.hooks||[]).find(h=>h.id===b.dataset.id)||state.stories.map(s=>({id:s.id,text:s.hookA})).find(h=>h.id===b.dataset.id);if(h){storyDraft.hookA=h.text;storyDraft.shots[0].voice=h.text;storyDraft.ready=false;storyDraft.reviewed=false;storyDraft.linkChecked=false;clearDraft('studio');studioTab='script';render();recordStoryHistory()}}
if(a==='more')modal(uiText('more_workspace_tools'),navItems().filter(([k])=>['products','results','lab','settings'].includes(k)).map(([k,l])=>btn(l,'modal-nav','ghost',`data-page="${k}"`)).join(' '));
if(a==='modal-nav'){$('#dialog').close();await navigateTo(b.dataset.page)}
if(a==='lang'){syncStory();capture();lang=['th','en'].includes(b.dataset.lang)?b.dataset.lang:lang==='th'?'en':'th';try{localStorage.setItem('aff-lang',lang)}catch{}render()}
if(a==='new-product'){switchProductDraft(null);page='analyze';render();window.scrollTo(0,0)}
if(a==='edit-product'){await navigateTo('analyze',b.dataset.id)}
if(a==='copy-link')await copy(product(b.dataset.id).affiliate);
if(a==='product-story'){syncStory();if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);studioProductId=b.dataset.id;storyDraft=null;studioTab='brief';clearDraft('studio');page='studio';render();window.scrollTo(0,0)}
if(a==='compare'){const ps=$$('.compare-check:checked').map(el=>product(el.value));if(ps.length<2||ps.length>5)throw Error(uiText('select_2_5_products'));$('#comparison').innerHTML=`<section class="card"><h2>${uiText('evidence_comparison')}</h2><p class="notice info">${uiText('same_rubric_but_dimensions_and_variants_may_differ_this')}</p><div class="tablewrap"><table><thead><tr><th>${uiText('dimension')}</th>${ps.map(p=>`<th>${esc(p.title)}<br><small>${esc(p.variant)}</small></th>`).join('')}</tr></thead><tbody><tr><td>${uiText('opportunity_coverage')}</td>${ps.map(p=>`<td>${formatScore(p)} / ${score(p).coverage}%</td>`).join('')}</tr><tr><td>${uiText('price')}</td>${ps.map(p=>`<td>${money(p.price)}</td>`).join('')}</tr>${dimensions().map(([n],i)=>`<tr><td>${n}</td>${ps.map(p=>`<td>${p.dims[i].rating??'—'}<p class="sub">${esc(p.dims[i].reason)}</p></td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;$('#comparison').scrollIntoView({behavior:'smooth'})}
if(a==='save-profile'){readProfile();await persist();toast(uiText('brief_saved'))}
if(a==='generate-story'){if(storyDraft&&$('#storyName'))syncStory();const p=product($('#storyProduct').value),brief=readProfile();if(!brief.audience)throw Error(uiText('enter_an_audience_before_choosing_an_angle'));if(brief.minutes<10||brief.minutes>480)throw Error(uiText('filming_time_must_be_10_480_minutes'));const angle=Number(b.dataset.angle);if(angle===1&&!brief.own)toast(uiText('no_product_in_hand_using_a_buying_guide_angle'));const next=makeStory(p,brief,angle,Number($('#duration').value),$('#storyLanguage').value,$('#platform').value);if(storyDraft&&(!state.stories.some(s=>s.id===storyDraft.id)||storyText(storyDraft)!==storyText(state.stories.find(s=>s.id===storyDraft.id)))){pendingStory=next;modal(uiText('unsaved_story_draft'),`<p>${uiText('save_the_current_draft_first_or_confirm_replacing_it')}</p>`,btn(uiText('replace_draft'),'replace-story','primary'));return}if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);storyDraft=next;studioTab='script';initStoryHistory();await persist();clearDraft('studio');render();$('#story-editor').scrollIntoView({behavior:'smooth'})}
if(a==='replace-story'){if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);storyDraft=pendingStory;studioTab='script';initStoryHistory();pendingStory=null;$('#dialog').close();clearDraft('studio');render();$('#story-editor').scrollIntoView()}
if(a==='open-story'||a==='resume-story'){await navigateTo('studio',b.dataset.id)}
if(a==='refresh-story-evidence'){syncStory();storyDraft.evidenceVersion=product(storyDraft.productId).snapshots.at(-1)?.id;storyDraft.ready=false;storyDraft.reviewed=false;storyDraft.linkChecked=false;clearDraft('studio');render();$('#story-editor').scrollIntoView();toast(uiText('latest_evidence_linked_review_the_script_and_confirm_ag'))}
if(a==='validate-story'){syncStory();const f=storyFlags(storyDraft);$('#quality-flags').innerHTML=f.length?f.map(x=>`<p class="notice">${esc(x)}</p>`).join(''):badge(uiText('basic_checks_passed_human_review_is_still_required'),'green')}
if(a==='save-story')await saveStory(false);
if(a==='ready-story')await saveStory(true);
if(a==='copy-story'){syncStory();await copy(storyText(storyDraft))}
if(a==='view-revision'){const r=storyDraft.revisions.find(r=>r.id===b.dataset.id);modal(uiText('saved_revision'),`<pre>${esc(r.text)}</pre>`)}
if(a==='plan-view'){capture();planView=b.dataset.view;render()}
if(a==='complete-task'){const p=state.plans.find(x=>x.id===b.dataset.plan),t=p.tasks.find(x=>x.id===b.dataset.id),s=state.stories.find(x=>x.id===t.storyId);if(t.dependency&&p.tasks.find(x=>x.id===t.dependency)?.status!=='done')throw Error(uiText('complete_the_prerequisite_first'));if(['shoot','check','publish'].includes(t.type)&&(!s.ready||storyFlags(s).length))throw Error(uiText('the_story_must_pass_review_and_be_ready_before_this_tas'));if(t.type==='publish'){pendingTask={p,t};modal(uiText('confirm_manual_publishing'),`<p>${uiText('have_you_published_this_post_yourself_this_app_does_not')}</p>`,btn(uiText('i_published_it'),'confirm-task','primary'));return}if(t.type==='measure'){const posts=state.posts.filter(x=>x.storyId===t.storyId).sort((a,b)=>a.publishedAt.localeCompare(b.publishedAt)),post=posts.at(-1);if(!post||Date.now()-Date.parse(post.publishedAt)<72*36e5||!post.metrics.some(m=>m.window==='72h'))throw Error(uiText('register_the_actual_post_wait_72_hours_after_publishing'));}t.status='done';await persist();capture();render()}
if(a==='confirm-task'){pendingTask.t.status='done';await persist();$('#dialog').close();capture();render();toast(uiText('saved_add_the_post_url_and_metrics_in_results'))}
if(a==='export')exportData();if(a==='export-csv')exportCSV();if(a==='close-modal'){stopPrompter();$('#dialog').close()}
if(a==='demo')await switchWorkspaceMode();
if(a==='import-merge'||a==='import-replace'){if(!pendingImport)throw Error('No import');if(a==='import-replace'){modal(uiText('back_up_and_replace_data'),`<p>${uiText('a_backup_of_the_current_workspace_will_download_before_')}</p>`,btn(uiText('back_up_replace'),'confirm-import','primary'));return}exportData();const next=structuredClone(state);for(const key of ['products','stories','plans','posts','experiments','hooks']){next[key]=next[key]||[];const ids=new Set(next[key].map(x=>x.id));next[key].push(...(pendingImport[key]||[]).filter(x=>!ids.has(x.id)))}validateImport({app:'Affiliate Intelligence Studio',mode,data:next});state=next;await persist();if(pendingRecovery){stashProductDraft();sessionStories={...pendingRecovery.sessionStories,...sessionStories};const current=productDrafts[selected||'_new'];productDrafts={...pendingRecovery.productDrafts,...Object.fromEntries(Object.entries(productDrafts).filter(([,d])=>hasProductDraft(d)))};if(!hasProductDraft(current)){const incoming=productDrafts[selected||'_new'];if(incoming){clearDraft('analyze');Object.assign(drafts,incoming.fields);draftImage=incoming.image;productStep=incoming.step}}drafts={...Object.fromEntries(Object.entries(pendingRecovery.drafts).filter(([k])=>!k.startsWith('analyze:')&&!k.startsWith('studio:'))),...drafts}}pendingImport=null;pendingRecovery=null;render();toast(uiText('imported_existing_records_with_the_same_id_were_preserv'))}
if(a==='confirm-import'){exportData();state=pendingImport;await persist();const recovery=pendingRecovery;pendingImport=null;pendingRecovery=null;resetSession();if(recovery){await writeRecord('session:'+workspaceKey(),recovery);try{localStorage.removeItem(journalKey())}catch{}await loadSession()}$('#dialog').close();render();toast(uiText('workspace_replaced'))}
if(!['nav','modal-nav','open-story','resume-story','edit-product'].includes(a))syncRoute();queueSession();}catch(err){toast(err.message||String(err))}finally{if(lock){busyActions.delete(lock);b.disabled=false}}}
let pendingStory=null,pendingTask=null;
document.addEventListener('click',handleAction);
document.addEventListener('input',e=>{if(rendering||cloudChanging)return;if(page==='studio'&&storyDraft&&e.target.closest('#story-editor')&&!['reviewed','linkChecked'].includes(e.target.id)&&!e.target.id.startsWith('shotdone')){storyDraft.reviewed=false;storyDraft.linkChecked=false;storyDraft.ready=false;if($('#reviewed'))$('#reviewed').checked=false;if($('#linkChecked'))$('#linkChecked').checked=false;if(e.target.id==='storyHookA'&&$('#voice0'))$('#voice0').value=e.target.value;if(e.target.id==='voice0'&&$('#storyHookA'))$('#storyHookA').value=e.target.value;clearTimeout(historyTimer);historyTimer=setTimeout(recordStoryHistory,300);}if(e.target.id==='global-query')clearFieldError(e.target);if(e.target.closest('#main')){clearFieldError(e.target);if(e.target.id==='productSearch'){productFilters.query=e.target.value;renderProductSearch()}queueSession()}if(e.target.id==='prompt-font'){promptFont=+e.target.value;$('#prompt-text').style.fontSize=promptFont+'px'}if(e.target.id==='prompt-speed')promptSpeed=+e.target.value;});
document.addEventListener('change',async e=>{if(rendering||cloudChanging)return;try{if(e.target.id==='store-sort'){storefrontSort=['newest','evidence','commission','price'].includes(e.target.value)?e.target.value:'newest';capture();render();$('#store-sort')?.focus();return;}if(e.target.id==='cloud-auto'){cloudMeta.auto=e.target.checked;await writeRecord('cloud-meta:'+workspaceKey('real'),cloudMeta);scheduleCloudUpload();return;}if(['productStatus','productEvidence','productCategory'].includes(e.target.id)){productFilters[e.target.id==='productStatus'?'status':e.target.id==='productCategory'?'category':'evidence']=e.target.value;capture();render()}if(e.target.id==='imageFile'&&e.target.files[0]){const f=e.target.files[0];if(f.size>5*1024*1024||!['image/png','image/jpeg','image/webp'].includes(f.type)){e.target.value='';throw Error(uiText('use_jpg_png_webp_up_to_5_mb'))}draftImage=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});applyProductStep()}if(e.target.closest('#main'))queueSession();if(e.target.id==='resultWindow'){filter.window=e.target.value;clearDraft('results');render()}if(e.target.id==='resultPlatform'){filter.platform=e.target.value;clearDraft('results');render()}if(e.target.id.startsWith('status-')){const p=product(e.target.id.slice(7));if(e.target.value==='ready'&&score(p).coverage<60){e.target.value=p.status;throw Error(uiText('at_least_60_evidence_coverage_is_required'))}p.status=e.target.value;await persist()}if(e.target.id==='import-file'){const f=e.target.files[0];if(!f)return;if(f.size>20*1024*1024)throw Error(uiText('file_exceeds_20_mb'));const root=JSON.parse(await f.text());if(root.mode!==mode)throw Error(uiText('demo_and_real_backups_are_isolated_switch_to_the_matchi'));pendingImport=validateImport(root);pendingRecovery=validateRecovery(root.editingSession,pendingImport);$('#import-preview').innerHTML=`<div class="notice info mt">${uiText('validated')} · ${pendingImport.products.length} ${uiText('products')} · ${pendingImport.stories.length} ${uiText('stories')} · ${pendingImport.posts.length} ${uiText('posts')}</div><div class="actions mt">${btn(uiText('merge_records'),'import-merge','cyan')}${btn(uiText('replace_workspace'),'import-replace','ghost')}</div>`}}catch(err){pendingImport=null;toast(err.message||String(err))}});
document.addEventListener('submit',async e=>{e.preventDefault();if(cloudChanging)return;if(e.target.id.startsWith('cloud-')){try{await handleCloudSubmit(e.target)}catch(error){cloudNote(cloudError(error));toast(cloudError(error))}return;}const form=e.target;if(!validateForm(form))return;if(form.dataset.saving)return;form.dataset.saving='true';const submits=[...form.querySelectorAll('[type=submit],button:not([type])')];submits.forEach(b=>b.disabled=true);const v=id=>$('#'+id).value;try{if(form.id==='product-form')await saveProduct(form);
if(form.id==='plan-form'){const chosen=$$('.plan-story:checked').map(el=>state.stories.find(s=>s.id===el.value)),weekdays=$$('.weekday:checked').map(el=>+el.value);if(!chosen.length||!weekdays.length)throw Error(uiText('select_at_least_one_story_and_weekday'));const ongoing=new Set(state.plans.flatMap(p=>p.tasks.filter(t=>t.status!=='done').map(t=>t.storyId)));if(chosen.some(s=>ongoing.has(s.id)))throw Error(uiText('a_selected_story_already_has_an_unfinished_plan'));const cfg={start:v('planStart'),days:+v('planDays'),minutes:+v('dailyMinutes'),reserve:+v('reserve'),max:+v('maxPosts'),time:v('planTime'),arrival:v('arrival'),off:v('daysOff').split(',').map(x=>x.trim()).filter(Boolean),weekdays};if(cfg.time.split(':').map(Number).reduce((h,m)=>h*60+m)+cfg.minutes>1440)throw Error(uiText('the_work_block_crosses_midnight_start_earlier_or_reduce'));if(cfg.off.some(d=>!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d))))throw Error(uiText('use_yyyy_mm_dd_for_days_off'));const reserved={};state.plans.forEach(p=>p.tasks.forEach(t=>{reserved[t.date]=(reserved[t.date]||0)+t.effort}));const plan=schedule(chosen,cfg,reserved);if(!plan.tasks.length)throw Error(uiText('no_usable_capacity_in_this_plan'));state.plans.push(plan);await persist();clearDraft('planner');render();toast(uiText('plan_saved_deferred_work_is_listed_below'))}
if(form.id==='post-form'){const s=state.stories.find(s=>s.id===v('postStory'));if(!s)throw Error(uiText('choose_a_story'));const url=safeUrl(v('postUrl'));if(!url)throw Error(uiText('invalid_post_url'));if(state.posts.some(p=>p.url===url))throw Error(uiText('this_post_already_exists_add_a_snapshot_instead'));const dt=v('publishedAt')+':00+07:00';if(Date.parse(dt)>Date.now())throw Error(uiText('publication_time_cannot_be_in_the_future'));state.posts.push({id:uid(),storyId:s.id,storyVersion:s.revisions.at(-1)?.id||null,productId:s.productId,productVariant:product(s.productId).variant,productTitle:product(s.productId).title,platform:s.platform,name:v('postName').trim(),url,publishedAt:dt,variant:v('postVariant'),metrics:[]});await persist();clearDraft('results');render();toast(uiText('post_saved'))}
if(form.id==='metric-form'){const p=state.posts.find(p=>p.id===v('metricPost')),dt=v('metricDate')+':00+07:00',age=(Date.parse(dt)-Date.parse(p.publishedAt))/36e5,expected={'24h':24,'72h':72,'7d':168}[v('metricWindow')];if(Date.parse(dt)>Date.now())throw Error(uiText('observation_time_cannot_be_in_the_future'));if(Math.abs(age-expected)>expected*.15)throw Error(uiText('post_age_does_not_match_the_window_15_tolerance_use_a_m'));const m={id:uid(),window:v('metricWindow'),observedAt:dt,source:v('metricSource').trim(),attribution:v('attribution')};['views','clicks','orders','cancelled','sales','estimated','confirmed','cost','retention'].forEach(k=>m[k]=N(v('m-'+k)));if(['views','clicks','orders','confirmed'].every(k=>m[k]===null))throw Error(uiText('enter_at_least_one_primary_metric'));if(m.cancelled!==null&&m.orders!==null&&m.cancelled>m.orders)throw Error(uiText('cancelled_orders_cannot_exceed_total_orders'));const same=p.metrics.find(x=>x.window===m.window&&x.observedAt===m.observedAt);if(same)throw Error(uiText('a_snapshot_exists_at_this_time_use_a_new_observation_ti'));p.metrics.push(m);await persist();clearDraft('results');render();toast(uiText('snapshot_saved_without_double_counting'))}
if(form.id==='experiment-form'){if(v('expA')===v('expB'))throw Error(uiText('choose_two_different_posts'));state.experiments.push({id:uid(),name:v('expName'),a:v('expA'),b:v('expB'),variable:v('expVariable'),metric:v('expMetric'),window:v('expWindow'),pre:$('#expPre').checked,createdAt:now()});await persist();clearDraft('lab');render()}
if(form.id==='forecast-form'){const orders=+v('fViews')*(+v('fClick')/100)*(+v('fOrder')/100),payout=v('fMode')==='fixed'?+v('fValue'):+v('fValue')*(+v('fRate')/100),commission=orders*payout*(+v('fApproval')/100);$('#forecast-result').innerHTML=`<div class="notice info"><strong>${uiText('hypothetical_scenario_not_a_prediction')}</strong><p>${uiText('assumed_orders')}: ${num(orders)}<br>${uiText('assumed_commission_after_approval_fraction')}: ${money(commission)}</p><small>${uiText('source')}: ${esc(v('fSource'))}</small></div>`}
if(form.id==='settings-form'){['staleHours','minViews','minClicks','clickTarget','orderTarget','commissionTarget'].forEach(k=>state.settings[k]=+v(k));state.settings.reserve=+v('setReserve');state.settings.reduced=$('#reduced').checked;await persist();clearDraft('settings');render();toast(uiText('settings_saved'))}
syncRoute();queueSession();}catch(err){toast(err.message||String(err))}finally{delete form.dataset.saving;submits.forEach(b=>b.disabled=false)}});
window.addEventListener('beforeunload',e=>{if(saveFailure||sessionVersion>savedSessionVersion){e.preventDefault();e.returnValue=''}});
(async()=>{try{try{mode=localStorage.getItem('aff-mode')==='demo'?'demo':'real'}catch{}db=await openDB();await initCloud();await load();await loadSession();await loadCloudMeta()}catch(e){state=state||base();db=null}render();if(location.hash)await applyLocation();else syncRoute(true);cloudReady=true;await processCloudAuth();if(!db){saveFailure=true;saveIndicator('error');toast(uiText('storage_unavailable_export_your_work_before_closing'))}})();

document.addEventListener('keydown',e=>{if(e.target.closest('.studio-tabs')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=$$('[data-action="studio-tab"][role="tab"]:not(:disabled)'),i=tabs.indexOf(e.target),next=(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].click();tabs[next].focus()}if(page==='studio'&&storyDraft&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!e.target.matches('input,textarea')){e.preventDefault();undoStory(e.shiftKey?1:-1)}});
$('#dialog').addEventListener('close',stopPrompter);

$('#workspace-drawer').addEventListener('close',()=>{$('#menu-toggle').setAttribute('aria-expanded','false');$('#menu-toggle').focus()});
// Skip within the current screen without invoking the hash-based workspace router.
$('.skip-link').addEventListener('click',e=>{e.preventDefault();$('#main').focus({preventScroll:true});$('#main').scrollIntoView({block:'start',behavior:'instant'})});

// The quick-entry field supports Enter without replacing an existing product draft.
document.addEventListener('keydown',e=>{if(e.target.id==='creator-link'&&e.key==='Enter'){e.preventDefault();$('[data-action="start-product-link"]')?.click()}});

document.addEventListener('keydown',e=>{if(e.target.id==='global-query'&&e.key==='Enter'){e.preventDefault();$('#global-search-button').click()}});
