'use strict';
const VERSION=2, RUBRIC='2.0-manual', WEIGHTS=[20,20,15,15,10,10,10];
let rendering=false;
let lang=(()=>{try{return localStorage.getItem('aff-lang')==='en'?'en':'th'}catch{return 'th'}})(), mode='real', page='today', db, state, selected=null, drafts={}, storyDraft=null, planView='list', filter={window:'72h',platform:'all'}, pendingImport=null,pendingRecovery=null;
const uiText=key=>TRANSLATIONS[lang]?.[key]??TRANSLATIONS.en[key]??key;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const now=()=>new Date().toISOString(), today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function dayPlus(d,n){let x=new Date(d+'T12:00:00+07:00');x.setUTCDate(x.getUTCDate()+n);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(x)}
const date=v=>v?new Intl.DateTimeFormat(lang==='th'?'th-TH':'en-GB',{dateStyle:'medium',timeZone:'Asia/Bangkok'}).format(new Date(v.length===10?v+'T12:00:00+07:00':v)):'—';
const num=v=>v===null||v===undefined||!Number.isFinite(+v)?'—':new Intl.NumberFormat(lang==='th'?'th-TH':'en-US',{maximumFractionDigits:2}).format(v);
const money=v=>v===null||v===undefined?'—':'฿'+num(v);
const N=v=>v===''||v===null||v===undefined?null:Number(v);
const ratio=(n,d,k=1)=>n===null||d===null||d<=0?null:n/d*k;
const safeUrl=u=>{try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)&&!x.username&&!x.password?x.href:''}catch{return ''}};
const shopee=u=>{try{const x=new URL(u);return x.protocol==='https:'&&!x.username&&!x.password&&['shopee.co.th','www.shopee.co.th','s.shopee.co.th','shope.ee'].includes(x.hostname)}catch{return false}};
const safeImage=u=>/^data:image\/(png|jpeg|webp);base64,[a-zA-Z0-9+/=]+$/.test(u||'')||safeUrl(u)?u:'';
const icon=k=>commerceIcons[k]||commerceIcons.analyze;
const badge=(s,c='')=>`<span class="badge ${c}">${esc(s)}</span>`;
const btn=(label,action,cls='',extra='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const field=(id,label,value='',type='text',extra='')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" value="${esc(value)}" ${extra}></div>`;
const area=(id,label,value='',extra='')=>`<div class="field"><label for="${id}">${label}</label><textarea id="${id}" name="${id}" ${extra}>${esc(value)}</textarea></div>`;
const sel=(id,label,options,value='')=>`<div class="field"><label for="${id}">${label}</label><select id="${id}" name="${id}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`;
const empty=(title,desc,action='analyze',label=uiText('add_your_first_product'))=>`<div class="empty"><div class="empty-icon">${icon('products')}</div><h2>${title}</h2><p>${desc}</p>${btn(label,'nav','primary',`data-page="${action}"`)}</div>`;
function base(){return {schemaVersion:2,products:[],stories:[],plans:[],posts:[],experiments:[],hooks:[],profile:{audience:'',goal:'educate',tone:'friendly',own:false,face:false,experience:'',equipment:'',minutes:60,budget:null,avoid:''},settings:{reserve:20,staleHours:24,minViews:1000,minClicks:30,clickTarget:2,orderTarget:3,commissionTarget:20,reduced:false},createdAt:now()}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),4200)}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('affiliate-intelligence-v2',1);r.onupgradeneeded=()=>r.result.createObjectStore('workspaces');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function load(){if(!db){state=base();return}state=await new Promise((res,rej)=>{let r=db.transaction('workspaces').objectStore('workspaces').get(workspaceKey());r.onsuccess=()=>res(r.result||base());r.onerror=()=>rej(r.error)});}
async function persist(){saveIndicator('saving');try{await writeRecord(workspaceKey(),state);businessSaveFailure=false;saveFailure=sessionSaveFailure;saveIndicator(saveFailure?'error':sessionVersion>savedSessionVersion?'saving':'saved')}catch(err){businessSaveFailure=true;saveFailure=true;saveIndicator('error');throw Error(uiText('save_failed_your_work_remains_in_this_page_export_a_bac'))}}
function capture(){if($('#main'))$$('#main input,#main textarea,#main select').forEach(e=>{if(e.id&&e.type!=='file'&&e.type!=='password'&&!e.closest('[data-private]'))drafts[page+':'+e.id]=e.type==='checkbox'?e.checked:e.value})}
function restore(){Object.entries(drafts).filter(([k])=>k.startsWith(page+':')).forEach(([k,v])=>{const el=document.getElementById(k.slice(page.length+1));if(el&&el.type!=='password'&&!el.closest('[data-private]')){if(el.type==='checkbox')el.checked=v;else el.value=v}})}
function clearDraft(p){Object.keys(drafts).filter(k=>k.startsWith(p+':')).forEach(k=>delete drafts[k])}
const product=id=>state.products.find(p=>p.id===id);
const dimensions=()=>[[uiText('problem_use_case'),uiText('who_has_the_problem_in_what_situation')],[uiText('demonstration_potential'),uiText('describe_a_shoot_or_test_do_not_infer_from_images')],[uiText('price_value'),uiText('variant_price_and_comparable_alternatives')],[uiText('reviews_seller'),uiText('rating_review_count_and_actual_review_samples')],[uiText('known_commission'),uiText('rate_or_payout_with_checked_eligibility')],[uiText('purchase_friction'),uiText('higher_clear_compatibility_and_simpler_purchase')],[uiText('distinct_story_angle'),uiText('describe_the_difference_and_supporting_evidence')]];
function score(p){let weight=0,total=0,count=0;(p.dims||[]).forEach((d,i)=>{if(d.rating!==null&&Number.isFinite(d.rating)&&d.rating>=0&&d.rating<=5&&d.evidence?.trim()&&d.reason?.trim()){weight+=WEIGHTS[i];total+=WEIGHTS[i]*d.rating/5;count++}});return {coverage:weight,score:weight<60?null:Math.round(100*total/weight),count}}
function stale(p){return !p.observedAt||(Date.now()-Date.parse(p.observedAt))/36e5>state.settings.staleHours}
function formatScore(p){let s=score(p);return s.score===null?'—':s.score}
function navItems(){return [['today',uiText('emerald_home')],['analyze',uiText('product_intelligence')],['products',uiText('selling_list')],['studio',uiText('story_studio')],['planner',uiText('planner')],['results',uiText('results')],['lab',uiText('experiment_lab')],['settings',uiText('settings_backup')]]}
function render(){rendering=true;try{document.documentElement.lang=lang;document.body.classList.toggle('reduce',state.settings.reduced);const nav=navItems();$('#nav').innerHTML=nav.map(([k,l])=>`<button data-action="nav" data-page="${k}" class="${page===k?'active':''} ${['today','analyze','studio','planner'].includes(k)?'mobile':''}" ${page===k?'aria-current="page"':''}>${icon(k)}<span class="nav-copy"><strong>${l}</strong>${lang==='th'?`<small>${({today:'Home',analyze:'Product Research',products:'Product Library',studio:'Content Studio',planner:'Content Plan',results:'Post Analytics',lab:'Experiments',settings:'Settings'})[k]}</small>`:''}</span>${k==='products'?`<span class="navcount">${state.products.length}</span>`:''}</button>`).join('')+`<button data-action="more" class="mobile ${['products','results','lab','settings'].includes(page)?'active':''}">${icon('more')}<span>${uiText('more')}</span></button>`;$('#crumb').textContent=uiText('workspace')+(nav.find(x=>x[0]===page)?.[1]||'');$('#demo').textContent=mode==='demo'?uiText('my_workspace'):uiText('try_demo');$('#mode-badge').innerHTML=badge(uiText('local_workspace_2'),'cyan');$('#demo-banner').classList.toggle('hidden',mode!=='demo');$('#demo-banner').textContent=uiText('demo_workspace_fictional_data_isolated_from_your_real_r');$('#local-label').textContent=uiText('data_stays_on_this_device');$('#nav-label').textContent=uiText('workspace_2');$('#backup-top').textContent=uiText('backup');$('#save-status').textContent=db?uiText('local_autosave'):uiText('storage_unavailable_export_backup');const views={today:todayView,analyze:analyzeView,products:productsView,studio:studioView,planner:plannerView,results:resultsView,lab:labView,settings:settingsView};$('#main').innerHTML=views[page]();restore();enhanceView();enhanceStorefront();if($('#account-top'))$('#account-top').textContent=cloudUser?uiText('account'):uiText('sign_in');}finally{rendering=false}}
function head(k,title,sub,actions=''){return `<div class="pagehead"><div><div class="eyebrow">${k}</div><h1>${title}</h1>${sub?`<p class="muted">${sub}</p>`:''}</div>${actions}</div>`}
function kpi(label,value,note,color=''){return `<div class="card stat"><span class="muted">${label}</span><div class="value ${color}">${value}</div><span class="sub">${note}</span></div>`}
function paired(rows,a,b,mul=1){const valid=rows.filter(x=>x[a]!==null&&x[a]!==undefined&&x[b]!==null&&x[b]!==undefined);return valid.length?ratio(valid.reduce((n,x)=>n+x[a],0),valid.reduce((n,x)=>n+x[b],0),mul):null}
function total(rows,key){let r=rows.filter(x=>x[key]!==null&&x[key]!==undefined);return r.length?r.reduce((n,x)=>n+x[key],0):null}
function latestRows(window=filter.window,platform=filter.platform){return state.posts.filter(p=>platform==='all'||p.platform===platform).flatMap(p=>{const m=p.metrics.filter(x=>x.window===window).sort((a,b)=>a.observedAt.localeCompare(b.observedAt)).at(-1);return m?[{...m,post:p}]:[]})}
function attributed(rows){return rows.filter(x=>x.attribution==='post')}
