'use strict';
const VERSION=2, RUBRIC='2.0-manual', WEIGHTS=[20,20,15,15,10,10,10];
let rendering=false;
let lang=(()=>{try{return localStorage.getItem('aff-lang')||'th'}catch{return 'th'}})(), mode='real', page='today', db, state, selected=null, drafts={}, storyDraft=null, planView='list', filter={window:'72h',platform:'all'}, pendingImport=null,pendingRecovery=null;
const T=(th,en)=>lang==='th'?th:en;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const now=()=>new Date().toISOString(), today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function dayPlus(d,n){let x=new Date(d+'T12:00:00+07:00');x.setUTCDate(x.getUTCDate()+n);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(x)}
const date=v=>v?new Intl.DateTimeFormat(lang==='th'?'th-TH':'en-GB',{dateStyle:'medium',timeZone:'Asia/Bangkok'}).format(new Date(v.length===10?v+'T12:00:00+07:00':v)):'—';
const num=v=>v===null||v===undefined||!Number.isFinite(+v)?'—':new Intl.NumberFormat(lang==='th'?'th-TH':'en-US',{maximumFractionDigits:2}).format(v);
const money=v=>v===null||v===undefined?'—':'฿'+num(v);
const N=v=>v===''||v===null||v===undefined?null:Number(v);
const ratio=(n,d,k=1)=>n===null||d===null||d<=0?null:n/d*k;
const safeUrl=u=>{try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)&&!x.username&&!x.password?x.href:''}catch{return ''}};
const shopee=u=>{try{const x=new URL(u);return x.protocol==='https:'&&!x.username&&!x.password&&['shopee.co.th','www.shopee.co.th','s.shopee.co.th','shope.ee'].includes(x.hostname)}catch{return false}};
const safeImage=u=>/^data:image\/(png|jpeg|webp);base64,[a-zA-Z0-9+/=]+$/.test(u||'')||safeUrl(u)?u:'';
const icons={today:'M3 10 12 3l9 7v10H3z M9 20v-7h6v7',analyze:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6 M7 10h6 M10 7v6',products:'m3 7 9-4 9 4v11l-9 4-9-4z M3 7l9 4 9-4 M12 11v11',studio:'M4 4h16v16H4z M9 8l7 4-7 4z',planner:'M4 5h16v16H4z M7 2v6 M17 2v6 M4 11h16',results:'M4 3v18h17 M8 16v-5 M13 16V6 M18 16V9',lab:'M9 3h6 M10 3v6L4 19q-1 2 2 2h12q3 0 2-2L14 9V3 M7 15h10',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',more:'M4 5h16 M4 12h16 M4 19h16'};
const icon=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[k]||icons.analyze}"/></svg>`;
const badge=(s,c='')=>`<span class="badge ${c}">${esc(s)}</span>`;
const btn=(label,action,cls='',extra='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const field=(id,label,value='',type='text',extra='')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" value="${esc(value)}" ${extra}></div>`;
const area=(id,label,value='',extra='')=>`<div class="field"><label for="${id}">${label}</label><textarea id="${id}" name="${id}" ${extra}>${esc(value)}</textarea></div>`;
const sel=(id,label,options,value='')=>`<div class="field"><label for="${id}">${label}</label><select id="${id}" name="${id}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`;
const empty=(title,desc,action='analyze',label=T('เพิ่มสินค้าแรก','Add your first product'))=>`<div class="empty"><div class="empty-icon">${icon('products')}</div><h2>${title}</h2><p>${desc}</p>${btn(label,'nav','primary',`data-page="${action}"`)}</div>`;
function base(){return {schemaVersion:2,products:[],stories:[],plans:[],posts:[],experiments:[],hooks:[],profile:{audience:'',goal:'educate',tone:'friendly',own:false,face:false,experience:'',equipment:'',minutes:60,budget:null,avoid:''},settings:{reserve:20,staleHours:24,minViews:1000,minClicks:30,clickTarget:2,orderTarget:3,commissionTarget:20,reduced:false},createdAt:now()}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),4200)}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('affiliate-intelligence-v2',1);r.onupgradeneeded=()=>r.result.createObjectStore('workspaces');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function load(){if(!db){state=base();return}state=await new Promise((res,rej)=>{let r=db.transaction('workspaces').objectStore('workspaces').get(mode);r.onsuccess=()=>res(r.result||base());r.onerror=()=>rej(r.error)});}
async function persist(){saveIndicator('saving');try{await writeRecord(mode,state);businessSaveFailure=false;saveFailure=sessionSaveFailure;saveIndicator(saveFailure?'error':sessionVersion>savedSessionVersion?'saving':'saved')}catch(err){businessSaveFailure=true;saveFailure=true;saveIndicator('error');throw Error(T('บันทึกไม่สำเร็จ ข้อมูลยังอยู่ในหน้านี้ ส่งออกสำรองก่อนปิด','Save failed. Your work remains in this page; export a backup before closing.'))}}
function capture(){if($('#main'))$$('#main input,#main textarea,#main select').forEach(e=>{if(e.id&&e.type!=='file')drafts[page+':'+e.id]=e.type==='checkbox'?e.checked:e.value})}
function restore(){Object.entries(drafts).filter(([k])=>k.startsWith(page+':')).forEach(([k,v])=>{const el=document.getElementById(k.slice(page.length+1));if(el){if(el.type==='checkbox')el.checked=v;else el.value=v}})}
function clearDraft(p){Object.keys(drafts).filter(k=>k.startsWith(p+':')).forEach(k=>delete drafts[k])}
const product=id=>state.products.find(p=>p.id===id);
const dimensions=()=>[[T('ปัญหาและการใช้งาน','Problem & use case'),T('ใครมีปัญหาอะไร ใช้ในสถานการณ์ไหน','Who has the problem? In what situation?')],[T('สาธิตได้จริง','Demonstration potential'),T('ระบุวิธีถ่ายหรือผลทดลอง ไม่เดาจากรูป','Describe a shoot or test; do not infer from images')],[T('ราคาและคุณค่า','Price & value'),T('รุ่น ราคา และตัวเทียบที่เงื่อนไขใกล้กัน','Variant, price and comparable alternatives')],[T('รีวิวและร้านค้า','Reviews & seller'),T('คะแนน จำนวนรีวิว และตัวอย่างที่อ่านจริง','Rating, review count and actual review samples')],[T('ผลตอบแทนที่ทราบ','Known commission'),T('อัตราหรือยอด พร้อมเงื่อนไขที่ตรวจแล้ว','Rate or payout with checked eligibility')],[T('อุปสรรคก่อนซื้อ','Purchase friction'),T('คะแนนสูง = เลือกง่าย ข้อจำกัดทราบชัด','Higher = clear compatibility and simpler purchase')],[T('มุมเล่าที่แตกต่าง','Distinct story angle'),T('บอกว่าต่างอย่างไรและมีอะไรพิสูจน์','Describe the difference and supporting evidence')]];
function score(p){let weight=0,total=0,count=0;(p.dims||[]).forEach((d,i)=>{if(d.rating!==null&&Number.isFinite(d.rating)&&d.rating>=0&&d.rating<=5&&d.evidence?.trim()&&d.reason?.trim()){weight+=WEIGHTS[i];total+=WEIGHTS[i]*d.rating/5;count++}});return {coverage:weight,score:weight<60?null:Math.round(100*total/weight),count}}
function stale(p){return !p.observedAt||(Date.now()-Date.parse(p.observedAt))/36e5>state.settings.staleHours}
function formatScore(p){let s=score(p);return s.score===null?'—':s.score}
function navItems(){return [['today',T('วันนี้','Today')],['analyze',T('วิเคราะห์สินค้า','Product intelligence')],['products',T('คลังสินค้า','Selling list')],['studio',T('สร้างเนื้อเรื่อง','Story studio')],['planner',T('แผนงาน','Planner')],['results',T('ผลโพสต์','Results')],['lab',T('ทดลองและคาดการณ์','Experiment lab')],['settings',T('ตั้งค่าและสำรอง','Settings & backup')]]}
function render(){rendering=true;try{document.documentElement.lang=lang;document.body.classList.toggle('reduce',state.settings.reduced);const nav=navItems();$('#nav').innerHTML=nav.map(([k,l])=>`<button data-action="nav" data-page="${k}" class="${page===k?'active':''} ${['today','analyze','studio','planner'].includes(k)?'mobile':''}" ${page===k?'aria-current="page"':''}>${icon(k)}<span>${l}</span>${k==='products'?`<span class="navcount">${state.products.length}</span>`:''}</button>`).join('')+`<button data-action="more" class="mobile ${['products','results','lab','settings'].includes(page)?'active':''}">${icon('more')}<span>${T('เพิ่มเติม','More')}</span></button>`;$('#crumb').textContent='Workspace / '+(nav.find(x=>x[0]===page)?.[1]||'');$('#lang').textContent=lang==='th'?'EN':'ไทย';$('#demo').textContent=mode==='demo'?T('กลับข้อมูลจริง','My workspace'):T('ลองตัวอย่าง','Try demo');$('#mode-badge').innerHTML=badge(T('โหมดในเครื่อง','Local workspace'),'cyan');$('#demo-banner').classList.toggle('hidden',mode!=='demo');$('#demo-banner').textContent=T('โหมดตัวอย่าง • ข้อมูลสมมติ แยกจากข้อมูลจริงของคุณ','DEMO WORKSPACE • Fictional data, isolated from your real records');$('#local-label').textContent=T('เก็บข้อมูลเฉพาะเครื่องนี้','Data stays on this device');$('#nav-label').textContent=T('พื้นที่ทำงาน','WORKSPACE');$('#backup-top').textContent=T('สำรองข้อมูล','Backup');$('#save-status').textContent=db?T('บันทึกในเครื่องอัตโนมัติ','Local autosave'):T('บันทึกไม่ได้ — ส่งออกสำรอง','Storage unavailable — export backup');const views={today:todayView,analyze:analyzeView,products:productsView,studio:studioView,planner:plannerView,results:resultsView,lab:labView,settings:settingsView};$('#main').innerHTML=views[page]();restore();enhanceView();}finally{rendering=false}}
function head(k,title,sub,actions=''){return `<div class="pagehead"><div><div class="eyebrow">${k}</div><h1>${title}</h1>${sub?`<p class="muted">${sub}</p>`:''}</div>${actions}</div>`}
function kpi(label,value,note,color=''){return `<div class="card stat"><span class="muted">${label}</span><div class="value ${color}">${value}</div><span class="sub">${note}</span></div>`}
function paired(rows,a,b,mul=1){const valid=rows.filter(x=>x[a]!==null&&x[a]!==undefined&&x[b]!==null&&x[b]!==undefined);return valid.length?ratio(valid.reduce((n,x)=>n+x[a],0),valid.reduce((n,x)=>n+x[b],0),mul):null}
function total(rows,key){let r=rows.filter(x=>x[key]!==null&&x[key]!==undefined);return r.length?r.reduce((n,x)=>n+x[key],0):null}
function latestRows(window=filter.window,platform=filter.platform){return state.posts.filter(p=>platform==='all'||p.platform===platform).flatMap(p=>{const m=p.metrics.filter(x=>x.window===window).sort((a,b)=>a.observedAt.localeCompare(b.observedAt)).at(-1);return m?[{...m,post:p}]:[]})}
function attributed(rows){return rows.filter(x=>x.attribution==='post')}
