let onlineStatus={shopee:'unknown',ai:'unknown'},onlineVerified={},pendingOnline=null;
function providerBadge(kind){const status=onlineStatus[kind];const label=status==='connected'?uiText('last_request_succeeded'):status==='configured_unverified'?uiText('configured_unverified'):status==='not_configured'?uiText('not_connected'):status==='error'?uiText('connection_failed'):uiText('not_checked');return badge(label,status==='connected'?'green':'orange');}
function onlineStatusHTML(){return `<section class="card"><h2>${uiText('online_services')}</h2><div id="online-services"><div class="task">Shopee ${providerBadge('shopee')}</div><div class="task">AI ${providerBadge('ai')}</div></div><p class="sub">${uiText('sign_in_to_check_status_service_keys_stay_on_the_server')}</p>${btn(uiText('check_service_configuration'),'online-status','ghost')}</section>`;}
async function providerRequest(body){const context=cloudContext();await requireCloud();assertCloudContext(context);const owner=cloudUser.id;const {data,error}=await cloudClient.functions.invoke(CLOUD_CONFIG.functionName,{body});assertCloudContext(context);if(cloudUser?.id!==owner)throw Error(uiText('account_changed_try_again'));if(error){let code;try{code=(await error.context?.json())?.error}catch{}throw Error(code||error.message)}if(data?.error)throw Error(data.error);return data;}
function onlineProductControls(){return `<div class="notice info mb"><div class="actions">${btn(uiText('retrieve_shopee_details'),'online-shopee','cyan')}${btn(uiText('ask_ai_to_review_evidence'),'online-analysis','ghost')}</div><p class="sub mt">${uiText('requires_sign_in_and_configured_services_retrieved_fiel')}</p></div>`;}
function onlineProductInput(){const val=id=>$('#'+id)?.value||'';if(page==='analyze')return {id:selected,title:val('title'),variant:val('variant'),usecase:val('usecase'),price:N(val('price')),observedAt:val('observed'),sourceText:val('sourceText'),dims:WEIGHTS.map((_,i)=>({rating:N(val('dim'+i)),reason:val('reason'+i),evidence:val('ev'+i),source:val('src'+i)}))};return product(storyDraft?.productId||$('#storyProduct')?.value||studioProductId);}
function aiPreview(result){return `<p class="notice">${uiText('ai_suggestions_require_evidence_review_scores_and_ready')}</p>${result.summary?`<p>${esc(result.summary)}</p>${[['strengths',uiText('supported_strengths')],['gaps',uiText('evidence_gaps')],['angles',uiText('content_angles')]].map(([key,label])=>`<h3 class="mt">${label}</h3><ul>${result[key].map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`).join('')}`:`<h3>${esc(result.name)}</h3><p>${esc(result.hookA)}</p>${result.shots.map((s,i)=>`<div class="data-note mt"><strong>${i+1} · ${esc(s.time)}</strong><p>${esc(s.voice)}</p><small>${esc(s.evidence)}</small></div>`).join('')}`}`;}
async function handleOnlineAction(action){if(action==='online-status'){const result=await providerRequest({action:'status'});for(const kind of ['shopee','ai'])onlineStatus[kind]=result[kind]||'unknown';capture();render();return;}
 if(action==='online-shopee'){const url=$('#affiliate')?.value;if(!shopee(url))throw Error(uiText('enter_a_shopee_https_link_first'));const owner=cloudUser?.id,selectedId=selected;try{const data=await providerRequest({action:'shopee',url});onlineStatus.shopee='connected';onlineVerified.shopee=data.verifiedAt;pendingOnline={kind:'shopee',context:cloudContext(),owner,selectedId,url,data};modal(uiText('review_retrieved_product_details'),`<h3>${esc(data.product.title)}</h3><p>${esc(data.product.shop)}</p><p>${uiText('price_range')}: ${money(data.product.priceMin)} – ${money(data.product.priceMax)}</p><p>${uiText('reported_commission_rate')}: ${data.product.commissionRate??'—'}%</p><p class="notice">${uiText('only_empty_fields_will_be_filled_a_price_range_is_not_t')}</p>`,btn(uiText('fill_empty_fields'),'online-apply-shopee','primary'));}catch(e){onlineStatus.shopee=e.message==='SHOPEE_NOT_CONFIGURED'?'not_configured':'error';throw e;}return;}
 if(action==='online-apply-shopee'){const p=pendingOnline;assertCloudContext(p?.context);if(!p||p.owner!==cloudUser?.id||page!=='analyze'||p.selectedId!==selected||$('#affiliate').value!==p.url)throw Error(uiText('draft_changed_retrieve_details_again'));const data=p.data.product;for(const [key,value]of Object.entries({title:data.title,shop:data.shop,canonical:data.canonical,price:data.price,rating:data.rating,imageUrl:data.imageUrl})){const el=$('#'+key);if(el&&!el.value&&value!==null&&value!==undefined)el.value=value}if(!$('#sourceText').value)$('#sourceText').value=[data.source,data.canonical,data.observedAt,uiText('verify_variant_and_conditions_before_use'),data.commissionRate===null?'':uiText('reported_commission_rate_2')+data.commissionRate+'%'].filter(Boolean).join('\n');capture();queueSession();$('#dialog').close();pendingOnline=null;return;}
 if(action==='online-analysis'||action==='online-story'){const p=onlineProductInput();if(!p?.title)throw Error(uiText('enter_or_select_a_product_first'));const brief=page==='studio'?readProfile():state.profile;const request={action:'ai',task:action==='online-story'?'story':'analysis',product:p,brief,language:$('#storyLanguage')?.value||lang,duration:Number($('#duration')?.value)||30,platform:$('#platform')?.value||'TikTok'};const owner=cloudUser?.id;try{const data=await providerRequest(request);onlineStatus.ai='connected';onlineVerified.ai=data.verifiedAt;pendingOnline={kind:request.task,context:cloudContext(),owner,request,data};modal(uiText('review_ai_suggestions'),aiPreview(data.result),request.task==='story'?btn(uiText('create_a_new_draft'),'online-apply-story','primary'):btn(uiText('copy_analysis'),'online-copy-analysis','cyan'));}catch(e){onlineStatus.ai=e.message==='AI_NOT_CONFIGURED'?'not_configured':'error';throw e;}return;}
 if(action==='online-copy-analysis'&&pendingOnline?.kind==='analysis'){assertCloudContext(pendingOnline.context);await copy(JSON.stringify(pendingOnline.data.result,null,2));}
 if(action==='online-apply-story'){const p=pendingOnline;assertCloudContext(p?.context);if(!p||p.kind!=='story'||p.owner!==cloudUser?.id||!product(p.request.product.id))throw Error('Story context changed');syncStory();if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);const base=makeStory(product(p.request.product.id),p.request.brief,0,p.request.duration,p.request.language,p.request.platform);storyDraft={...base,...p.data.result,id:uid(),productId:p.request.product.id,ready:false,reviewed:false,linkChecked:false,revisions:[],ai:{provider:'OpenAI',model:p.data.model,generatedAt:p.data.verifiedAt}};storyDraft.shots=storyDraft.shots.map(shot=>({...shot,evidence:/^E[1-7]$/.test(shot.evidence)?storyDraft.productId.slice(0,6)+'-'+shot.evidence:shot.evidence}));storyDraft.disclosure=storyDraft.disclosure||base.disclosure;storyDraft.shots[0].voice=storyDraft.hookA;sessionStories[storyDraft.id]=structuredClone(storyDraft);clearDraft('studio');page='studio';studioTab='script';initStoryHistory();render();queueSession();syncRoute();$('#dialog').close();pendingOnline=null;}
}
