// Storefront presentation over existing records. No new catalogue or schema.
let storefrontFilter='all';
const storefrontCategories=[
 {id:'mac',label:'Mac',shape:'laptop',match:/\b(mac|macbook|imac)\b/i},
 {id:'iphone',label:'iPhone',shape:'phone',match:/iphone/i},
 {id:'ipad',label:'iPad',shape:'tablet',match:/ipad/i},
 {id:'watch',label:'Apple Watch',shape:'watch',match:/watch|นาฬิกา/i},
 {id:'audio',label:'AirPods',shape:'audio',match:/airpods|audio|headphone|earbud|หูฟัง|ลำโพง/i},
 {id:'airtag',label:'AirTag',shape:'tag',match:/airtag/i},
 {id:'tv',label:'Apple TV 4K',shape:'tv',match:/apple tv|โทรทัศน์/i},
 {id:'home',label:'HomePod',shape:'home',match:/homepod|smart home|บ้านอัจฉริยะ/i},
 {id:'accessories',label:null,shape:'accessories',match:/usb|hub|accessor|case|cable|charger|ขาตั้ง|สาย|เคส|อุปกรณ์/i},
 {id:'gifts',label:null,shape:'gift',match:/gift card|บัตรของขวัญ/i}
];
function categoryName(c){return c.id==='accessories'?uiText('accessories'):c.id==='gifts'?uiText('gift_cards'):c.label;}
function categoryMatches(p,id){if(id==='all'||id==='latest')return true;if(id==='tvhome')return categoryMatches(p,'tv')||categoryMatches(p,'home');const c=storefrontCategories.find(c=>c.id===id);return !!c&&c.match.test([p.title,p.variant,p.usecase].join(' '));}
function categoryArtwork(shape){const shapes={
 laptop:'<rect x="18" y="14" width="84" height="53" rx="5" fill="#172b45" stroke="#92a6c0"/><path d="M23 20h74v41H23z" fill="#0b1424"/><path d="m25 58 28-26 20 19 22-26v34z" fill="#3275c5"/><path d="M8 70h104l-8 7H17z" fill="#8796ac"/><path d="M48 70h24l-3 3H51z" fill="#35465e"/>',
 phone:'<rect x="40" y="5" width="40" height="77" rx="9" fill="#748aa6"/><rect x="43" y="8" width="34" height="71" rx="7" fill="#142946"/><path d="M44 68c15-43 17-39 32-44v48H44" fill="#4280cc"/><rect x="53" y="11" width="14" height="4" rx="2" fill="#080c13"/>',
 tablet:'<rect x="29" y="8" width="62" height="74" rx="7" fill="#8291a7"/><rect x="32" y="11" width="56" height="68" rx="5" fill="#16365a"/><path d="M35 73c3-36 44-40 50-55v55z" fill="#347fbb"/>',
 watch:'<rect x="46" y="1" width="28" height="88" rx="11" fill="#34485c"/><rect x="35" y="21" width="50" height="51" rx="14" fill="#bac4ce"/><rect x="39" y="25" width="42" height="43" rx="11" fill="#0b1725"/><circle cx="60" cy="46" r="16" fill="none" stroke="#589fff" stroke-width="2"/><path d="M60 34v13l9 6" fill="none" stroke="#ecf4ff" stroke-width="2"/><rect x="85" y="37" width="4" height="12" rx="2" fill="#8496a9"/>',
 audio:'<rect x="25" y="40" width="70" height="43" rx="17" fill="#d3deeb"/><path d="M27 52h66" stroke="#9eafc3"/><circle cx="60" cy="69" r="2" fill="#70839e"/><path d="M34 8c-12 0-14 21-2 23h9v15h8V20c0-8-7-12-15-12m52 0c12 0 14 21 2 23h-9v15h-8V20c0-8 7-12 15-12" fill="#e4ecf6"/><path d="M30 17v7m60-7v7" stroke="#7a8ea5" stroke-width="4" stroke-linecap="round"/>',
 tag:'<circle cx="60" cy="46" r="30" fill="#c2cedd" stroke="#eef4fc" stroke-width="3"/><circle cx="60" cy="46" r="23" fill="#74879e"/><circle cx="60" cy="46" r="10" fill="#a9b8c9"/>',
 tv:'<rect x="18" y="25" width="70" height="52" rx="13" fill="#324052" stroke="#718195"/><rect x="29" y="31" width="47" height="30" rx="8" fill="#253448"/><rect x="93" y="8" width="15" height="72" rx="6" fill="#a1adbd"/><circle cx="100.5" cy="23" r="5" fill="#24354b"/><circle cx="100.5" cy="38" r="2" fill="#465971"/>',
 home:'<rect x="29" y="17" width="62" height="64" rx="29" fill="#a5b4c6"/><path d="M34 41h52M32 48h56M32 55h56M34 62h52M38 69h44" stroke="#697e96" stroke-width="2"/><ellipse cx="60" cy="29" rx="22" ry="11" fill="#142a45"/><ellipse cx="60" cy="28" rx="12" ry="5" fill="#679df1"/>',
 accessories:'<rect x="16" y="34" width="75" height="27" rx="7" fill="#9baabd"/><path d="M89 45h13q10 0 10-13V17" fill="none" stroke="#a2b6ce" stroke-width="5"/><path d="M27 42v10m12-10v10m12-10v10" stroke="#34465e" stroke-width="5"/><rect x="106" y="9" width="12" height="11" rx="2" fill="#d1dae6"/>',
 gift:'<rect x="18" y="19" width="84" height="54" rx="9" fill="#1f406b" stroke="#7197c8"/><path d="M18 37h84M61 19v54" stroke="#9ec6fc" stroke-width="4"/><path d="M60 36q-26-27-22-4 2 9 22 4m1 0q26-27 22-4-2 9-22 4" fill="none" stroke="#9ec6fc" stroke-width="3"/>'};
 return `<svg viewBox="0 0 120 90" aria-hidden="true" focusable="false">${shapes[shape]||shapes.accessories}</svg>`;
}
function heroArtwork(){return `<svg viewBox="0 0 760 550" class="hero-devices" aria-hidden="true" focusable="false">
<defs><radialGradient id="hero-halo"><stop stop-color="#2768b2" stop-opacity=".44"/><stop offset="1" stop-color="#09111c" stop-opacity="0"/></radialGradient><linearGradient id="hero-metal" x2=".7" y2="1"><stop stop-color="#c5d1df"/><stop offset=".25" stop-color="#5b6b84"/><stop offset=".6" stop-color="#202d41"/><stop offset="1" stop-color="#9caec5"/></linearGradient><linearGradient id="hero-screen" x2=".8" y2="1"><stop stop-color="#0a1c3b"/><stop offset=".5" stop-color="#123b70"/><stop offset="1" stop-color="#060e20"/></linearGradient><linearGradient id="hero-wave" x2=".3" y2="1"><stop stop-color="#94d9ff"/><stop offset=".3" stop-color="#4080d6"/><stop offset="1" stop-color="#14253f"/></linearGradient><linearGradient id="hero-white" x2=".8" y2="1"><stop stop-color="#f4f7fa"/><stop offset=".6" stop-color="#bacce3"/><stop offset="1" stop-color="#5e7799"/></linearGradient><filter id="hero-shadow"><feGaussianBlur stdDeviation="16"/></filter></defs>
<ellipse cx="421" cy="280" rx="330" ry="265" fill="url(#hero-halo)"/><ellipse cx="399" cy="462" rx="285" ry="29" fill="#2b5895" opacity=".22" filter="url(#hero-shadow)"/>
<g transform="translate(65 55) rotate(-8 300 210)"><rect x="100" y="30" width="390" height="265" rx="15" fill="url(#hero-metal)" stroke="#8d9db5"/><rect x="108" y="38" width="374" height="247" rx="10" fill="#070d15"/><rect x="118" y="49" width="354" height="224" rx="3" fill="url(#hero-screen)"/><path d="M118 238C201 256 205 81 315 66s88 158 157 135v72H118" fill="url(#hero-wave)" opacity=".95"/><path d="M118 242C233 252 212 111 313 90s99 174 159 121" fill="none" stroke="#abdcff" stroke-width="2" opacity=".55"/><path d="M100 295h390l75 41q-226 25-523 0z" fill="url(#hero-metal)"/><path d="m123 300 344 0 31 19H86z" fill="#152237"/><path d="M206 327h141l18 13H193z" fill="#8295ad" opacity=".6"/><path d="M42 336q300 15 523 0l-6 7q-271 19-510 0z" fill="#8093aa"/></g>
<g transform="translate(472 168) rotate(12 74 131)"><rect width="146" height="276" rx="28" fill="url(#hero-metal)" stroke="#b4c3d4" stroke-width="2"/><rect x="6" y="6" width="134" height="264" rx="24" fill="#070d17"/><rect x="11" y="11" width="124" height="254" rx="20" fill="url(#hero-screen)"/><path d="M12 214c73 34 46-164 122-178v215q-2 14-19 14H32q-20 0-20-18z" fill="url(#hero-wave)"/><path d="M13 215c60 40 45-137 120-158" fill="none" stroke="#a9dfff" stroke-width="2"/><rect x="48" y="17" width="50" height="13" rx="7" fill="#050911"/><path d="M-3 72v35m153-4v39" stroke="#879bb8" stroke-width="3" stroke-linecap="round"/></g>
<g transform="translate(605 285) rotate(18 38 85)"><rect x="17" y="0" width="43" height="176" rx="15" fill="#43576f"/><path d="M24 7h29M24 17h29M24 154h29M24 164h29" stroke="#7b8ea7"/><rect x="0" y="45" width="79" height="89" rx="24" fill="url(#hero-metal)" stroke="#b5c4d7"/><rect x="6" y="51" width="67" height="77" rx="20" fill="#080f1b"/><circle cx="39" cy="89" r="25" fill="none" stroke="#64a5f6" stroke-width="4"/><path d="M39 72v17l13 8" fill="none" stroke="#ecf4ff" stroke-width="3" stroke-linecap="round"/><rect x="79" y="66" width="7" height="16" rx="3" fill="#99b0cc"/></g>
<g transform="translate(135 358) rotate(-9)"><rect width="142" height="92" rx="31" fill="url(#hero-white)"/><path d="M3 29h136" stroke="#7d94b2"/><rect x="65" y="59" width="11" height="3" rx="1.5" fill="#789e91"/><path d="M31-43C10-45 3-9 26-8h13v29h12v-43c0-14-8-19-20-21m77 0c21-2 28 34 5 35h-13v29H88v-43c0-14 8-19 20-21" fill="url(#hero-white)"/><path d="M21-30v10m95-10v10" stroke="#40546b" stroke-width="6" stroke-linecap="round"/></g>
<path d="M75 474q316 22 604-2" fill="none" stroke="#7798c5" stroke-opacity=".2"/>
</svg>`;}
function storefrontProducts(){const products=state.products.filter(p=>categoryMatches(p,storefrontFilter));return products.slice().sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')));}
function storefrontCard(p){const image=safeImage(p.imageUrl),coverage=score(p).coverage;return `<article class="showcase-card reveal"><div class="showcase-top">${badge(uiText('saved'),'blue')}<span>${coverage}% ${uiText('evidence_2')}</span></div><button class="showcase-image" data-action="edit-product" data-id="${esc(p.id)}" aria-label="${esc(uiText('view_product')+p.title)}">${image?`<img src="${esc(image)}" alt="${esc(p.title)}" loading="lazy" decoding="async" width="400" height="320">`:`<div class="no-photo">${icon('products')}<span>${uiText('no_product_image_yet')}</span></div>`}</button><div class="showcase-copy"><h3>${esc(p.title)}</h3><p>${esc(p.usecase||p.variant||uiText('add_details_to_start_a_story'))}</p><div class="showcase-price"><strong>${p.price===null||p.price===undefined?uiText('price_not_recorded'):money(p.price)}</strong><small>${esc(p.variant||'')}</small></div><div class="showcase-actions">${btn(uiText('view_details'),'edit-product','ghost small',`data-id="${esc(p.id)}"`)}${btn(uiText('create_story')+' <span aria-hidden="true">↗</span>','product-story','small',`data-id="${esc(p.id)}"`)}</div></div></article>`;}
function storefrontHero(){return `<section class="store-hero"><div class="hero-copy reveal"><span class="eyebrow">${uiText('your_creator_workspace')}</span><h1>${uiText('your_store_your_next_story')}</h1><p>${uiText('discover_products_shape_better_stories_and_turn_ideas_i')}</p><div class="hero-actions">${btn(uiText('explore_products')+' <span aria-hidden="true">↗</span>','explore-products','primary')}${btn(uiText('view_all_saved'),'nav','hero-secondary','data-page="products"')}</div><div class="hero-footnote"><span class="localdot"></span>${uiText('your_workspace_create_from_real_evidence')}</div></div><div class="hero-visual">${heroArtwork()}<div class="hero-caption"><span class="mini-spark" aria-hidden="true">✦</span><span>${uiText('every_idea_starts_with_your_next_find')}</span></div></div></section>`;}
function categoryStrip(){return `<section class="category-section reveal" aria-label="${uiText('product_categories')}"><div class="category-strip">${storefrontCategories.map(c=>`<button class="category-tile" data-action="store-category" data-category="${c.id}" aria-pressed="${storefrontFilter===c.id}"><span class="category-picture">${categoryArtwork(c.shape)}</span><span>${esc(categoryName(c))}</span></button>`).join('')}</div></section>`;}
function storefrontCollection(){const products=storefrontProducts(),chips=[['all',uiText('all')],['latest',uiText('latest')],['mac','Mac'],['iphone','iPhone'],['ipad','iPad'],['watch','Watch'],['audio',uiText('audio')],['home',uiText('smart_home')],['accessories',uiText('accessories')]];return `<section id="store-collection" class="store-section"><div class="store-section-head"><div><span class="eyebrow">${uiText('curated_by_you')}</span><h2>${uiText('latest_products_your_next_inspiration')}</h2><p>${uiText('your_saved_products_ready_to_become_your_next_story')}</p></div>${btn(uiText('view_all')+' <span aria-hidden="true">↗</span>','nav','text-link','data-page="products"')}</div><div class="collection-controls"><div class="filter-chips" aria-label="${uiText('filter_products')}">${chips.map(([id,label])=>`<button data-action="store-category" data-category="${id}" aria-pressed="${storefrontFilter===id}">${label}</button>`).join('')}</div>${btn(icon('analyze')+`<span>${uiText('search_saved')}</span>`,'store-search','collection-search')}</div><div id="showcase-grid" class="showcase-grid">${products.slice(0,storefrontFilter==='latest'?4:8).map(storefrontCard).join('')}</div>${products.length?'':`<div class="store-empty">${icon('products')}<h3>${state.products.length?uiText('no_saved_products_in_this_category'):uiText('a_space_for_your_next_discovery')}</h3><p>${state.products.length?uiText('choose_another_category_or_add_a_product_to_your_collec'):uiText('save_a_product_link_image_and_evidence_to_start_your_st')}</p>${btn(uiText('add_product'),'new-product','primary')}${!state.products.length?btn(uiText('explore_the_demo'),'demo','ghost'):btn(uiText('show_all_products'),'store-category','ghost','data-category="all"')}</div>`}</section>`;}
function storefrontEditorial(){return `<section class="editorial-banner reveal"><div class="editorial-copy"><span class="eyebrow">${uiText('stories_worth_hearing')}</span><h2>${uiText('better_sound_for_every_moment')}</h2><p>${uiText('explore_the_audio_products_you_saved_build_a_story_arou')}</p>${btn(uiText('explore_audio')+' <span aria-hidden="true">↗</span>','store-category','primary','data-category="audio"')}</div><div class="audio-art">${categoryArtwork('audio')}<span class="sound-ring ring-one"></span><span class="sound-ring ring-two"></span></div></section><section class="editorial-panels"><article class="editorial-panel reveal"><div><span class="eyebrow">${uiText('from_idea_to_shoot')}</span><h2>${uiText('more_than_a_device_a_new_way_to_create')}</h2>${btn(uiText('open_story_studio_2')+' <span aria-hidden="true">↗</span>','nav','text-link','data-page="studio"')}</div><div class="panel-art">${categoryArtwork('tablet')}</div></article><article class="editorial-panel reveal"><div><span class="eyebrow">${uiText('create_with_intention')}</span><h2>${uiText('small_ideas_real_possibilities')}</h2>${btn(uiText('plan_your_next_story')+' <span aria-hidden="true">↗</span>','nav','text-link','data-page="planner"')}</div><div class="panel-art">${categoryArtwork('watch')}</div></article></section>`;}
function todayView(){return storefrontHero()+categoryStrip()+storefrontCollection()+storefrontEditorial()+`<section class="creator-workspace store-section"><div class="store-section-head"><div><span class="eyebrow">${uiText('make_it_happen')}</span><h2>${uiText('your_creative_workspace')}</h2></div>${btn(uiText('add_product'),'new-product','ghost')}</div><div id="home-recovery"></div>${workspaceOverview()}</section>`;}
function renderStoreChrome(){$('.skip-link').textContent=uiText('skip_content');document.body.dataset.page=page;$('#language-switch').setAttribute('aria-label',uiText('choose_language'));$$('[data-action="lang"]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.lang===lang));b.title=b.dataset.lang==='th'?'ภาษาไทย':'English';b.classList.toggle('active',b.dataset.lang===lang)});$('#store-nav').innerHTML=[['all',uiText('store')],['mac','Mac'],['ipad','iPad'],['iphone','iPhone'],['watch','Watch'],['audio','AirPods'],['tvhome',uiText('tv_home')],['accessories',uiText('accessories')]].map(([id,label])=>btn(label,'store-category',page==='today'&&storefrontFilter===id?'selected':'',`data-category="${id}"`)).join('');$('#brand-home').setAttribute('aria-label',uiText('sp_affiliate_home'));$('#store-search').setAttribute('aria-label',uiText('search_products'));$('#saved-bag').setAttribute('aria-label',uiText('saved_product_collection'));$('#saved-count').textContent=state.products.length;$('#menu-toggle').setAttribute('aria-label',uiText('open_workspace_menu'));$('#nav').setAttribute('aria-label',uiText('workspace_navigation'));$('#footer-tagline').textContent=uiText('thoughtful_finds_stories_only_you_can_tell');$('#workspace-status').innerHTML=badge(mode==='demo'?uiText('demo_data'):cloudUser?uiText('personal_account'):uiText('local_workspace_3'),'blue');}
function openWorkspaceMenu(){const d=$('#workspace-drawer');d.innerHTML=`<div class="section-title"><h2 id="workspace-menu-title">${uiText('your_workspace')}</h2>${btn('×','close-menu','icon-button',`aria-label="${uiText('close_menu')}"`)}</div><nav aria-label="${uiText('mobile_navigation')}">${navItems().map(([id,label])=>btn(icon(id)+`<span>${label}</span>`,'nav',page===id?'active':'',`data-page="${id}"`)).join('')}</nav><div class="drawer-footer">${btn(mode==='demo'?uiText('my_workspace'):uiText('try_demo'),'demo','ghost')}${btn(uiText('export_backup'),'export','ghost')}</div>`;d.setAttribute('aria-labelledby','workspace-menu-title');d.showModal();$('#menu-toggle').setAttribute('aria-expanded','true');}
let revealObserver;
function enhanceStorefront(){renderStoreChrome();revealObserver?.disconnect();if(!('IntersectionObserver' in window)||matchMedia('(prefers-reduced-motion: reduce)').matches||state.settings.reduced)return;revealObserver=new IntersectionObserver(items=>items.forEach(item=>{if(item.isIntersecting){item.target.classList.add('is-visible');revealObserver.unobserve(item.target)}}),{threshold:.08});$$('.reveal').forEach(el=>{el.classList.add('will-reveal');revealObserver.observe(el)});}
async function handleStoreAction(action,button){if(action==='workspace-menu'){openWorkspaceMenu();return true}if(action==='close-menu'){$('#workspace-drawer').close();return true}if(action==='store-search'){await navigateTo('products');$('#productSearch')?.focus();return true}if(action==='explore-products'){document.getElementById('store-collection')?.scrollIntoView({behavior:state.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});return true}if(action==='store-category'){const focusScope=button.closest('#store-nav')?'#store-nav':button.closest('.category-strip')?'.category-strip':button.closest('.filter-chips')?'.filter-chips':button.closest('.editorial-banner')?'.editorial-banner':'.store-empty';storefrontFilter=storefrontCategories.some(c=>c.id===button.dataset.category)||['all','latest','tvhome'].includes(button.dataset.category)?button.dataset.category:'all';if(page!=='today')await navigateTo('today');else{capture();render()}$(focusScope+' [data-action="store-category"][data-category="'+storefrontFilter+'"]')?.focus({preventScroll:true});$('#store-collection')?.scrollIntoView({behavior:state.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});return true}return false;}
window.addEventListener('scroll',()=>document.body.classList.toggle('scrolled',scrollY>20),{passive:true});
