// Presentation over real workspace records; no demonstration data is inserted here.
let storefrontFilter='all', storefrontSort='newest';
let focusBackground=(()=>{try{return localStorage.getItem('aff-focus-background')==='true'}catch{return false}})();
const categoryKeys=['tech','fashion','beauty','home','health','baby','books','food','pets','sport','auto','other'];
function productCategoryId(p){return p.category?.trim()?'custom:'+p.category.trim():'uncategorized';}
function productCategoryName(p){return p.category?.trim()||uiText('uncategorized');}
function catalogueCategories(){const groups=new Map();for(const p of state.products){const id=productCategoryId(p);if(!groups.has(id))groups.set(id,{id,label:productCategoryName(p),count:0});groups.get(id).count++}return [...groups.values()].sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label));}
function categoryMatches(p,id){return ['all','latest'].includes(id)||productCategoryId(p)===id;}
function productMetadataFields(p){const suggestions=[...new Set([...categoryKeys.map(k=>uiText('category_'+k)),...state.products.map(p=>p.category).filter(Boolean)])];return `${field('category',uiText('category_label'),p.category||'','text','maxlength="120" list="category-suggestions" aria-describedby="category-help"')}<datalist id="category-suggestions">${suggestions.map(s=>`<option value="${esc(s)}"></option>`).join('')}</datalist>${field('brand',uiText('brand_label'),p.brand||'','text','maxlength="120"')}${field('tags',uiText('tags_label'),p.tags||'','text','maxlength="500"')}<p class="sub metadata-help" id="category-help">${uiText('category_hint')}</p>`;}
function storefrontProducts(){
 const products=state.products.filter(p=>categoryMatches(p,storefrontFilter)).slice();
 const recent=(a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||''));
 const numeric=(a,b,key,descending=false)=>{const av=a[key],bv=b[key];if(av==null&&bv==null)return recent(a,b);if(av==null)return 1;if(bv==null)return -1;return (descending?bv-av:av-bv)||recent(a,b)};
 return products.sort((a,b)=>storefrontSort==='price'?numeric(a,b,'price'):storefrontSort==='commission'?numeric(a,b,'commission',true):storefrontSort==='evidence'?score(b).coverage-score(a).coverage||recent(a,b):recent(a,b));
}
function storefrontCard(p){const image=safeImage(p.imageUrl),coverage=score(p).coverage;return `<article class="showcase-card"><div class="showcase-top">${badge(productCategoryName(p),'violet')}<span>${coverage}% ${uiText('evidence_2')}</span></div><button class="showcase-image" data-action="edit-product" data-id="${esc(p.id)}" aria-label="${esc(uiText('view_product')+p.title)}">${image?`<img src="${esc(image)}" alt="${esc(p.title)}" loading="lazy" decoding="async" width="400" height="320" referrerpolicy="no-referrer">`:`<div class="no-photo">${icon('products')}<span>${uiText('no_product_image_yet')}</span></div>`}</button><div class="showcase-copy"><h3>${esc(p.title)}</h3><p>${esc(p.brand||p.usecase||p.variant||uiText('add_details_to_start_a_story'))}</p>${p.rating!=null?`<div class="showcase-rating">${icon('star')}<span>${num(p.rating)}${p.reviews!=null?' · '+num(p.reviews):''}</span><span class="sr-only">${uiText('commerce_rating')}</span></div>`:''}<div class="showcase-price"><strong>${p.price==null?uiText('price_not_recorded'):money(p.price)}</strong><small>${uiText('commerce_commission')} <b>${money(p.commission)}</b></small></div><div class="showcase-actions">${btn(uiText('select_product')+icon('arrow'),'product-story','small',`data-id="${esc(p.id)}"`)}${btn(icon('copy'),'copy-link','ghost small',`data-id="${esc(p.id)}" aria-label="${esc(uiText('copy_link')+' · '+p.title)}" title="${uiText('copy_link')}"`)}</div></div></article>`;}
function creatorJourney(){return `<aside class="creator-journey" aria-label="${uiText('studio_workflow')}"><span class="eyebrow">PRODUCT · CONTENT · INCOME</span><h2>${uiText('commerce_flow')}</h2><p>${uiText('commerce_flow_sub')}</p><ol>${[['flow_link','analyze','link'],['flow_product','products','products'],['flow_story','studio','studio']].map(([key,route,glyph],i)=>`<li>${btn(icon(glyph),'nav','journey-action',`data-page="${route}" aria-label="${uiText(key)}"`)}<span>${uiText(key)}</span></li>`).join('')}</ol></aside>`;}
function storefrontHero(){return `<section class="store-hero"><div class="hero-copy"><span class="eyebrow">SP-AFFILIATE <span class="eyebrow-divider">/</span> ${uiText('creator_studio')}</span><h1>${uiText('creator_heading')}</h1><p>${uiText('creator_intro')}</p><div class="hero-link-entry">${icon('link')}<label class="sr-only" for="creator-link">${uiText('original_affiliate_link')}</label><input id="creator-link" type="url" placeholder="https://s.shopee.co.th/…" autocomplete="off">${btn(uiText('start_link')+icon('arrow'),'start-product-link','primary')}</div><p class="hero-link-hint">${uiText('link_hint')}</p><div class="hero-footnote">${badge(uiText('platform_manual'))}<span>${uiText('shopee_ai_online_research')} · ${uiText('not_connected')}</span></div></div>${creatorJourney()}</section>`;}
function categoryStrip(){const categories=catalogueCategories(),chips=[{id:'all',label:uiText('all_categories'),count:state.products.length},...categories];return `<div class="category-rail"><div class="filter-chips" aria-label="${uiText('filter_products')}">${chips.map(c=>`<button data-action="store-category" data-category="${esc(c.id)}" aria-pressed="${storefrontFilter===c.id}">${icon(c.id==='all'?'grid':'products')}<span class="category-name">${esc(c.label)}</span><small>${c.count}</small></button>`).join('')}${!state.products.length?categoryKeys.filter(k=>k!=='other').map(k=>`<span class="category-example">${icon(k)}<span>${uiText('category_'+k)}</span></span>`).join(''):''}</div></div>`;}
function storefrontCollection(){const categories=catalogueCategories();if(!['all','latest',...categories.map(c=>c.id)].includes(storefrontFilter))storefrontFilter='all';const products=storefrontProducts();return `<section id="store-collection" class="store-section"><div class="store-section-head"><div><span class="eyebrow">${uiText('curated_by_you')}</span><h2>${uiText('collection_heading')}</h2><p>${uiText('collection_sub')}</p></div><div class="collection-head-actions">${btn(uiText('view_all')+icon('arrow'),'nav','text-link','data-page="products"')}${btn(icon('products'),'new-product','icon-button',`aria-label="${uiText('add_product')}" title="${uiText('add_product')}"`)}</div></div>${state.products.length?`<div class="collection-controls"><span class="sub">${products.length} ${uiText('products')}</span><div class="collection-sort"><label class="sr-only" for="store-sort">${uiText('commerce_sort')}</label><select id="store-sort">${['newest','evidence','commission','price'].map(k=>`<option value="${k}" ${storefrontSort===k?'selected':''}>${uiText('sort_'+k)}</option>`).join('')}</select>${btn(icon('analyze'),'store-search','icon-button',`aria-label="${uiText('search_saved')}"`)}</div></div>`:''}<div id="showcase-grid" class="showcase-grid">${products.slice(0,10).map(storefrontCard).join('')}</div>${products.length?'':`<div class="store-empty"><div class="empty-emblem">${icon('products')}</div><div><h3>${uiText('empty_catalogue_title')}</h3><p>${uiText('empty_catalogue_body')}</p></div><div class="empty-actions">${btn(uiText('add_product'),'new-product','primary')}${btn(uiText('explore_the_demo'),'demo','ghost')}</div></div>`}</section>`;}
function recentStories(){const stories=state.stories.slice().sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||''))).slice(0,3);return `<section class="recent-stories"><div class="store-section-head"><div><span class="eyebrow">STORY STUDIO</span><h2>${uiText('studio_recent')}</h2></div>${btn(uiText('studio_open')+' ↗','nav','text-link','data-page="studio"')}</div>${stories.length?`<div class="recent-list">${stories.map((s,i)=>`<button class="recent-story" data-action="open-story" data-id="${esc(s.id)}"><span class="recent-index">0${i+1}</span><span class="recent-copy"><strong>${esc(s.name)}</strong><small>${esc(product(s.productId)?.title||'')} · ${esc(s.platform)} · ${s.duration}s</small></span><span class="recent-arrow" aria-hidden="true">↗</span></button>`).join('')}</div>`:`<div class="recent-empty">${icon('studio')}<div><h3>${uiText('studio_recent_empty')}</h3><p>${uiText('studio_recent_hint')}</p></div>${btn(uiText('create_story'),'nav','ghost','data-page="studio"')}</div>`}</section>`;}
function commerceInsights(){const rows=latestRows('72h','all'),a=attributed(rows),due=state.plans.flatMap(p=>p.tasks).filter(t=>t.status!=='done'&&t.date<=today());return `<aside class="commerce-insights"><section class="insight-card"><div class="insight-title">${icon('check')}<h2>${uiText('commerce_tasks')}</h2>${btn(icon('arrow'),'nav','icon-button',`data-page="planner" aria-label="${uiText('open_planner')}"`)}</div>${due.length?`<strong class="due-total">${due.length} <small>${uiText('commerce_pending_tasks')}</small></strong><p>${uiText('check_dependencies_before_starting')}</p>${btn(uiText('open_planner'),'nav','small','data-page="planner"')}`:`<h3>${uiText('commerce_no_tasks')}</h3><p>${uiText('commerce_no_tasks_sub')}</p><div class="insight-next">${btn(icon('products')+uiText('add_product'),'new-product','ghost small')}${btn(icon('studio')+uiText('create_story'),'nav','ghost small','data-page="studio"')}</div>`}</section><section class="insight-card"><div class="insight-title">${icon('results')}<h2>${uiText('commerce_income')}</h2></div><span class="insight-window">${uiText('commerce_window')}</span><div class="income-value">${money(total(a,'confirmed'))}</div><p>${uiText('post_attributed_only_72h')}</p><div class="insight-metrics"><div><span>${uiText('clicks')}</span><strong>${num(total(rows,'clicks'))}</strong></div><div><span>${uiText('orders')}</span><strong>${num(total(rows,'orders'))}</strong></div></div>${!rows.length?`<p class="insight-note">${uiText('commerce_no_metrics')}</p>`:''}${btn(uiText('log_results')+icon('arrow'),'nav','text-link','data-page="results"')}</section></aside>`;}
function commerceTools(){return `<section class="commerce-tools">${[['studio','story_studio','commerce_studio_sub'],['planner','planner','commerce_plan_sub'],['results','results','commerce_results_sub']].map(([route,key,sub])=>btn(`<span class="tool-icon">${icon(route)}</span><span><strong>${uiText(key)}</strong><small>${uiText(sub)}</small></span>${icon('arrow')}`,'nav','commerce-tool',`data-page="${route}"`)).join('')}</section>`;}
function todayView(){return storefrontHero()+`<div id="home-recovery"></div>`+categoryStrip()+`<div class="commerce-layout">${storefrontCollection()}${commerceInsights()}${commerceTools()}</div>`+recentStories()+`<details class="workspace-details"><summary>${uiText('commerce_details')}</summary><section class="creator-workspace store-section"><div class="store-section-head"><h2>${uiText('workspace_today')}</h2></div>${workspaceOverview()}</section></details>`;}

function renderStoreChrome(){document.body.classList.toggle('focus-background',focusBackground);$('#appearance-toggle').innerHTML=icon('sun');$('#appearance-toggle').setAttribute('aria-label',uiText('focus_background'));$('#appearance-toggle').setAttribute('aria-pressed',String(focusBackground));$('#global-query').placeholder=uiText('global_search');$('#global-query').setAttribute('aria-label',uiText('global_search'));$('#global-search-button').innerHTML=icon('analyze');$('#global-search-button').setAttribute('aria-label',uiText('search_products'));$('#rail-title').textContent=uiText('commerce_local_title');$('#rail-description').textContent=uiText('commerce_local_sub');$('.skip-link').textContent=uiText('skip_content');document.body.dataset.page=page;$('#language-switch').setAttribute('aria-label',uiText('choose_language'));$$('[data-action="lang"]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.lang===lang));b.title=b.dataset.lang==='th'?'ภาษาไทย':'English';b.classList.toggle('active',b.dataset.lang===lang)});$('#store-nav').innerHTML=`<span>${uiText('creator_studio')}</span><span class="context-slash">/</span><strong>${navItems().find(([id])=>id===page)?.[1]||''}</strong>`;$('#brand-home').setAttribute('aria-label',uiText('sp_affiliate_home'));$('#store-search').setAttribute('aria-label',uiText('search_products'));$('#saved-bag').setAttribute('aria-label',uiText('saved_product_collection'));$('#saved-count').textContent=state.products.length;$('#menu-toggle').setAttribute('aria-label',uiText('open_workspace_menu'));$('#nav').setAttribute('aria-label',uiText('workspace_navigation'));$('#footer-tagline').textContent=uiText('thoughtful_finds_stories_only_you_can_tell');$('#workspace-status').innerHTML=badge(mode==='demo'?uiText('demo_data'):cloudUser?uiText('personal_account'):uiText('local_workspace_3'),'blue');$('#mobile-nav').setAttribute('aria-label',uiText('mobile_navigation'));$('#mobile-nav').innerHTML=['today','products','studio'].map(id=>btn(icon(id)+`<span>${navItems().find(([k])=>k===id)[1]}</span>`,'nav',page===id?'active':'',`data-page="${id}" ${page===id?'aria-current="page"':''}`)).join('')+btn(icon('more')+`<span>${uiText('more')}</span>`,'workspace-menu',['today','products','studio'].includes(page)?'':'active');}
function openWorkspaceMenu(){const d=$('#workspace-drawer');d.innerHTML=`<div class="section-title"><h2 id="workspace-menu-title">${uiText('your_workspace')}</h2>${btn('×','close-menu','icon-button',`aria-label="${uiText('close_menu')}"`)}</div><nav aria-label="${uiText('mobile_navigation')}">${navItems().map(([id,label])=>btn(icon(id)+`<span>${label}</span>`,'nav',page===id?'active':'',`data-page="${id}"`)).join('')}</nav><div class="drawer-footer">${btn(mode==='demo'?uiText('my_workspace'):uiText('try_demo'),'demo','ghost')}${btn(uiText('export_backup'),'export','ghost')}</div>`;d.setAttribute('aria-labelledby','workspace-menu-title');d.showModal();$('#menu-toggle').setAttribute('aria-expanded','true');}
function enhanceStorefront(){renderStoreChrome();}
async function handleStoreAction(action,button){
 if(action==='appearance'){focusBackground=!focusBackground;try{localStorage.setItem('aff-focus-background',String(focusBackground))}catch{}renderStoreChrome();return true}
 if(action==='global-search'){const query=$('#global-query').value.trim();if(/^https?:\/\//i.test(query)){if(!shopee(query)){inlineError('global-query',uiText('use_an_https_shopee_thailand_link'));return true}openProductLink(query);}else{await navigateTo('products');productFilters.query=query;productFilters.category='all';productFilters.status='all';productFilters.evidence='all';clearDraft('products');render();queueSession();$('#productSearch')?.focus();}return true}
 if(action==='workspace-menu'){openWorkspaceMenu();return true}
 if(action==='close-menu'){$('#workspace-drawer').close();return true}
 if(action==='store-search'){await navigateTo('products');$('#productSearch')?.focus();return true}
 if(action==='start-product-link'){const link=$('#creator-link').value.trim();if(link&&!shopee(link)){inlineError('creator-link',uiText('use_an_https_shopee_thailand_link'));return true}openProductLink(link);return true}
 if(action==='explore-products'){$('#store-collection')?.scrollIntoView({block:'start'});return true}
 if(action==='store-category'){storefrontFilter=['all','latest',...catalogueCategories().map(c=>c.id)].includes(button.dataset.category)?button.dataset.category:'all';if(page!=='today')await navigateTo('today');else{capture();render()}$$('.filter-chips [data-action="store-category"]').find(b=>b.dataset.category===storefrontFilter)?.focus({preventScroll:true});return true}return false;
}
window.addEventListener('scroll',()=>document.body.classList.toggle('scrolled',scrollY>20),{passive:true});

function openProductLink(link){syncStory();if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);switchProductDraft(null);const existingLink=String(drafts['analyze:affiliate']||'').trim();const occupied=hasProductDraft(productDrafts._new)&&existingLink&&link&&existingLink!==link;if(link&&!occupied){drafts['analyze:affiliate']=link;productStep=0}page='analyze';render();syncRoute();queueSession();$('#affiliate')?.focus();if(occupied)toast(uiText('existing_product_draft'));window.scrollTo(0,0);}
