// Presentation over real workspace records; no demonstration data is inserted here.
let storefrontFilter='all', storefrontSort='newest', storefrontQuery='', storefrontStatus='all', storefrontLayout='grid', commerceWindow='72h';
let focusBackground=(()=>{try{return localStorage.getItem('aff-focus-background')==='true'}catch{return false}})();
const categoryKeys=['fashion','beauty','home','tech','food','health','baby','pets','books','sport','auto','other'];
function productCategoryId(p){return p.category?.trim()?'custom:'+p.category.trim():'uncategorized';}
function productCategoryName(p){return p.category?.trim()||uiText('uncategorized');}
function catalogueCategories(){const groups=new Map();for(const p of state.products){const id=productCategoryId(p);if(!groups.has(id))groups.set(id,{id,label:productCategoryName(p),count:0});groups.get(id).count++}return [...groups.values()].sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label));}
function categoryMatches(p,id){return ['all','latest'].includes(id)||productCategoryId(p)===id;}
function productMetadataFields(p){const suggestions=[...new Set([...categoryKeys.map(k=>uiText('category_'+k)),...state.products.map(p=>p.category).filter(Boolean)])];return `${field('category',uiText('category_label'),p.category||'','text','maxlength="120" list="category-suggestions" aria-describedby="category-help"')}<datalist id="category-suggestions">${suggestions.map(s=>`<option value="${esc(s)}"></option>`).join('')}</datalist>${field('brand',uiText('brand_label'),p.brand||'','text','maxlength="120"')}${field('tags',uiText('tags_label'),p.tags||'','text','maxlength="500"')}<p class="sub metadata-help" id="category-help">${uiText('category_hint')}</p>`;}
function storefrontProducts(){
 const products=state.products.filter(p=>categoryMatches(p,storefrontFilter)&&storefrontMatches(p)).slice();
 const recent=(a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||''));
 const numeric=(a,b,key,descending=false)=>{const av=a[key],bv=b[key];if(av==null&&bv==null)return recent(a,b);if(av==null)return 1;if(bv==null)return -1;return (descending?bv-av:av-bv)||recent(a,b)};
 return products.sort((a,b)=>storefrontSort==='price'?numeric(a,b,'price'):storefrontSort==='commission'?numeric(a,b,'commission',true):storefrontSort==='evidence'?score(b).coverage-score(a).coverage||recent(a,b):recent(a,b));
}
function storefrontCard(p){const image=safeImage(p.imageUrl),coverage=score(p).coverage;return `<article class="showcase-card"><div class="showcase-top">${badge(productCategoryName(p),'violet')}<span>${coverage}% ${uiText('evidence_2')}</span></div><button class="showcase-image" data-action="edit-product" data-id="${esc(p.id)}" aria-label="${esc(uiText('view_product')+p.title)}">${image?`<img src="${esc(image)}" alt="${esc(p.title)}" loading="lazy" decoding="async" width="400" height="320" referrerpolicy="no-referrer">`:`<div class="no-photo">${icon('products')}<span>${uiText('no_product_image_yet')}</span></div>`}</button><div class="showcase-copy"><span class="content-status">${uiText('emerald_status_'+productContentStatus(p))}</span><h3>${esc(p.title)}</h3><p>${esc(p.brand||p.usecase||p.variant||uiText('add_details_to_start_a_story'))}</p>${p.rating!=null?`<div class="showcase-rating">${icon('star')}<span>${num(p.rating)}${p.reviews!=null?' · '+num(p.reviews):''}</span><span class="sr-only">${uiText('commerce_rating')}</span></div>`:''}<div class="showcase-price"><strong>${p.price==null?uiText('price_not_recorded'):money(p.price)}</strong><small>${uiText('commerce_commission')} <b>${money(p.commission)}</b></small></div><small class="product-saved-date">${uiText('emerald_saved')} ${date(p.updatedAt||p.createdAt)}</small><div class="showcase-actions">${btn(uiText('select_product')+icon('arrow'),'product-story','small',`data-id="${esc(p.id)}"`)}${btn(icon('copy'),'copy-link','ghost small',`data-id="${esc(p.id)}" aria-label="${esc(uiText('copy_link')+' · '+p.title)}" title="${uiText('copy_link')}"`)}</div></div></article>`;}
function creatorJourney(){return `<div class="hero-art" aria-hidden="true"><img src="/*__HERO_ASSET__*/" width="560" height="360" alt="" decoding="async"></div>`;}

function storefrontHero(){return `<section class="store-hero"><div class="hero-copy"><span class="eyebrow">SP-AFFILIATE <span class="eyebrow-divider">/</span> AFFILIATE INTELLIGENCE</span><h1>${uiText('creator_heading')}</h1><p>${uiText('creator_intro')}</p></div>${creatorJourney()}<div class="hero-entry"><div class="hero-link-entry">${icon('link')}<label class="sr-only" for="creator-link">${uiText('original_affiliate_link')}</label><input id="creator-link" type="url" placeholder="https://shopee.co.th/…" autocomplete="off">${btn(uiText('start_link')+icon('arrow'),'start-product-link','primary')}</div><p class="hero-link-hint">${uiText('link_hint')}</p><div class="hero-footnote">${badge(uiText('platform_manual'))}<span>${uiText('shopee_ai_online_research')} · ${uiText('not_connected')}</span></div></div></section>`;}

function categoryStrip(){const categories=catalogueCategories(),chips=[{id:'all',label:uiText('all_categories'),count:state.products.length},...categories];return `<section class="category-rail"><div class="category-heading"><h2>${uiText('emerald_choose_category')}</h2>${btn(uiText('view_all')+icon('arrow'),'nav','text-link','data-page="products"')}</div><div class="filter-chips" aria-label="${uiText('filter_products')}">${chips.map(c=>`<button data-action="store-category" data-category="${esc(c.id)}" aria-pressed="${storefrontFilter===c.id}">${icon(c.id==='all'?'grid':'products')}<span class="category-name">${esc(c.label)}</span>${lang==='th'&&c.id==='all'?'<span class="category-sub">All Categories</span>':''}<small>${c.count}</small></button>`).join('')}${!state.products.length?categoryKeys.filter(k=>k!=='other').map(k=>`<span class="category-example">${icon(k)}<span>${uiText('category_short_'+k)}</span>${lang==='th'?`<small class="category-sub">${TRANSLATIONS.en['category_short_'+k]}</small>`:''}</span>`).join(''):''}</div></section>`;}
function storefrontCollection(){const categories=catalogueCategories();if(!['all','latest',...categories.map(c=>c.id)].includes(storefrontFilter))storefrontFilter='all';return `<section id="store-collection" class="store-section"><div class="store-section-head"><div><h2>${uiText('collection_heading')}</h2><p>${uiText('collection_sub')}</p></div><div class="collection-head-actions">${btn(uiText('view_all')+icon('arrow'),'nav','text-link','data-page="products"')}${btn(icon('products'),'new-product','icon-button',`aria-label="${uiText('add_product')}" title="${uiText('add_product')}"`)}</div></div><div class="collection-controls"><div class="collection-search">${icon('analyze')}<label class="sr-only" for="store-query">${uiText('search_saved')}</label><input id="store-query" type="search" placeholder="${uiText('search_saved')}" value="${esc(storefrontQuery)}" autocomplete="off"></div><div class="collection-sort"><label class="sr-only" for="store-sort">${uiText('commerce_sort')}</label><select id="store-sort">${['newest','evidence','commission','price'].map(k=>`<option value="${k}" ${storefrontSort===k?'selected':''}>${uiText('sort_'+k)}</option>`).join('')}</select><div class="view-switch" role="group" aria-label="${uiText('emerald_view')}">${['grid','list'].map(k=>btn(icon(k==='grid'?'grid':'more'),'store-layout','icon-button',`data-layout="${k}" aria-label="${uiText(k==='grid'?'emerald_grid':'list')}" aria-pressed="${storefrontLayout===k}"`)).join('')}</div></div></div><div class="content-filters" role="group" aria-label="${uiText('emerald_content_status')}">${['all','draft','ready','published'].map(k=>btn(`${uiText('emerald_status_'+k)} <span>${state.products.filter(p=>categoryMatches(p,storefrontFilter)&&(k==='all'||productContentStatus(p)===k)).length}</span>`,'store-status','small',`data-status="${k}" aria-pressed="${storefrontStatus===k}"`)).join('')}</div><div id="store-results">${storefrontResults()}</div></section>`;}
function productContentStatus(p){if(state.posts.some(post=>post.productId===p.id))return 'published';const stories=state.stories.filter(story=>story.productId===p.id);return stories.some(story=>story.ready)?'ready':'draft';}
function storefrontMatches(p){const query=storefrontQuery.trim().toLocaleLowerCase();return (storefrontStatus==='all'||productContentStatus(p)===storefrontStatus)&&(!query||[p.title,p.brand,p.category,p.tags,p.variant,p.shop,p.usecase].filter(Boolean).join(' ').toLocaleLowerCase().includes(query));}
function storefrontResults(){const products=storefrontProducts();return `<p class="sr-only" role="status">${products.length} ${uiText('products')}</p><div id="showcase-grid" class="showcase-grid ${storefrontLayout==='list'?'showcase-list':''}">${products.slice(0,10).map(storefrontCard).join('')}</div>${products.length>10?`<p class="collection-overflow">${uiText('emerald_first_ten')} ${btn(uiText('view_all'),'nav','text-link','data-page="products"')}</p>`:''}${products.length?'':state.products.length?`<div class="store-empty filtered-empty"><h3>${uiText('emerald_no_matches')}</h3><p>${uiText('emerald_adjust_filters')}</p>${btn(uiText('emerald_clear_filters'),'store-clear','ghost')}</div>`:`<div class="store-empty"><img class="empty-art" src="/*__EMPTY_ASSET__*/" width="360" height="360" alt="" decoding="async"><div class="empty-copy"><h3>${uiText('empty_catalogue_title')}</h3><p>${uiText('empty_catalogue_body')}</p><div class="empty-actions">${btn(uiText('add_product'),'new-product','primary')}${btn(uiText('explore_the_demo'),'demo','ghost')}</div></div></div>`}`;}
function renderStoreResults(){const el=$('#store-results');if(el)el.innerHTML=storefrontResults();}

function recentStories(){const stories=state.stories.slice().sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||''))).slice(0,3);return `<section class="recent-stories"><div class="store-section-head"><div><span class="eyebrow">STORY STUDIO</span><h2>${uiText('studio_recent')}</h2></div>${btn(uiText('studio_open')+' ↗','nav','text-link','data-page="studio"')}</div>${stories.length?`<div class="recent-list">${stories.map((s,i)=>`<button class="recent-story" data-action="open-story" data-id="${esc(s.id)}"><span class="recent-index">0${i+1}</span><span class="recent-copy"><strong>${esc(s.name)}</strong><small>${esc(product(s.productId)?.title||'')} · ${esc(s.platform)} · ${s.duration}s</small></span><span class="recent-arrow" aria-hidden="true">↗</span></button>`).join('')}</div>`:`<div class="recent-empty">${icon('studio')}<div><h3>${uiText('studio_recent_empty')}</h3><p>${uiText('studio_recent_hint')}</p></div>${btn(uiText('create_story'),'nav','ghost','data-page="studio"')}</div>`}</section>`;}
function commerceInsights(){const tasks=state.plans.flatMap(p=>p.tasks).filter(t=>t.date===today()),done=tasks.filter(t=>t.status==='done').length,rows=latestRows(commerceWindow,'all'),a=attributed(rows);return `<aside class="commerce-insights"><section class="insight-card daily-goals"><div class="insight-title">${icon('check')}<div><h2>${uiText('commerce_tasks')}</h2><time datetime="${today()}">${new Intl.DateTimeFormat(lang==='th'?'th-TH':'en-GB',{dateStyle:'medium',timeZone:'Asia/Bangkok'}).format(new Date())}</time></div>${btn(icon('arrow'),'nav','icon-button',`data-page="planner" aria-label="${uiText('open_planner')}"`)}</div><div class="daily-progress"><div class="ring" style="--v:${tasks.length?done/tasks.length*100:0}" role="meter" aria-label="${uiText('emerald_task_progress')}" aria-valuemin="0" aria-valuemax="${Math.max(1,tasks.length)}" aria-valuenow="${done}" aria-valuetext="${done}/${tasks.length}"><div><strong>${done}<small>/${tasks.length}</small></strong></div></div><div><h3>${tasks.length?uiText('emerald_your_plan'):uiText('commerce_no_tasks')}</h3><p>${tasks.length?uiText('emerald_completed_tasks'):uiText('commerce_no_tasks_sub')}</p></div></div>${tasks.length?`<ul class="daily-checklist">${tasks.slice(0,5).map(t=>`<li class="${t.status==='done'?'is-done':''}">${icon(t.status==='done'?'check':'clock')}<span>${esc(jobNames()[t.type]||t.type)}<small>${esc(state.stories.find(s=>s.id===t.storyId)?.name||'')} · ${esc(t.time)}</small></span></li>`).join('')}</ul>${tasks.length>5?btn(uiText('view_all')+icon('arrow'),'nav','text-link','data-page="planner"'):''}`:`<div class="insight-next">${btn(icon('products')+uiText('add_product'),'new-product','ghost small')}${btn(icon('planner')+uiText('open_planner'),'nav','ghost small','data-page="planner"')}</div>`}</section><section class="insight-card performance-card"><div class="insight-title">${icon('results')}<h2>${uiText('emerald_performance')}</h2><label class="sr-only" for="commerce-window">${uiText('post_age_window')}</label><select id="commerce-window">${['24h','72h','7d'].map(w=>`<option ${commerceWindow===w?'selected':''}>${w}</option>`).join('')}</select></div><p class="metric-basis">${uiText('emerald_metric_basis')}</p><div class="insight-metrics">${[['clicks',num(total(rows,'clicks'))],['confirmed',money(total(a,'confirmed'))],['views',num(total(rows,'views'))]].map(([k,value])=>`<div><span>${uiText(k)}</span><strong>${value}</strong></div>`).join('')}</div>${commerceChart(rows)}${btn(uiText('log_results')+icon('arrow'),'nav','text-link','data-page="results"')}</section>${commerceTools()}</aside>`;}
function commerceSeries(rows){const grouped=new Map();for(const r of rows){if(!Number.isFinite(r.clicks))continue;const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(r.post.publishedAt));grouped.set(day,(grouped.get(day)||0)+r.clicks);}return [...grouped].sort((a,b)=>a[0].localeCompare(b[0]));}
function commerceChart(rows){const points=commerceSeries(rows);if(!points.length)return `<div class="chart-empty">${icon('results')}<p>${uiText('commerce_no_metrics')}</p></div>`;const max=Math.max(1,...points.map(x=>x[1])),plot=points.map(([day,value],i)=>({day,value,x:28+(points.length>1?i/(points.length-1):.5)*244,y:112-value/max*82}));return `<figure class="commerce-chart"><figcaption>${uiText('emerald_chart_caption')}</figcaption><svg viewBox="0 0 300 150" role="img" aria-labelledby="commerce-chart-title"><title id="commerce-chart-title">${uiText('emerald_chart_caption')}</title>${[30,71,112].map(y=>`<line x1="28" y1="${y}" x2="272" y2="${y}" class="chart-grid"/>`).join('')}<text x="0" y="25">${num(max)}</text><text x="12" y="117">0</text>${plot.length>1?`<polyline points="${plot.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" class="chart-line"/>`:''}${plot.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="3" class="chart-dot"><title>${esc(p.day)}: ${num(p.value)}</title></circle>`).join('')}<text x="28" y="142">${esc(plot[0].day.slice(5))}</text>${plot.length>1?`<text x="272" y="142" text-anchor="end">${esc(plot.at(-1).day.slice(5))}</text>`:''}</svg><details><summary>${uiText('emerald_chart_data')}</summary><table><thead><tr><th>${uiText('emerald_post_date')}</th><th>${uiText('clicks')}</th></tr></thead><tbody>${points.map(([day,value])=>`<tr><td>${esc(day)}</td><td>${num(value)}</td></tr>`).join('')}</tbody></table></details></figure>`;}

function commerceTools(){return `<section class="insight-card quick-tools"><div class="insight-title">${icon('lab')}<h2>${uiText('emerald_quick_tools')}</h2></div><div class="commerce-tools">${[['studio','story_studio'],['lab','experiment_lab'],['planner','planner'],['results','results']].map(([route,key])=>btn(`<span class="tool-icon">${icon(route)}</span><span><strong>${uiText(key)}</strong></span>${icon('arrow')}`,'nav','commerce-tool',`data-page="${route}"`)).join('')}</div></section>`;}

function todayView(){return `<div class="dashboard-content"><div class="dashboard-main">${storefrontHero()}<div id="home-recovery"></div>${categoryStrip()}${storefrontCollection()}${recentStories()}</div>${commerceInsights()}</div><details class="workspace-details"><summary>${uiText('commerce_details')}</summary><section class="creator-workspace store-section"><div class="store-section-head"><h2>${uiText('workspace_today')}</h2></div>${workspaceOverview()}</section></details>`;}

function renderStoreChrome(){document.body.classList.toggle('focus-background',focusBackground);$('#appearance-toggle').innerHTML=icon('sun');$('#appearance-toggle').setAttribute('aria-label',uiText('focus_background'));$('#appearance-toggle').setAttribute('aria-pressed',String(focusBackground));$('#global-query').placeholder=uiText('global_search');$('#global-query').setAttribute('aria-label',uiText('global_search'));$('#global-search-button').innerHTML=icon('analyze');$('#global-search-button').setAttribute('aria-label',uiText('search_products'));$('#rail-title').textContent=uiText('commerce_local_title');$('#rail-description').textContent=uiText('commerce_local_sub');$('.skip-link').textContent=uiText('skip_content');document.body.dataset.page=page;$('#language-switch').setAttribute('aria-label',uiText('choose_language'));$$('[data-action="lang"]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.lang===lang));b.title=b.dataset.lang==='th'?'ภาษาไทย':'English';b.classList.toggle('active',b.dataset.lang===lang)});$('#store-nav').innerHTML=`<span>${uiText('creator_studio')}</span><span class="context-slash">/</span><strong>${navItems().find(([id])=>id===page)?.[1]||''}</strong>`;$('#brand-home').setAttribute('aria-label',uiText('sp_affiliate_home'));$('#store-search').setAttribute('aria-label',uiText('search_products'));$('#saved-bag').setAttribute('aria-label',uiText('saved_product_collection'));$('#saved-count').textContent=state.products.length;$('#menu-toggle').setAttribute('aria-label',uiText('open_workspace_menu'));$('#nav').setAttribute('aria-label',uiText('workspace_navigation'));$('#footer-tagline').textContent=uiText('thoughtful_finds_stories_only_you_can_tell');$('#workspace-status').innerHTML=badge(mode==='demo'?uiText('demo_data'):cloudUser?uiText('personal_account'):uiText('local_workspace_3'),'blue');$('#mobile-nav').setAttribute('aria-label',uiText('mobile_navigation'));$('#mobile-nav').innerHTML=['today','products','studio'].map(id=>btn(icon(id)+`<span>${navItems().find(([k])=>k===id)[1]}</span>`,'nav',page===id?'active':'',`data-page="${id}" ${page===id?'aria-current="page"':''}`)).join('')+btn(icon('more')+`<span>${uiText('more')}</span>`,'workspace-menu',['today','products','studio'].includes(page)?'':'active');}
function openWorkspaceMenu(){const d=$('#workspace-drawer');d.innerHTML=`<div class="section-title"><h2 id="workspace-menu-title">${uiText('your_workspace')}</h2>${btn('×','close-menu','icon-button',`aria-label="${uiText('close_menu')}"`)}</div><nav aria-label="${uiText('mobile_navigation')}">${navItems().map(([id,label])=>btn(icon(id)+`<span>${label}</span>`,'nav',page===id?'active':'',`data-page="${id}"`)).join('')}</nav><div class="drawer-footer">${btn(mode==='demo'?uiText('my_workspace'):uiText('try_demo'),'demo','ghost')}${btn(uiText('export_backup'),'export','ghost')}</div>`;d.setAttribute('aria-labelledby','workspace-menu-title');d.showModal();$('#menu-toggle').setAttribute('aria-expanded','true');}
function enhanceStorefront(){renderStoreChrome();}
async function handleStoreAction(action,button){
 if(action==='store-layout'){storefrontLayout=button.dataset.layout==='list'?'list':'grid';capture();render();$('[data-action=store-layout][data-layout='+storefrontLayout+']')?.focus({preventScroll:true});queueSession();return true}
 if(action==='store-status'){storefrontStatus=['all','draft','ready','published'].includes(button.dataset.status)?button.dataset.status:'all';capture();render();$('[data-action=store-status][data-status='+storefrontStatus+']')?.focus({preventScroll:true});queueSession();return true}
 if(action==='store-clear'){storefrontQuery='';storefrontStatus='all';storefrontFilter='all';clearDraft('today');render();queueSession();return true}
 if(action==='appearance'){focusBackground=!focusBackground;try{localStorage.setItem('aff-focus-background',String(focusBackground))}catch{}renderStoreChrome();return true}
 if(action==='global-search'){const query=$('#global-query').value.trim();if(/^https?:\/\//i.test(query)){if(!shopee(query)){inlineError('global-query',uiText('use_an_https_shopee_thailand_link'));return true}openProductLink(query);}else{await navigateTo('products');productFilters.query=query;productFilters.category='all';productFilters.status='all';productFilters.evidence='all';clearDraft('products');render();queueSession();$('#productSearch')?.focus();}return true}
 if(action==='workspace-menu'){openWorkspaceMenu();return true}
 if(action==='close-menu'){$('#workspace-drawer').close();return true}
 if(action==='store-search'){await navigateTo('products');$('#productSearch')?.focus();return true}
 if(action==='start-product-link'){const link=$('#creator-link').value.trim();if(link&&!shopee(link)){inlineError('creator-link',uiText('use_an_https_shopee_thailand_link'));return true}openProductLink(link);return true}
 if(action==='explore-products'){$('#store-collection')?.scrollIntoView({block:'start'});return true}
 if(action==='store-category'){storefrontFilter=['all','latest',...catalogueCategories().map(c=>c.id)].includes(button.dataset.category)?button.dataset.category:'all';if(page!=='today')await navigateTo('today');else{capture();render()}$$('.filter-chips [data-action="store-category"]').find(b=>b.dataset.category===storefrontFilter)?.focus({preventScroll:true});queueSession();return true}return false;
}
window.addEventListener('scroll',()=>document.body.classList.toggle('scrolled',scrollY>20),{passive:true});

function openProductLink(link){syncStory();if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);switchProductDraft(null);const existingLink=String(drafts['analyze:affiliate']||'').trim();const occupied=hasProductDraft(productDrafts._new)&&existingLink&&link&&existingLink!==link;if(link&&!occupied){drafts['analyze:affiliate']=link;productStep=0}page='analyze';render();syncRoute();queueSession();$('#affiliate')?.focus();if(occupied)toast(uiText('existing_product_draft'));window.scrollTo(0,0);}

// Optional presentation state: old version-1 editing sessions need no migration.
function restoreStorefrontSession(s={}){s=s&&typeof s==='object'?s:{};storefrontQuery=typeof s.query==='string'?s.query.slice(0,1000):'';storefrontStatus=['all','draft','ready','published'].includes(s.status)?s.status:'all';storefrontFilter=typeof s.category==='string'?s.category:'all';storefrontSort=['newest','evidence','commission','price'].includes(s.sort)?s.sort:'newest';storefrontLayout=s.layout==='list'?'list':'grid';commerceWindow=['24h','72h','7d'].includes(s.window)?s.window:'72h';}
