const studioTabs=()=>[['brief',uiText('brief')],['angles',uiText('angles')],['script',uiText('script')],['scenes',uiText('scenes')],['review',uiText('review_2')],['history',uiText('versions')]];
let historyTimer,promptFrame=null,promptRunning=false,promptLast=0,promptElapsed=0,promptSpeed=30,promptFont=32,pendingRevision=null;
function studioTabsHTML(){return `<div class="studio-tabs" role="tablist" aria-label="${uiText('story_workflow')}">${studioTabs().map(([id,label])=>`<button role="tab" id="tab-${id}" aria-controls="panel-${id}" aria-selected="${studioTab===id}" data-action="studio-tab" data-tab="${id}" ${!storyDraft&&!['brief','angles'].includes(id)?'disabled':''}>${label}</button>`).join('')}</div>`;}
function applyStudioTab(){if(!storyDraft&&!['brief','angles'].includes(studioTab))studioTab='brief';$$('[data-studio-panel]').forEach(el=>el.hidden=el.dataset.studioPanel!==studioTab);$$('[data-action="studio-tab"]').forEach(b=>{b.setAttribute('aria-selected',b.dataset.tab===studioTab?'true':'false');b.tabIndex=b.dataset.tab===studioTab?0:-1});if(storyDraft)initStoryHistory();updateHistoryControls();}
function storySnapshot(s){const copy=structuredClone(s);delete copy.revisions;delete copy.ready;delete copy.reviewed;delete copy.linkChecked;return copy;}
function initStoryHistory(){if(!storyDraft)return;if(!storyHistories[storyDraft.id])storyHistories[storyDraft.id]={items:[storySnapshot(storyDraft)],index:0};}
function recordStoryHistory(){clearTimeout(historyTimer);if(!storyDraft)return;syncStory();initStoryHistory();const h=storyHistories[storyDraft.id],snap=storySnapshot(storyDraft);if(JSON.stringify(h.items[h.index])===JSON.stringify(snap))return;h.items=h.items.slice(0,h.index+1);h.items.push(snap);if(h.items.length>60)h.items.shift();h.index=h.items.length-1;updateHistoryControls();}
function updateHistoryControls(){const h=storyDraft&&storyHistories[storyDraft.id];$$('[data-action="undo-story"]').forEach(b=>b.disabled=!h||h.index<=0);$$('[data-action="redo-story"]').forEach(b=>b.disabled=!h||h.index>=h.items.length-1);}
function restoreStoryContent(snapshot){const id=storyDraft.id,productId=storyDraft.productId,revisions=storyDraft.revisions;storyDraft={...structuredClone(snapshot),id,productId,revisions,ready:false,reviewed:false,linkChecked:false};clearDraft('studio');render();queueSession();}
function undoStory(direction){recordStoryHistory();const h=storyHistories[storyDraft.id],next=h.index+direction;if(next<0||next>=h.items.length)return;h.index=next;restoreStoryContent(h.items[next]);}
function legacyRevisionSnapshot(r){const s=storySnapshot(storyDraft),text=r.text||'',lines=text.split('\n');s.name=lines[0]||s.name;s.hookA=lines.find(x=>x.startsWith('Hook A: '))?.slice(8)||s.hookA;s.hookB=lines.find(x=>x.startsWith('Hook B: '))?.slice(8)||s.hookB;if(Array.isArray(r.shots)&&r.shots.length===5)s.shots=structuredClone(r.shots);const caption=text.split('\n\nCaption\n')[1];if(caption){const parts=caption.split('\n\nFacebook\n');s.caption=parts[0];if(parts[1]!==undefined)s.facebook=parts[1]}s.shots[0].voice=s.hookA;return s;}
function revisionPreview(id){syncStory();pendingRevision=storyDraft.revisions.find(r=>r.id===id);if(!pendingRevision)return;const snapshot=pendingRevision.snapshot||legacyRevisionSnapshot(pendingRevision);modal(uiText('restore_this_version_as_a_draft'),`<p>${uiText('your_current_content_is_checkpointed_first_review_is_re')}</p><div class="grid cols2"><div class="data-note"><strong>${uiText('current')}</strong><p>${esc(storyDraft.hookA)}</p></div><div class="data-note"><strong>${uiText('selected_version')}</strong><p>${esc(snapshot.hookA)}</p></div></div>${!pendingRevision.snapshot?`<p class="notice mt">${uiText('legacy_revisions_store_text_and_scenes_only_the_current')}</p>`:''}`,btn(uiText('restore_draft'),'confirm-restore-revision','primary'));}
function confirmRevisionRestore(){if(!pendingRevision)return;const snap=pendingRevision.snapshot?structuredClone(pendingRevision.snapshot):legacyRevisionSnapshot(pendingRevision);recordStoryHistory();storyDraft.revisions.push({id:uid(),at:now(),text:storyText(storyDraft),shots:structuredClone(storyDraft.shots),snapshot:storySnapshot(storyDraft),ready:false,checkpoint:true});$('#dialog').close();restoreStoryContent(snap);recordStoryHistory();pendingRevision=null;toast(uiText('restored_as_a_draft_previous_versions_remain_available'));}
function hookLibrary(){const all=[...state.stories.map(s=>({id:s.id,text:s.hookA,name:s.name,productId:s.productId})),...(state.hooks||[])];return `<div class="card space"><div class="section-title"><h2>${uiText('your_hook_library')}</h2>${storyDraft?btn(uiText('save_this_hook'),'save-hook','small cyan'):''}</div>${all.length?all.slice().reverse().slice(0,30).map(h=>`<div class="task"><div class="grow"><p>${esc(h.text)}</p><small>${esc(h.name||'')}</small></div>${btn(uiText('use'),'use-hook','small',`data-id="${esc(h.id)}"`)}</div>`).join(''):`<p class="sub">${uiText('save_stories_or_useful_hooks_to_reuse_in_a_suitable_con')}</p>`}<p class="sub">${uiText('recheck_the_product_name_and_evidence_when_reusing_a_ho')}</p></div>`;}
function openTeleprompter(){syncStory();recordStoryHistory();stopPrompter();promptElapsed=0;modal(uiText('rehearse_film'),`<div class="prompt-controls"><label>${uiText('text_size')}<input id="prompt-font" type="range" min="22" max="64" value="${promptFont}"></label><label>${uiText('scroll_speed')}<input id="prompt-speed" type="range" min="10" max="100" value="${promptSpeed}"></label></div><div class="row between"><strong id="prompt-clock" aria-live="off">00:00</strong><span class="sub">${uiText('target')}: ${storyDraft.duration}s</span>${btn(uiText('start_rehearsal'),'prompt-toggle','primary')}${btn(uiText('reset'),'prompt-reset','ghost')}</div><div id="prompt-scroll" class="prompt-scroll" tabindex="0"><div id="prompt-text" style="font-size:${promptFont}px">${storyDraft.shots.map((s,i)=>`<section><small>${uiText('scene')} ${i+1} · ${esc(s.time)}s</small><p>${esc(s.voice)}</p></section>`).join('')}</div></div><p class="sub">${uiText('time_your_actual_delivery_this_tool_does_not_record_aud')}</p>`);$('#dialog').classList.add('prompt-dialog');}
function stopPrompter(){promptRunning=false;cancelAnimationFrame(promptFrame);promptFrame=null;$('#dialog')?.classList.remove('prompt-dialog');}
function tickPrompter(ts){if(!promptRunning)return;const elapsed=promptLast?Math.min(100,ts-promptLast):0;promptLast=ts;promptElapsed+=elapsed;const scroll=$('#prompt-scroll');if(!scroll){stopPrompter();return}scroll.scrollTop+=promptSpeed*elapsed/1000;$('#prompt-clock').textContent=String(Math.floor(promptElapsed/60000)).padStart(2,'0')+':'+String(Math.floor(promptElapsed/1000)%60).padStart(2,'0');promptFrame=requestAnimationFrame(tickPrompter);}
function togglePrompter(){promptRunning=!promptRunning;const b=$('[data-action="prompt-toggle"]');b.textContent=promptRunning?uiText('pause'):uiText('start_rehearsal');if(promptRunning){promptLast=0;promptFrame=requestAnimationFrame(tickPrompter)}else cancelAnimationFrame(promptFrame);}
