// Versioned editing sessions; v2 business records and database identity stay unchanged.
let productDrafts={},studioProductId=null;
let productStep=0,studioTab='brief',productFilters={query:'',status:'all',evidence:'all',view:'cards'},draftImage='',sessionStories={},storyHistories={},recoveredAt=null;
let sessionTimer,saveQueue=Promise.resolve(),sessionVersion=0,savedSessionVersion=0,saveFailure=false,businessSaveFailure=false,sessionSaveFailure=false;
function saveIndicator(status){const el=$('#save-status');if(!el)return;el.dataset.state=status;el.textContent=status==='saving'?T('กำลังบันทึกร่าง…','Saving draft…'):status==='error'?T('บันทึกไม่สำเร็จ — ส่งออกสำรองก่อนปิด','Save failed — export a backup before closing'):T('บันทึกในเครื่องแล้ว','Saved on this device');}
function writeRecord(key,value){const snapshot=structuredClone(value);const job=saveQueue.catch(()=>{}).then(()=>new Promise((res,rej)=>{if(!db)return rej(Error(T('พื้นที่บันทึกไม่พร้อม','Storage unavailable')));const tx=db.transaction('workspaces','readwrite');tx.objectStore('workspaces').put(snapshot,key);tx.oncomplete=res;tx.onabort=()=>rej(tx.error||Error('Storage transaction aborted'));tx.onerror=()=>rej(tx.error)}));saveQueue=job;return job;}
function hasProductDraft(d){return !!d&&(!!d.image||Object.entries(d.fields||{}).some(([k,v])=>k!=='analyze:observed'&&v!==''&&v!==false));}
function stashProductDraft(){const d={fields:Object.fromEntries(Object.entries(drafts).filter(([k])=>k.startsWith('analyze:'))),image:draftImage,step:productStep};if(hasProductDraft(d))productDrafts[selected||'_new']=d;}
function switchProductDraft(id){capture();stashProductDraft();selected=product(id)?id:null;clearDraft('analyze');const saved=productDrafts[selected||'_new'];Object.assign(drafts,saved?.fields||{});draftImage=saved?.image||'';productStep=saved?.step||0;}
function sessionSnapshot(){syncStory();capture();stashProductDraft();if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);return {version:1,revision:sessionVersion,updatedAt:now(),page,selected,studioProductId,productDrafts:structuredClone(productDrafts),drafts:structuredClone(drafts),storyDraft:storyDraft?structuredClone(storyDraft):null,sessionStories:structuredClone(sessionStories),storyHistories:structuredClone(storyHistories),productStep,studioTab,productFilters:structuredClone(productFilters),draftImage,planView};}
function journalKey(workspace=mode){return 'aff-session-v1:'+workspace;}
function queueSession(){if(!state)return;sessionVersion++;saveIndicator('saving');const snapshot=sessionSnapshot();try{localStorage.setItem(journalKey(),JSON.stringify(snapshot))}catch{/* IndexedDB remains authoritative; failed writes trigger the leave warning. */}clearTimeout(sessionTimer);sessionTimer=setTimeout(()=>flushSession().catch(()=>{}),450);}
async function flushSession(){clearTimeout(sessionTimer);const workspace=mode,version=sessionVersion,snapshot=sessionSnapshot();saveIndicator('saving');try{await writeRecord('session:'+workspace,snapshot);if(workspace===mode){savedSessionVersion=version;sessionSaveFailure=false;saveFailure=businessSaveFailure;if(saveFailure)saveIndicator('error');else if(version===sessionVersion)saveIndicator('saved')}try{const current=JSON.parse(localStorage.getItem(journalKey(workspace))||'null');if(!current||current.updatedAt<snapshot.updatedAt||(current.updatedAt===snapshot.updatedAt&&(current.revision||0)<=snapshot.revision))localStorage.removeItem(journalKey(workspace))}catch{}}catch(err){sessionSaveFailure=true;saveFailure=true;saveIndicator('error');throw err}}
async function readRecord(key){if(!db)return null;return new Promise((res,rej)=>{const r=db.transaction('workspaces').objectStore('workspaces').get(key);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
function resetSession(){productDrafts={};studioProductId=null;businessSaveFailure=false;sessionSaveFailure=false;drafts={};storyDraft=null;selected=null;productStep=0;studioTab='brief';productFilters={query:'',status:'all',evidence:'all',view:'cards'};sessionStories={};storyHistories={};draftImage='';recoveredAt=null;sessionVersion=0;savedSessionVersion=0;saveFailure=false;}
async function loadSession(){resetSession();let s=await readRecord('session:'+mode);try{const journal=JSON.parse(localStorage.getItem(journalKey())||'null');if(journal?.version===1&&(!s||journal.updatedAt>s.updatedAt||journal.updatedAt===s.updatedAt&&(journal.revision||0)>(s.revision||0)))s=journal}catch{}if(!s||s.version!==1)return;drafts=s.drafts&&typeof s.drafts==='object'?s.drafts:{};selected=product(s.selected)?s.selected:null;studioProductId=product(s.studioProductId)?s.studioProductId:null;productDrafts=s.productDrafts||{};sessionStories=s.sessionStories||{};storyHistories=s.storyHistories||{};storyDraft=s.storyDraft&&product(s.storyDraft.productId)?s.storyDraft:null;for(const [id,d]of Object.entries(sessionStories))if(!product(d.productId))delete sessionStories[id];productStep=Math.max(0,Math.min(3,Number(s.productStep)||0));studioTab=['brief','angles','script','scenes','review','history'].includes(s.studioTab)?s.studioTab:'brief';productFilters={...productFilters,...s.productFilters};draftImage=safeImage(s.draftImage)||'';page=navItems().some(([k])=>k===s.page)?s.page:'today';planView=['list','calendar','board'].includes(s.planView)?s.planView:'list';recoveredAt=s.updatedAt;}
function routeFor(){if(page==='studio'&&storyDraft)return '#studio/'+encodeURIComponent(storyDraft.id);if(page==='analyze'&&selected)return '#analyze/'+encodeURIComponent(selected);return '#'+page;}
function syncRoute(replace=false){const hash=routeFor();if(location.hash!==hash)history[replace?'replaceState':'pushState'](null,'',hash);}
async function navigateTo(next,id=null,{fromHistory=false}={}){syncStory();capture();flushSession().catch(()=>{});if(storyDraft)sessionStories[storyDraft.id]=structuredClone(storyDraft);if(next==='analyze'&&id&&(id==='_new'||product(id))&&(id==='_new'?null:id)!==selected)switchProductDraft(id==='_new'?null:id);page=navItems().some(([k])=>k===next)?next:'today';if(page==='studio'&&id&&(sessionStories[id]||state.stories.some(s=>s.id===id))){storyDraft=structuredClone(sessionStories[id]||state.stories.find(s=>s.id===id));studioProductId=storyDraft.productId;clearDraft('studio');initStoryHistory();if(studioTab==='brief')studioTab='script'}render();if(!fromHistory)syncRoute();queueSession();window.scrollTo(0,0);}
async function applyLocation(){const [route,id]=location.hash.slice(1).split('/');if(!route)return;await navigateTo(route,id?decodeURIComponent(id):null,{fromHistory:true})}
function sessionCards(){const items=Object.values(sessionStories).filter(d=>{const saved=state.stories.find(s=>s.id===d.id);return !saved||JSON.stringify(storySnapshot(saved))!==JSON.stringify(storySnapshot(d))});const products=Object.entries(productDrafts).filter(([,d])=>Object.keys(d.fields||{}).length);if(!items.length&&!products.length)return '';return `<section class="card recovery-card mb"><div class="section-title"><div><div class="eyebrow">CONTINUE CREATING</div><h2>${T('ทำต่อจากครั้งล่าสุด','Pick up where you left off')}</h2></div>${badge(T('ร่างกู้คืนได้','Recoverable drafts'),'green')}</div><div class="actions">${products.map(([id,d])=>btn(esc(d.fields['analyze:title']||T('ร่างสินค้าใหม่','New product draft')),'edit-product','cyan',`data-id="${esc(id)}"`)).join('')}${items.map(d=>btn(esc(d.name||T('ร่างบท','Story draft')),'resume-story','ghost',`data-id="${esc(d.id)}"`)).join('')}</div><p class="sub">${T('ร่างถูกเก็บแยกจากข้อมูลที่ยืนยันแล้ว ยังไม่ถือว่า Ready','Drafts are separate from confirmed records and are not automatically Ready.')}</p></section>`;}
function inlineError(id,message){const el=document.getElementById(id);if(!el){toast(message);return}el.setAttribute('aria-invalid','true');let err=document.getElementById(id+'-error');if(!err){err=document.createElement('p');err.id=id+'-error';err.className='field-error';el.after(err)}err.textContent=message;el.setAttribute('aria-describedby',err.id);if(page==='analyze'){const step=el.closest('[data-product-step]');if(step){productStep=Number(step.dataset.productStep);applyProductStep()}}for(let parent=el.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;el.focus();el.scrollIntoView({block:'center',behavior:'smooth'});}
function clearFieldError(el){el.removeAttribute('aria-invalid');el.removeAttribute('aria-describedby');document.getElementById(el.id+'-error')?.remove();}
function validateForm(form){const invalid=[...form.querySelectorAll('input,select,textarea')].find(e=>!e.validity.valid);if(invalid){inlineError(invalid.id,T('ตรวจช่องนี้: ','Check this field: ')+invalid.validationMessage);return false}return true;}
function enhanceView(){if(page==='today')$('#main').insertAdjacentHTML('afterbegin',sessionCards());if(page==='analyze')applyProductStep();if(page==='studio')applyStudioTab();saveIndicator(saveFailure?'error':sessionVersion>savedSessionVersion?'saving':'saved');if(recoveredAt){$('#save-status').title=T('กู้ร่างล่าสุดแล้ว','Latest editing session recovered')}$$('form').forEach(f=>f.noValidate=true);}
window.addEventListener('hashchange',()=>applyLocation().catch(e=>toast(e.message)));
window.addEventListener('pagehide',()=>{if(state){try{localStorage.setItem(journalKey(),JSON.stringify(sessionSnapshot()))}catch{}flushSession().catch(()=>{})}});
